@class NSString;

@interface AWDBiometricKitMatchAttempt : PBCodable <NSCopying> {
    struct { unsigned long long *list; unsigned long long count; unsigned long long size; } _identityCreationTimes;
    struct { unsigned char bioCheckEndTime : 1; unsigned char faceDetectEndTime : 1; unsigned char overallTime : 1; unsigned char overallTimeWithRetries : 1; unsigned char probingPatternEndTime : 1; unsigned char rfcFrameIndex : 1; unsigned char rfcSetIndex : 1; unsigned char timeSinceSleep : 1; unsigned char timestamp : 1; unsigned char ambientLux : 1; unsigned char bioCheckCamRectH : 1; unsigned char bioCheckCamRectW : 1; unsigned char bioCheckCamRectX : 1; unsigned char bioCheckCamRectY : 1; unsigned char bioCheckFaceDistance : 1; unsigned char bioCheckFrameCount : 1; unsigned char bioCheckFrameDenseCount : 1; unsigned char bioCheckFrameFloodCount : 1; unsigned char bioCheckFrameSparseCount : 1; unsigned char bioCheckPPMAllocatedBudget : 1; unsigned char bioCheckPPMRequestedBudget : 1; unsigned char bioCheckResult : 1; unsigned char bioLockoutReason : 1; unsigned char camRectH : 1; unsigned char camRectW : 1; unsigned char camRectX : 1; unsigned char camRectY : 1; unsigned char cameraErr : 1; unsigned char captureMethod : 1; unsigned char deviceOrientation : 1; unsigned char faceDetectCamRectH : 1; unsigned char faceDetectCamRectW : 1; unsigned char faceDetectCamRectX : 1; unsigned char faceDetectCamRectY : 1; unsigned char faceDetectFaceDistance : 1; unsigned char faceDetectFrameCount : 1; unsigned char faceDetectFrameDenseCount : 1; unsigned char faceDetectFrameFloodCount : 1; unsigned char faceDetectFrameSparseCount : 1; unsigned char faceDetectPPMAllocatedBudget : 1; unsigned char faceDetectPPMRequestedBudget : 1; unsigned char faceDetectResult : 1; unsigned char faceDistance : 1; unsigned char faceOrientation : 1; unsigned char facePitch : 1; unsigned char faceRoll : 1; unsigned char faceYaw : 1; unsigned char failedMatchAttemptsFromBiocheck : 1; unsigned char failedMatchAttemptsFromFD : 1; unsigned char failedUnlockAttemptsFromBiocheck : 1; unsigned char failedUnlockAttemptsFromFD : 1; unsigned char featureGenerationError : 1; unsigned char matchFeatureVectorError : 1; unsigned char matchIdentityCount : 1; unsigned char matchType : 1; unsigned char onlineTemplateAge : 1; unsigned char probingPatternCamRectH : 1; unsigned char probingPatternCamRectW : 1; unsigned char probingPatternCamRectX : 1; unsigned char probingPatternCamRectY : 1; unsigned char probingPatternFaceDistance : 1; unsigned char probingPatternFrameCount : 1; unsigned char probingPatternFrameDenseCount : 1; unsigned char probingPatternFrameFloodCount : 1; unsigned char probingPatternFrameSparseCount : 1; unsigned char probingPatternResult : 1; unsigned char sensorTemperature : 1; unsigned char shortTermTemplateAge : 1; unsigned char asDepthFailure : 1; unsigned char asFailure : 1; unsigned char asFloodFailure : 1; unsigned char autoRetry : 1; unsigned char autoRetryAllowed : 1; unsigned char autoRetryEnabled : 1; unsigned char bioLockout : 1; unsigned char combinedSequenceEnabled : 1; unsigned char engagementInfoFeedbackCameraObstructed : 1; unsigned char engagementInfoFeedbackFaceOccluded : 1; unsigned char engagementInfoFeedbackFaceTooClose : 1; unsigned char engagementInfoFeedbackFaceTooFar : 1; unsigned char engagementInfoFeedbackNoAttention : 1; unsigned char engagementInfoFeedbackNoFaceDetected : 1; unsigned char engagementInfoFeedbackNoseAndMouthOccluded : 1; unsigned char engagementInfoFeedbackPartialOutOfFOV : 1; unsigned char engagementInfoFeedbackPoseMarginal : 1; unsigned char engagementInfoFeedbackPoseOutOfRange : 1; unsigned char hasOcclusion : 1; unsigned char matchCancelled : 1; unsigned char matchDepthFailure : 1; unsigned char matchFloodFailure : 1; unsigned char matchForUnlock : 1; unsigned char matcherFailure : 1; unsigned char onlineTemplateUpdated : 1; unsigned char overallResult : 1; unsigned char passcodeChallengeAllowed : 1; unsigned char probingPatternFailure : 1; } _has;
}

@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) unsigned long long timestamp;
@property (nonatomic) BOOL hasOverallResult;
@property (nonatomic) BOOL overallResult;
@property (nonatomic) BOOL hasOverallTime;
@property (nonatomic) unsigned long long overallTime;
@property (nonatomic) BOOL hasFaceDetectEndTime;
@property (nonatomic) unsigned long long faceDetectEndTime;
@property (nonatomic) BOOL hasFaceDetectResult;
@property (nonatomic) unsigned int faceDetectResult;
@property (nonatomic) BOOL hasFaceDetectFrameCount;
@property (nonatomic) unsigned int faceDetectFrameCount;
@property (nonatomic) BOOL hasFaceDetectFrameFloodCount;
@property (nonatomic) unsigned int faceDetectFrameFloodCount;
@property (nonatomic) BOOL hasFaceDetectFrameSparseCount;
@property (nonatomic) unsigned int faceDetectFrameSparseCount;
@property (nonatomic) BOOL hasFaceDetectFrameDenseCount;
@property (nonatomic) unsigned int faceDetectFrameDenseCount;
@property (nonatomic) BOOL hasBioCheckEndTime;
@property (nonatomic) unsigned long long bioCheckEndTime;
@property (nonatomic) BOOL hasBioCheckResult;
@property (nonatomic) int bioCheckResult;
@property (nonatomic) BOOL hasBioCheckFrameCount;
@property (nonatomic) unsigned int bioCheckFrameCount;
@property (nonatomic) BOOL hasBioCheckFrameFloodCount;
@property (nonatomic) unsigned int bioCheckFrameFloodCount;
@property (nonatomic) BOOL hasBioCheckFrameSparseCount;
@property (nonatomic) unsigned int bioCheckFrameSparseCount;
@property (nonatomic) BOOL hasBioCheckFrameDenseCount;
@property (nonatomic) unsigned int bioCheckFrameDenseCount;
@property (nonatomic) BOOL hasProbingPatternEndTime;
@property (nonatomic) unsigned long long probingPatternEndTime;
@property (nonatomic) BOOL hasProbingPatternResult;
@property (nonatomic) int probingPatternResult;
@property (nonatomic) BOOL hasProbingPatternFrameCount;
@property (nonatomic) unsigned int probingPatternFrameCount;
@property (nonatomic) BOOL hasProbingPatternFrameFloodCount;
@property (nonatomic) unsigned int probingPatternFrameFloodCount;
@property (nonatomic) BOOL hasProbingPatternFrameSparseCount;
@property (nonatomic) unsigned int probingPatternFrameSparseCount;
@property (nonatomic) BOOL hasProbingPatternFrameDenseCount;
@property (nonatomic) unsigned int probingPatternFrameDenseCount;
@property (nonatomic) BOOL hasAmbientLux;
@property (nonatomic) int ambientLux;
@property (nonatomic) BOOL hasProbingPatternFailure;
@property (nonatomic) BOOL probingPatternFailure;
@property (nonatomic) BOOL hasMatcherFailure;
@property (nonatomic) BOOL matcherFailure;
@property (nonatomic) BOOL hasMatchDepthFailure;
@property (nonatomic) BOOL matchDepthFailure;
@property (nonatomic) BOOL hasMatchFloodFailure;
@property (nonatomic) BOOL matchFloodFailure;
@property (nonatomic) BOOL hasAsFloodFailure;
@property (nonatomic) BOOL asFloodFailure;
@property (nonatomic) BOOL hasAsDepthFailure;
@property (nonatomic) BOOL asDepthFailure;
@property (nonatomic) BOOL hasOnlineTemplateUpdated;
@property (nonatomic) BOOL onlineTemplateUpdated;
@property (nonatomic) BOOL hasPasscodeChallengeAllowed;
@property (nonatomic) BOOL passcodeChallengeAllowed;
@property (nonatomic) BOOL hasFeatureGenerationError;
@property (nonatomic) unsigned int featureGenerationError;
@property (nonatomic) BOOL hasSensorTemperature;
@property (nonatomic) int sensorTemperature;
@property (nonatomic) BOOL hasFaceDistance;
@property (nonatomic) unsigned int faceDistance;
@property (nonatomic) BOOL hasHasOcclusion;
@property (nonatomic) BOOL hasOcclusion;
@property (nonatomic) BOOL hasCamRectX;
@property (nonatomic) unsigned int camRectX;
@property (nonatomic) BOOL hasCamRectY;
@property (nonatomic) unsigned int camRectY;
@property (nonatomic) BOOL hasCamRectW;
@property (nonatomic) unsigned int camRectW;
@property (nonatomic) BOOL hasCamRectH;
@property (nonatomic) unsigned int camRectH;
@property (nonatomic) BOOL hasFaceDetectPPMRequestedBudget;
@property (nonatomic) unsigned int faceDetectPPMRequestedBudget;
@property (nonatomic) BOOL hasFaceDetectPPMAllocatedBudget;
@property (nonatomic) unsigned int faceDetectPPMAllocatedBudget;
@property (nonatomic) BOOL hasBioCheckPPMRequestedBudget;
@property (nonatomic) unsigned int bioCheckPPMRequestedBudget;
@property (nonatomic) BOOL hasBioCheckPPMAllocatedBudget;
@property (nonatomic) unsigned int bioCheckPPMAllocatedBudget;
@property (nonatomic) BOOL hasRfcSetIndex;
@property (nonatomic) long long rfcSetIndex;
@property (nonatomic) BOOL hasRfcFrameIndex;
@property (nonatomic) long long rfcFrameIndex;
@property (nonatomic) BOOL hasBioLockout;
@property (nonatomic) BOOL bioLockout;
@property (nonatomic) BOOL hasCameraErr;
@property (nonatomic) int cameraErr;
@property (nonatomic) BOOL hasMatchForUnlock;
@property (nonatomic) BOOL matchForUnlock;
@property (nonatomic) BOOL hasFailedUnlockAttemptsFromFD;
@property (nonatomic) unsigned int failedUnlockAttemptsFromFD;
@property (nonatomic) BOOL hasFailedUnlockAttemptsFromBiocheck;
@property (nonatomic) unsigned int failedUnlockAttemptsFromBiocheck;
@property (nonatomic) BOOL hasFailedMatchAttemptsFromFD;
@property (nonatomic) unsigned int failedMatchAttemptsFromFD;
@property (nonatomic) BOOL hasFailedMatchAttemptsFromBiocheck;
@property (nonatomic) unsigned int failedMatchAttemptsFromBiocheck;
@property (nonatomic) BOOL hasBioLockoutReason;
@property (nonatomic) unsigned int bioLockoutReason;
@property (nonatomic) BOOL hasMatchFeatureVectorError;
@property (nonatomic) unsigned int matchFeatureVectorError;
@property (nonatomic) BOOL hasOnlineTemplateAge;
@property (nonatomic) int onlineTemplateAge;
@property (nonatomic) BOOL hasShortTermTemplateAge;
@property (nonatomic) int shortTermTemplateAge;
@property (nonatomic) BOOL hasFaceDetectFaceDistance;
@property (nonatomic) unsigned int faceDetectFaceDistance;
@property (nonatomic) BOOL hasFaceDetectCamRectX;
@property (nonatomic) unsigned int faceDetectCamRectX;
@property (nonatomic) BOOL hasFaceDetectCamRectY;
@property (nonatomic) unsigned int faceDetectCamRectY;
@property (nonatomic) BOOL hasFaceDetectCamRectW;
@property (nonatomic) unsigned int faceDetectCamRectW;
@property (nonatomic) BOOL hasFaceDetectCamRectH;
@property (nonatomic) unsigned int faceDetectCamRectH;
@property (nonatomic) BOOL hasBioCheckFaceDistance;
@property (nonatomic) unsigned int bioCheckFaceDistance;
@property (nonatomic) BOOL hasBioCheckCamRectX;
@property (nonatomic) unsigned int bioCheckCamRectX;
@property (nonatomic) BOOL hasBioCheckCamRectY;
@property (nonatomic) unsigned int bioCheckCamRectY;
@property (nonatomic) BOOL hasBioCheckCamRectW;
@property (nonatomic) unsigned int bioCheckCamRectW;
@property (nonatomic) BOOL hasBioCheckCamRectH;
@property (nonatomic) unsigned int bioCheckCamRectH;
@property (nonatomic) BOOL hasProbingPatternFaceDistance;
@property (nonatomic) unsigned int probingPatternFaceDistance;
@property (nonatomic) BOOL hasProbingPatternCamRectX;
@property (nonatomic) unsigned int probingPatternCamRectX;
@property (nonatomic) BOOL hasProbingPatternCamRectY;
@property (nonatomic) unsigned int probingPatternCamRectY;
@property (nonatomic) BOOL hasProbingPatternCamRectW;
@property (nonatomic) unsigned int probingPatternCamRectW;
@property (nonatomic) BOOL hasProbingPatternCamRectH;
@property (nonatomic) unsigned int probingPatternCamRectH;
@property (nonatomic) BOOL hasAsFailure;
@property (nonatomic) BOOL asFailure;
@property (nonatomic) BOOL hasAutoRetry;
@property (nonatomic) BOOL autoRetry;
@property (nonatomic) BOOL hasAutoRetryAllowed;
@property (nonatomic) BOOL autoRetryAllowed;
@property (nonatomic) BOOL hasDeviceOrientation;
@property (nonatomic) unsigned int deviceOrientation;
@property (nonatomic) BOOL hasMatchIdentityCount;
@property (nonatomic) unsigned int matchIdentityCount;
@property (readonly, nonatomic) BOOL hasCameraHWParameters;
@property (retain, nonatomic) NSString *cameraHWParameters;
@property (nonatomic) BOOL hasCaptureMethod;
@property (nonatomic) unsigned int captureMethod;
@property (nonatomic) BOOL hasEngagementInfoFeedbackNoFaceDetected;
@property (nonatomic) BOOL engagementInfoFeedbackNoFaceDetected;
@property (nonatomic) BOOL hasEngagementInfoFeedbackFaceTooClose;
@property (nonatomic) BOOL engagementInfoFeedbackFaceTooClose;
@property (nonatomic) BOOL hasEngagementInfoFeedbackFaceTooFar;
@property (nonatomic) BOOL engagementInfoFeedbackFaceTooFar;
@property (nonatomic) BOOL hasEngagementInfoFeedbackPoseOutOfRange;
@property (nonatomic) BOOL engagementInfoFeedbackPoseOutOfRange;
@property (nonatomic) BOOL hasEngagementInfoFeedbackNoAttention;
@property (nonatomic) BOOL engagementInfoFeedbackNoAttention;
@property (nonatomic) BOOL hasEngagementInfoFeedbackFaceOccluded;
@property (nonatomic) BOOL engagementInfoFeedbackFaceOccluded;
@property (nonatomic) BOOL hasEngagementInfoFeedbackCameraObstructed;
@property (nonatomic) BOOL engagementInfoFeedbackCameraObstructed;
@property (nonatomic) BOOL hasEngagementInfoFeedbackPartialOutOfFOV;
@property (nonatomic) BOOL engagementInfoFeedbackPartialOutOfFOV;
@property (nonatomic) BOOL hasCombinedSequenceEnabled;
@property (nonatomic) BOOL combinedSequenceEnabled;
@property (nonatomic) BOOL hasOverallTimeWithRetries;
@property (nonatomic) unsigned long long overallTimeWithRetries;
@property (nonatomic) BOOL hasAutoRetryEnabled;
@property (nonatomic) BOOL autoRetryEnabled;
@property (readonly, nonatomic) unsigned long long identityCreationTimesCount;
@property (readonly, nonatomic) unsigned long long *identityCreationTimes;
@property (nonatomic) BOOL hasMatchCancelled;
@property (nonatomic) BOOL matchCancelled;
@property (nonatomic) BOOL hasEngagementInfoFeedbackPoseMarginal;
@property (nonatomic) BOOL engagementInfoFeedbackPoseMarginal;
@property (nonatomic) BOOL hasFaceOrientation;
@property (nonatomic) unsigned int faceOrientation;
@property (nonatomic) BOOL hasFacePitch;
@property (nonatomic) int facePitch;
@property (nonatomic) BOOL hasFaceYaw;
@property (nonatomic) int faceYaw;
@property (nonatomic) BOOL hasFaceRoll;
@property (nonatomic) int faceRoll;
@property (nonatomic) BOOL hasTimeSinceSleep;
@property (nonatomic) unsigned long long timeSinceSleep;
@property (nonatomic) BOOL hasEngagementInfoFeedbackNoseAndMouthOccluded;
@property (nonatomic) BOOL engagementInfoFeedbackNoseAndMouthOccluded;
@property (nonatomic) BOOL hasMatchType;
@property (nonatomic) unsigned int matchType;

- (id)copyWithZone:(struct _NSZone { } *)a0;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)a0;
- (void)dealloc;
- (void)mergeFrom:(id)a0;
- (BOOL)isEqual:(id)a0;
- (unsigned long long)hash;
- (void)writeTo:(id)a0;
- (BOOL)readFrom:(id)a0;
- (id)description;
- (void).cxx_destruct;
- (void)setIdentityCreationTimes:(unsigned long long *)a0 count:(unsigned long long)a1;
- (void)addIdentityCreationTime:(unsigned long long)a0;
- (void)clearIdentityCreationTimes;
- (unsigned long long)identityCreationTimeAtIndex:(unsigned long long)a0;

@end
