@interface AWDBiometricKitEnrollAttempt : PBCodable <NSCopying> {
    struct { unsigned char overallTime : 1; unsigned char rfcFrameIndex : 1; unsigned char rfcSetIndex : 1; unsigned char timestamp : 1; unsigned char ambientLux : 1; unsigned char bioCaptureSequenceCount : 1; unsigned char cameraErr : 1; unsigned char deviceOrientation : 1; unsigned char doubleErrorCountsBinCovered : 1; unsigned char doubleErrorCountsFaceOutOfFOV : 1; unsigned char doubleErrorCountsFaceTooClose : 1; unsigned char doubleErrorCountsFaceTooFar : 1; unsigned char doubleErrorCountsLowerFaceOccluded : 1; unsigned char doubleErrorCountsMoreFrames : 1; unsigned char doubleErrorCountsMultipleFaces : 1; unsigned char doubleErrorCountsNoFace : 1; unsigned char doubleErrorCountsOK : 1; unsigned char doubleErrorCountsOccluded : 1; unsigned char doubleErrorCountsPoseOutRange : 1; unsigned char doubleErrorCountsUpperFaceOccluded : 1; unsigned char enrollFeatureVectorError : 1; unsigned char enrollResult : 1; unsigned char enrollType : 1; unsigned char enrolledIdentityCount : 1; unsigned char enrolledTemplateCountTotal : 1; unsigned char enrolledTemplateCountType0 : 1; unsigned char enrolledTemplateCountType1 : 1; unsigned char faceDistance : 1; unsigned char featureGenerationError : 1; unsigned char frameCountBin00 : 1; unsigned char frameCountBin01 : 1; unsigned char frameCountBin02 : 1; unsigned char frameCountBin10 : 1; unsigned char frameCountBin11 : 1; unsigned char frameCountBin12 : 1; unsigned char frameCountBin20 : 1; unsigned char frameCountBin21 : 1; unsigned char frameCountBin22 : 1; unsigned char frameErrorCountsBinCovered : 1; unsigned char frameErrorCountsFaceOutOfFOV : 1; unsigned char frameErrorCountsFaceTooClose : 1; unsigned char frameErrorCountsFaceTooFar : 1; unsigned char frameErrorCountsLowerFaceOccluded : 1; unsigned char frameErrorCountsMoreFrames : 1; unsigned char frameErrorCountsMultipleFaces : 1; unsigned char frameErrorCountsNoFace : 1; unsigned char frameErrorCountsOK : 1; unsigned char frameErrorCountsOccluded : 1; unsigned char frameErrorCountsPoseOutRange : 1; unsigned char frameErrorCountsUpperFaceOccluded : 1; unsigned char sensorTemperature : 1; unsigned char failedNoFace : 1; unsigned char noseAndMouthOccluded : 1; unsigned char overallResult : 1; } _has;
}

@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) unsigned long long timestamp;
@property (nonatomic) BOOL hasOverallResult;
@property (nonatomic) BOOL overallResult;
@property (nonatomic) BOOL hasOverallTime;
@property (nonatomic) unsigned long long overallTime;
@property (nonatomic) BOOL hasDoubleErrorCountsOK;
@property (nonatomic) unsigned int doubleErrorCountsOK;
@property (nonatomic) BOOL hasDoubleErrorCountsMoreFrames;
@property (nonatomic) unsigned int doubleErrorCountsMoreFrames;
@property (nonatomic) BOOL hasDoubleErrorCountsNoFace;
@property (nonatomic) unsigned int doubleErrorCountsNoFace;
@property (nonatomic) BOOL hasDoubleErrorCountsFaceOutOfFOV;
@property (nonatomic) unsigned int doubleErrorCountsFaceOutOfFOV;
@property (nonatomic) BOOL hasDoubleErrorCountsMultipleFaces;
@property (nonatomic) unsigned int doubleErrorCountsMultipleFaces;
@property (nonatomic) BOOL hasDoubleErrorCountsFaceTooClose;
@property (nonatomic) unsigned int doubleErrorCountsFaceTooClose;
@property (nonatomic) BOOL hasDoubleErrorCountsFaceTooFar;
@property (nonatomic) unsigned int doubleErrorCountsFaceTooFar;
@property (nonatomic) BOOL hasDoubleErrorCountsPoseOutRange;
@property (nonatomic) unsigned int doubleErrorCountsPoseOutRange;
@property (nonatomic) BOOL hasDoubleErrorCountsBinCovered;
@property (nonatomic) unsigned int doubleErrorCountsBinCovered;
@property (nonatomic) BOOL hasDoubleErrorCountsOccluded;
@property (nonatomic) unsigned int doubleErrorCountsOccluded;
@property (nonatomic) BOOL hasFrameErrorCountsOK;
@property (nonatomic) unsigned int frameErrorCountsOK;
@property (nonatomic) BOOL hasFrameErrorCountsMoreFrames;
@property (nonatomic) unsigned int frameErrorCountsMoreFrames;
@property (nonatomic) BOOL hasFrameErrorCountsNoFace;
@property (nonatomic) unsigned int frameErrorCountsNoFace;
@property (nonatomic) BOOL hasFrameErrorCountsFaceOutOfFOV;
@property (nonatomic) unsigned int frameErrorCountsFaceOutOfFOV;
@property (nonatomic) BOOL hasFrameErrorCountsMultipleFaces;
@property (nonatomic) unsigned int frameErrorCountsMultipleFaces;
@property (nonatomic) BOOL hasFrameErrorCountsFaceTooClose;
@property (nonatomic) unsigned int frameErrorCountsFaceTooClose;
@property (nonatomic) BOOL hasFrameErrorCountsFaceTooFar;
@property (nonatomic) unsigned int frameErrorCountsFaceTooFar;
@property (nonatomic) BOOL hasFrameErrorCountsPoseOutRange;
@property (nonatomic) unsigned int frameErrorCountsPoseOutRange;
@property (nonatomic) BOOL hasFrameErrorCountsBinCovered;
@property (nonatomic) unsigned int frameErrorCountsBinCovered;
@property (nonatomic) BOOL hasFrameErrorCountsOccluded;
@property (nonatomic) unsigned int frameErrorCountsOccluded;
@property (nonatomic) BOOL hasFrameCountBin00;
@property (nonatomic) int frameCountBin00;
@property (nonatomic) BOOL hasFrameCountBin01;
@property (nonatomic) int frameCountBin01;
@property (nonatomic) BOOL hasFrameCountBin02;
@property (nonatomic) int frameCountBin02;
@property (nonatomic) BOOL hasFrameCountBin10;
@property (nonatomic) int frameCountBin10;
@property (nonatomic) BOOL hasFrameCountBin11;
@property (nonatomic) int frameCountBin11;
@property (nonatomic) BOOL hasFrameCountBin12;
@property (nonatomic) int frameCountBin12;
@property (nonatomic) BOOL hasFrameCountBin20;
@property (nonatomic) int frameCountBin20;
@property (nonatomic) BOOL hasFrameCountBin21;
@property (nonatomic) int frameCountBin21;
@property (nonatomic) BOOL hasFrameCountBin22;
@property (nonatomic) int frameCountBin22;
@property (nonatomic) BOOL hasBioCaptureSequenceCount;
@property (nonatomic) unsigned int bioCaptureSequenceCount;
@property (nonatomic) BOOL hasAmbientLux;
@property (nonatomic) int ambientLux;
@property (nonatomic) BOOL hasFeatureGenerationError;
@property (nonatomic) unsigned int featureGenerationError;
@property (nonatomic) BOOL hasEnrollFeatureVectorError;
@property (nonatomic) unsigned int enrollFeatureVectorError;
@property (nonatomic) BOOL hasCameraErr;
@property (nonatomic) int cameraErr;
@property (nonatomic) BOOL hasEnrollResult;
@property (nonatomic) unsigned int enrollResult;
@property (nonatomic) BOOL hasFaceDistance;
@property (nonatomic) unsigned int faceDistance;
@property (nonatomic) BOOL hasSensorTemperature;
@property (nonatomic) int sensorTemperature;
@property (nonatomic) BOOL hasRfcSetIndex;
@property (nonatomic) long long rfcSetIndex;
@property (nonatomic) BOOL hasRfcFrameIndex;
@property (nonatomic) long long rfcFrameIndex;
@property (nonatomic) BOOL hasFailedNoFace;
@property (nonatomic) BOOL failedNoFace;
@property (nonatomic) BOOL hasDeviceOrientation;
@property (nonatomic) unsigned int deviceOrientation;
@property (nonatomic) BOOL hasEnrolledIdentityCount;
@property (nonatomic) unsigned int enrolledIdentityCount;
@property (nonatomic) BOOL hasNoseAndMouthOccluded;
@property (nonatomic) BOOL noseAndMouthOccluded;
@property (nonatomic) BOOL hasDoubleErrorCountsUpperFaceOccluded;
@property (nonatomic) unsigned int doubleErrorCountsUpperFaceOccluded;
@property (nonatomic) BOOL hasDoubleErrorCountsLowerFaceOccluded;
@property (nonatomic) unsigned int doubleErrorCountsLowerFaceOccluded;
@property (nonatomic) BOOL hasFrameErrorCountsUpperFaceOccluded;
@property (nonatomic) unsigned int frameErrorCountsUpperFaceOccluded;
@property (nonatomic) BOOL hasFrameErrorCountsLowerFaceOccluded;
@property (nonatomic) unsigned int frameErrorCountsLowerFaceOccluded;
@property (nonatomic) BOOL hasEnrollType;
@property (nonatomic) unsigned int enrollType;
@property (nonatomic) BOOL hasEnrolledTemplateCountType0;
@property (nonatomic) unsigned int enrolledTemplateCountType0;
@property (nonatomic) BOOL hasEnrolledTemplateCountType1;
@property (nonatomic) unsigned int enrolledTemplateCountType1;
@property (nonatomic) BOOL hasEnrolledTemplateCountTotal;
@property (nonatomic) unsigned int enrolledTemplateCountTotal;

- (id)copyWithZone:(struct _NSZone { } *)a0;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)a0;
- (void)mergeFrom:(id)a0;
- (BOOL)isEqual:(id)a0;
- (unsigned long long)hash;
- (void)writeTo:(id)a0;
- (BOOL)readFrom:(id)a0;
- (id)description;

@end
