@class NSNumber;

@interface PearlCoreAnalyticsDailyTemplateMatchCountsEvent : PearlCoreAnalyticsEvent

@property (retain) NSNumber *enrolledIdentityCount;
@property (retain) NSNumber *enrolledTemplateCount;
@property (retain) NSNumber *enrolledTemplateCountType0;
@property (retain) NSNumber *enrolledTemplateCountType0NoGlasses;
@property (retain) NSNumber *enrolledTemplateCountType0WithGlasses;
@property (retain) NSNumber *enrolledTemplateCountType0Unknown;
@property (retain) NSNumber *templateType1Enrolled;
@property (retain) NSNumber *enrolledTemplateCountType1;
@property (retain) NSNumber *enrolledTemplateCountType1NoGlasses;
@property (retain) NSNumber *enrolledTemplateCountType1WithGlasses;
@property (retain) NSNumber *enrolledTemplateCountType1Unknown;
@property (retain) NSNumber *identity0EnrolledTemplateCountType0;
@property (retain) NSNumber *identity0EnrolledTemplateCountType0NoGlasses;
@property (retain) NSNumber *identity0EnrolledTemplateCountType0WithGlasses;
@property (retain) NSNumber *identity0EnrolledTemplateCountType0Unknown;
@property (retain) NSNumber *identity0TemplateType1Enrolled;
@property (retain) NSNumber *identity0Type1MainTemplateHasGlasses;
@property (retain) NSNumber *identity0EnrolledTemplateCountType1;
@property (retain) NSNumber *identity0EnrolledTemplateCountType1NoGlasses;
@property (retain) NSNumber *identity0EnrolledTemplateCountType1WithGlasses;
@property (retain) NSNumber *identity0EnrolledTemplateCountType1Unknown;
@property (retain) NSNumber *identity1EnrolledTemplateCountType0;
@property (retain) NSNumber *identity1EnrolledTemplateCountType0NoGlasses;
@property (retain) NSNumber *identity1EnrolledTemplateCountType0WithGlasses;
@property (retain) NSNumber *identity1EnrolledTemplateCountType0Unknown;
@property (retain) NSNumber *identity1TemplateType1Enrolled;
@property (retain) NSNumber *identity1Type1MainTemplateHasGlasses;
@property (retain) NSNumber *identity1EnrolledTemplateCountType1;
@property (retain) NSNumber *identity1EnrolledTemplateCountType1NoGlasses;
@property (retain) NSNumber *identity1EnrolledTemplateCountType1WithGlasses;
@property (retain) NSNumber *identity1EnrolledTemplateCountType1Unknown;
@property (retain) NSNumber *matchingTemplateCountType0;
@property (retain) NSNumber *matchingTemplateCountType0WithGlasses;
@property (retain) NSNumber *matchingTemplateCountType0NoGlasses;
@property (retain) NSNumber *matchingTemplateCountType0Unknown;
@property (retain) NSNumber *matchingTemplateCountType1;
@property (retain) NSNumber *matchingTemplateCountType1WithGlasses;
@property (retain) NSNumber *matchingTemplateCountType1NoGlasses;
@property (retain) NSNumber *matchingTemplateCountType1Unknown;
@property (retain) NSNumber *matchingTemplateCountType1MainTemplate;
@property (retain) NSNumber *identity0MatchingTemplateCountType0;
@property (retain) NSNumber *identity0MatchingTemplateCountType0WithGlasses;
@property (retain) NSNumber *identity0MatchingTemplateCountType0NoGlasses;
@property (retain) NSNumber *identity0MatchingTemplateCountType0Unknown;
@property (retain) NSNumber *identity0MatchingTemplateCountType1;
@property (retain) NSNumber *identity0MatchingTemplateCountType1WithGlasses;
@property (retain) NSNumber *identity0MatchingTemplateCountType1NoGlasses;
@property (retain) NSNumber *identity0MatchingTemplateCountType1Unknown;
@property (retain) NSNumber *identity0MatchingTemplateCountType1MainTemplate;
@property (retain) NSNumber *identity1MatchingTemplateCountType0;
@property (retain) NSNumber *identity1MatchingTemplateCountType0WithGlasses;
@property (retain) NSNumber *identity1MatchingTemplateCountType0NoGlasses;
@property (retain) NSNumber *identity1MatchingTemplateCountType0Unknown;
@property (retain) NSNumber *identity1MatchingTemplateCountType1;
@property (retain) NSNumber *identity1MatchingTemplateCountType1WithGlasses;
@property (retain) NSNumber *identity1MatchingTemplateCountType1NoGlasses;
@property (retain) NSNumber *identity1MatchingTemplateCountType1Unknown;
@property (retain) NSNumber *identity1MatchingTemplateCountType1MainTemplate;
@property (retain) NSNumber *identity0BaseTemplateFeatureCountType0;
@property (retain) NSNumber *identity0OnlineUpdateTemplateFeatureCountType0;
@property (retain) NSNumber *identity0PasscodeUpdateTemplateFeatureCountType0;
@property (retain) NSNumber *identity0BaseTemplateFeatureCountType1;
@property (retain) NSNumber *identity0OnlineUpdateTemplateFeatureCountType1;
@property (retain) NSNumber *identity0PasscodeUpdateTemplateFeatureCountType1;
@property (retain) NSNumber *identity1BaseTemplateFeatureCountType0;
@property (retain) NSNumber *identity1OnlineUpdateTemplateFeatureCountType0;
@property (retain) NSNumber *identity1PasscodeUpdateTemplateFeatureCountType0;
@property (retain) NSNumber *identity1BaseTemplateFeatureCountType1;
@property (retain) NSNumber *identity1OnlineUpdateTemplateFeatureCountType1;
@property (retain) NSNumber *identity1PasscodeUpdateTemplateFeatureCountType1;

- (BOOL)postAWDMetric;
- (void)setTemplateInfo:(id)a0;
- (id)initWithTemplateInfo:(id)a0;
- (void).cxx_destruct;
- (void)reset;

@end
