@class NSMutableDictionary;

@interface QUICLog : NSObject {
    struct { struct quiclog_event *stqh_first; struct quiclog_event **stqh_last; } events_list;
    NSMutableDictionary *top_level_object;
    BOOL disable_timestamps;
}

+ (id)eventTypeString:(int)a0;
+ (id)categoryString:(int)a0;
+ (id)flowTypeString:(unsigned char)a0;
+ (id)congestionStateString:(unsigned char)a0;
+ (id)congestionTriggerString:(unsigned char)a0;
+ (id)ownerString:(unsigned char)a0;
+ (id)packetLostTriggerString:(unsigned char)a0;
+ (id)packetSentRecievedTriggerString:(int)a0;
+ (int)packetType:(struct quic_packet { char *x0; char *x1; char *x2; char *x3; char *x4; unsigned char x5[21]; unsigned char x6[21]; unsigned char x7; unsigned char x8; unsigned char x9; unsigned char x10; unsigned char x11; unsigned char x12; unsigned short x13; unsigned short x14; unsigned short x15; union { unsigned short x0; unsigned short x1; } x16; union { char *x0; unsigned int *x1; } x17; int x18; unsigned int x19; unsigned long long x20; unsigned long long x21; unsigned long long x22; struct quic_packet_pool *x23; struct quic_path *x24; struct { struct quic_frame *x0; struct quic_frame **x1; } x25; struct { struct quic_packet *x0; struct quic_packet **x1; } x26; struct { struct quic_packet *x0; struct quic_packet **x1; } x27; struct { struct quic_packet *x0; struct quic_packet **x1; } x28; struct { struct quic_packet *x0; } x29; unsigned long long x30; unsigned char x31 : 1; unsigned char x32 : 1; unsigned char x33 : 1; unsigned char x34 : 1; unsigned char x35 : 1; unsigned char x36 : 1; unsigned char x37 : 1; unsigned char x38 : 1; unsigned char x39 : 1; unsigned char x40 : 1; unsigned char x41 : 1; unsigned char x42 : 1; unsigned char x43 : 1; unsigned char x44 : 1; unsigned char x45 : 1; unsigned int x46 : 17; unsigned char x47[4]; } *)a0;
+ (id)packetTypeString:(int)a0;
+ (id)streamSideString:(unsigned char)a0;
+ (id)streamTypeString:(unsigned char)a0;

- (id)init;
- (void)dealloc;
- (void).cxx_destruct;
- (struct quiclog_event { int x0; char x1[4]; unsigned long long x2; union { struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; unsigned long long x3; unsigned long long x4; char x5[32]; unsigned char x6[21]; unsigned char x7[21]; unsigned char x8[21]; char x9; char x10; char x11; unsigned char x12; struct quic_preferred_address { struct in_addr { unsigned int x0; } x0; unsigned short x1; struct in6_addr { union { unsigned char x0[16]; unsigned short x1[8]; unsigned int x2[4]; } x0; } x2; unsigned short x3; unsigned char x4[21]; unsigned char x5[16]; } x13; unsigned long long x14; unsigned long long x15; unsigned long long x16; unsigned long long x17; unsigned long long x18; unsigned long long x19; } x0; struct { int x0; char x1[4]; struct packet_header *x2; struct quic_frame_list { struct quic_frame *x0; struct quic_frame **x1; } x3; char x4; char x5[3]; union { int x0; unsigned char x1; } x6; } x1; struct { unsigned long long x0; unsigned char x1; unsigned char x2; unsigned char x3; char x4[1]; unsigned char x5; char x6[3]; } x2; struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; unsigned long long x3; unsigned long long x4; unsigned long long x5; unsigned long long x6; unsigned long long x7; unsigned long long x8; char x9; char x10[7]; } x3; struct { unsigned char x0; unsigned char x1; unsigned char x2; } x4; struct { unsigned long long x0; unsigned char x1; unsigned char x2; unsigned char x3; char x4[5]; } x5; } x3; struct { struct quiclog_event *x0; } x4; } *)createEvent:(int)a0;
- (id)addFrameList:(id)a0 frame_list:(struct quic_frame_list { struct quic_frame *x0; struct quic_frame **x1; } *)a1;
- (void)streamStateUpdated:(unsigned long long)a0 stream_type:(unsigned char)a1 old_state:(unsigned char)a2 new_state:(unsigned char)a3 stream_side:(unsigned char)a4;
- (id)addEventValues:(id)a0 event:(struct quiclog_event { int x0; char x1[4]; unsigned long long x2; union { struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; unsigned long long x3; unsigned long long x4; char x5[32]; unsigned char x6[21]; unsigned char x7[21]; unsigned char x8[21]; char x9; char x10; char x11; unsigned char x12; struct quic_preferred_address { struct in_addr { unsigned int x0; } x0; unsigned short x1; struct in6_addr { union { unsigned char x0[16]; unsigned short x1[8]; unsigned int x2[4]; } x0; } x2; unsigned short x3; unsigned char x4[21]; unsigned char x5[16]; } x13; unsigned long long x14; unsigned long long x15; unsigned long long x16; unsigned long long x17; unsigned long long x18; unsigned long long x19; } x0; struct { int x0; char x1[4]; struct packet_header *x2; struct quic_frame_list { struct quic_frame *x0; struct quic_frame **x1; } x3; char x4; char x5[3]; union { int x0; unsigned char x1; } x6; } x1; struct { unsigned long long x0; unsigned char x1; unsigned char x2; unsigned char x3; char x4[1]; unsigned char x5; char x6[3]; } x2; struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; unsigned long long x3; unsigned long long x4; unsigned long long x5; unsigned long long x6; unsigned long long x7; unsigned long long x8; char x9; char x10[7]; } x3; struct { unsigned char x0; unsigned char x1; unsigned char x2; } x4; struct { unsigned long long x0; unsigned char x1; unsigned char x2; unsigned char x3; char x4[5]; } x5; } x3; struct { struct quiclog_event *x0; } x4; } *)a1;
- (void)setEntryInTopLevelObject:(id)a0 value:(id)a1;
- (id)addMandatoryCharPointerToObject:(id)a0 key:(id)a1 value:(const char *)a2 function_name:(const char *)a3;
- (id)addMandatorySuperBoolToObject:(id)a0 key:(id)a1 value:(char)a2 function_name:(const char *)a3;
- (id)addMandatoryUint64ToObject:(id)a0 key:(id)a1 value:(unsigned long long)a2 function_name:(const char *)a3;
- (id)addOptionalCharPointerToObject:(id)a0 key:(id)a1 value:(const char *)a2;
- (id)addOptionalSuperBoolToObject:(id)a0 key:(id)a1 value:(char)a2;
- (id)addOptionalUint64ToObject:(id)a0 key:(id)a1 value:(unsigned long long)a2;
- (id)addPacketHeader:(id)a0 header:(struct packet_header { unsigned long long x0; unsigned long long x1; unsigned long long x2; char *x3; unsigned char x4; unsigned char x5; char x6[41]; char x7[41]; char x8[4]; } *)a1;
- (void)deallocEvent:(struct quiclog_event { int x0; char x1[4]; unsigned long long x2; union { struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; unsigned long long x3; unsigned long long x4; char x5[32]; unsigned char x6[21]; unsigned char x7[21]; unsigned char x8[21]; char x9; char x10; char x11; unsigned char x12; struct quic_preferred_address { struct in_addr { unsigned int x0; } x0; unsigned short x1; struct in6_addr { union { unsigned char x0[16]; unsigned short x1[8]; unsigned int x2[4]; } x0; } x2; unsigned short x3; unsigned char x4[21]; unsigned char x5[16]; } x13; unsigned long long x14; unsigned long long x15; unsigned long long x16; unsigned long long x17; unsigned long long x18; unsigned long long x19; } x0; struct { int x0; char x1[4]; struct packet_header *x2; struct quic_frame_list { struct quic_frame *x0; struct quic_frame **x1; } x3; char x4; char x5[3]; union { int x0; unsigned char x1; } x6; } x1; struct { unsigned long long x0; unsigned char x1; unsigned char x2; unsigned char x3; char x4[1]; unsigned char x5; char x6[3]; } x2; struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; unsigned long long x3; unsigned long long x4; unsigned long long x5; unsigned long long x6; unsigned long long x7; unsigned long long x8; char x9; char x10[7]; } x3; struct { unsigned char x0; unsigned char x1; unsigned char x2; } x4; struct { unsigned long long x0; unsigned char x1; unsigned char x2; unsigned char x3; char x4[5]; } x5; } x3; struct { struct quiclog_event *x0; } x4; } *)a0;
- (id)dictToJsonString:(id)a0;
- (void)disableTimestamps:(BOOL)a0;
- (id)dumpData:(id)a0;
- (id)jsonStringToDict:(id)a0;
- (void)logCongestionStateUpdated:(unsigned char)a0 new_state:(unsigned char)a1 trigger:(unsigned char)a2;
- (void)logStreamTypeSet:(unsigned long long)a0 owner:(unsigned char)a1 old_state:(unsigned char)a2 new_state:(unsigned char)a3;
- (void)metricsUpdated:(unsigned long long)a0 smoothed_rtt:(unsigned long long)a1 latest_rtt:(unsigned long long)a2 rtt_variance:(unsigned long long)a3 pto_count:(unsigned long long)a4 congestion_window:(unsigned long long)a5 bytes_in_flight:(unsigned long long)a6 ssthresh:(unsigned long long)a7 packets_in_flight:(unsigned long long)a8 in_recovery:(char)a9;
- (void)packetLost:(struct quic_packet { char *x0; char *x1; char *x2; char *x3; char *x4; unsigned char x5[21]; unsigned char x6[21]; unsigned char x7; unsigned char x8; unsigned char x9; unsigned char x10; unsigned char x11; unsigned char x12; unsigned short x13; unsigned short x14; unsigned short x15; union { unsigned short x0; unsigned short x1; } x16; union { char *x0; unsigned int *x1; } x17; int x18; unsigned int x19; unsigned long long x20; unsigned long long x21; unsigned long long x22; struct quic_packet_pool *x23; struct quic_path *x24; struct { struct quic_frame *x0; struct quic_frame **x1; } x25; struct { struct quic_packet *x0; struct quic_packet **x1; } x26; struct { struct quic_packet *x0; struct quic_packet **x1; } x27; struct { struct quic_packet *x0; struct quic_packet **x1; } x28; struct { struct quic_packet *x0; } x29; unsigned long long x30; unsigned char x31 : 1; unsigned char x32 : 1; unsigned char x33 : 1; unsigned char x34 : 1; unsigned char x35 : 1; unsigned char x36 : 1; unsigned char x37 : 1; unsigned char x38 : 1; unsigned char x39 : 1; unsigned char x40 : 1; unsigned char x41 : 1; unsigned char x42 : 1; unsigned char x43 : 1; unsigned char x44 : 1; unsigned char x45 : 1; unsigned int x46 : 17; unsigned char x47[4]; } *)a0 trigger:(unsigned char)a1;
- (void)packetReceived:(struct quic_packet { char *x0; char *x1; char *x2; char *x3; char *x4; unsigned char x5[21]; unsigned char x6[21]; unsigned char x7; unsigned char x8; unsigned char x9; unsigned char x10; unsigned char x11; unsigned char x12; unsigned short x13; unsigned short x14; unsigned short x15; union { unsigned short x0; unsigned short x1; } x16; union { char *x0; unsigned int *x1; } x17; int x18; unsigned int x19; unsigned long long x20; unsigned long long x21; unsigned long long x22; struct quic_packet_pool *x23; struct quic_path *x24; struct { struct quic_frame *x0; struct quic_frame **x1; } x25; struct { struct quic_packet *x0; struct quic_packet **x1; } x26; struct { struct quic_packet *x0; struct quic_packet **x1; } x27; struct { struct quic_packet *x0; struct quic_packet **x1; } x28; struct { struct quic_packet *x0; } x29; unsigned long long x30; unsigned char x31 : 1; unsigned char x32 : 1; unsigned char x33 : 1; unsigned char x34 : 1; unsigned char x35 : 1; unsigned char x36 : 1; unsigned char x37 : 1; unsigned char x38 : 1; unsigned char x39 : 1; unsigned char x40 : 1; unsigned char x41 : 1; unsigned char x42 : 1; unsigned char x43 : 1; unsigned char x44 : 1; unsigned char x45 : 1; unsigned int x46 : 17; unsigned char x47[4]; } *)a0 isCoalesced:(BOOL)a1;
- (void)packetSent:(struct quic_packet { char *x0; char *x1; char *x2; char *x3; char *x4; unsigned char x5[21]; unsigned char x6[21]; unsigned char x7; unsigned char x8; unsigned char x9; unsigned char x10; unsigned char x11; unsigned char x12; unsigned short x13; unsigned short x14; unsigned short x15; union { unsigned short x0; unsigned short x1; } x16; union { char *x0; unsigned int *x1; } x17; int x18; unsigned int x19; unsigned long long x20; unsigned long long x21; unsigned long long x22; struct quic_packet_pool *x23; struct quic_path *x24; struct { struct quic_frame *x0; struct quic_frame **x1; } x25; struct { struct quic_packet *x0; struct quic_packet **x1; } x26; struct { struct quic_packet *x0; struct quic_packet **x1; } x27; struct { struct quic_packet *x0; struct quic_packet **x1; } x28; struct { struct quic_packet *x0; } x29; unsigned long long x30; unsigned char x31 : 1; unsigned char x32 : 1; unsigned char x33 : 1; unsigned char x34 : 1; unsigned char x35 : 1; unsigned char x36 : 1; unsigned char x37 : 1; unsigned char x38 : 1; unsigned char x39 : 1; unsigned char x40 : 1; unsigned char x41 : 1; unsigned char x42 : 1; unsigned char x43 : 1; unsigned char x44 : 1; unsigned char x45 : 1; unsigned int x46 : 17; unsigned char x47[4]; } *)a0;
- (void)parametersSet:(unsigned char)a0 resumption_allowed:(char)a1 early_data_enabled:(char)a2 tls_cipher:(const char *)a3 original_dcid:(unsigned char[21] *)a4 initial_scid:(unsigned char[21] *)a5 retry_scid:(unsigned char[21] *)a6 disable_active_migration:(char)a7 max_idle_timeout:(unsigned long long)a8 max_udp_payload_size:(unsigned long long)a9 ack_delay_exponent:(unsigned long long)a10 max_ack_delay:(unsigned long long)a11 active_cid_limit:(unsigned long long)a12 initial_max_data:(unsigned long long)a13 initial_msd_bidi_remote:(unsigned long long)a14 initial_msd_bidi_local:(unsigned long long)a15 initial_msd_uni:(unsigned long long)a16 initial_ms_bidi:(unsigned long long)a17 initial_ms_uni:(unsigned long long)a18 preferred_address:(struct quic_preferred_address { struct in_addr { unsigned int x0; } x0; unsigned short x1; struct in6_addr { union { unsigned char x0[16]; unsigned short x1[8]; unsigned int x2[4]; } x0; } x2; unsigned short x3; unsigned char x4[21]; unsigned char x5[16]; } *)a19;
- (id)processCongestionStateUpdated:(struct quiclog_event { int x0; char x1[4]; unsigned long long x2; union { struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; unsigned long long x3; unsigned long long x4; char x5[32]; unsigned char x6[21]; unsigned char x7[21]; unsigned char x8[21]; char x9; char x10; char x11; unsigned char x12; struct quic_preferred_address { struct in_addr { unsigned int x0; } x0; unsigned short x1; struct in6_addr { union { unsigned char x0[16]; unsigned short x1[8]; unsigned int x2[4]; } x0; } x2; unsigned short x3; unsigned char x4[21]; unsigned char x5[16]; } x13; unsigned long long x14; unsigned long long x15; unsigned long long x16; unsigned long long x17; unsigned long long x18; unsigned long long x19; } x0; struct { int x0; char x1[4]; struct packet_header *x2; struct quic_frame_list { struct quic_frame *x0; struct quic_frame **x1; } x3; char x4; char x5[3]; union { int x0; unsigned char x1; } x6; } x1; struct { unsigned long long x0; unsigned char x1; unsigned char x2; unsigned char x3; char x4[1]; unsigned char x5; char x6[3]; } x2; struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; unsigned long long x3; unsigned long long x4; unsigned long long x5; unsigned long long x6; unsigned long long x7; unsigned long long x8; char x9; char x10[7]; } x3; struct { unsigned char x0; unsigned char x1; unsigned char x2; } x4; struct { unsigned long long x0; unsigned char x1; unsigned char x2; unsigned char x3; char x4[5]; } x5; } x3; struct { struct quiclog_event *x0; } x4; } *)a0;
- (id)processMetricsUpdated:(struct quiclog_event { int x0; char x1[4]; unsigned long long x2; union { struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; unsigned long long x3; unsigned long long x4; char x5[32]; unsigned char x6[21]; unsigned char x7[21]; unsigned char x8[21]; char x9; char x10; char x11; unsigned char x12; struct quic_preferred_address { struct in_addr { unsigned int x0; } x0; unsigned short x1; struct in6_addr { union { unsigned char x0[16]; unsigned short x1[8]; unsigned int x2[4]; } x0; } x2; unsigned short x3; unsigned char x4[21]; unsigned char x5[16]; } x13; unsigned long long x14; unsigned long long x15; unsigned long long x16; unsigned long long x17; unsigned long long x18; unsigned long long x19; } x0; struct { int x0; char x1[4]; struct packet_header *x2; struct quic_frame_list { struct quic_frame *x0; struct quic_frame **x1; } x3; char x4; char x5[3]; union { int x0; unsigned char x1; } x6; } x1; struct { unsigned long long x0; unsigned char x1; unsigned char x2; unsigned char x3; char x4[1]; unsigned char x5; char x6[3]; } x2; struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; unsigned long long x3; unsigned long long x4; unsigned long long x5; unsigned long long x6; unsigned long long x7; unsigned long long x8; char x9; char x10[7]; } x3; struct { unsigned char x0; unsigned char x1; unsigned char x2; } x4; struct { unsigned long long x0; unsigned char x1; unsigned char x2; unsigned char x3; char x4[5]; } x5; } x3; struct { struct quiclog_event *x0; } x4; } *)a0;
- (id)processPacketLost:(struct quiclog_event { int x0; char x1[4]; unsigned long long x2; union { struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; unsigned long long x3; unsigned long long x4; char x5[32]; unsigned char x6[21]; unsigned char x7[21]; unsigned char x8[21]; char x9; char x10; char x11; unsigned char x12; struct quic_preferred_address { struct in_addr { unsigned int x0; } x0; unsigned short x1; struct in6_addr { union { unsigned char x0[16]; unsigned short x1[8]; unsigned int x2[4]; } x0; } x2; unsigned short x3; unsigned char x4[21]; unsigned char x5[16]; } x13; unsigned long long x14; unsigned long long x15; unsigned long long x16; unsigned long long x17; unsigned long long x18; unsigned long long x19; } x0; struct { int x0; char x1[4]; struct packet_header *x2; struct quic_frame_list { struct quic_frame *x0; struct quic_frame **x1; } x3; char x4; char x5[3]; union { int x0; unsigned char x1; } x6; } x1; struct { unsigned long long x0; unsigned char x1; unsigned char x2; unsigned char x3; char x4[1]; unsigned char x5; char x6[3]; } x2; struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; unsigned long long x3; unsigned long long x4; unsigned long long x5; unsigned long long x6; unsigned long long x7; unsigned long long x8; char x9; char x10[7]; } x3; struct { unsigned char x0; unsigned char x1; unsigned char x2; } x4; struct { unsigned long long x0; unsigned char x1; unsigned char x2; unsigned char x3; char x4[5]; } x5; } x3; struct { struct quiclog_event *x0; } x4; } *)a0;
- (id)processPacketSentAndPacketRecieved:(struct quiclog_event { int x0; char x1[4]; unsigned long long x2; union { struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; unsigned long long x3; unsigned long long x4; char x5[32]; unsigned char x6[21]; unsigned char x7[21]; unsigned char x8[21]; char x9; char x10; char x11; unsigned char x12; struct quic_preferred_address { struct in_addr { unsigned int x0; } x0; unsigned short x1; struct in6_addr { union { unsigned char x0[16]; unsigned short x1[8]; unsigned int x2[4]; } x0; } x2; unsigned short x3; unsigned char x4[21]; unsigned char x5[16]; } x13; unsigned long long x14; unsigned long long x15; unsigned long long x16; unsigned long long x17; unsigned long long x18; unsigned long long x19; } x0; struct { int x0; char x1[4]; struct packet_header *x2; struct quic_frame_list { struct quic_frame *x0; struct quic_frame **x1; } x3; char x4; char x5[3]; union { int x0; unsigned char x1; } x6; } x1; struct { unsigned long long x0; unsigned char x1; unsigned char x2; unsigned char x3; char x4[1]; unsigned char x5; char x6[3]; } x2; struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; unsigned long long x3; unsigned long long x4; unsigned long long x5; unsigned long long x6; unsigned long long x7; unsigned long long x8; char x9; char x10[7]; } x3; struct { unsigned char x0; unsigned char x1; unsigned char x2; } x4; struct { unsigned long long x0; unsigned char x1; unsigned char x2; unsigned char x3; char x4[5]; } x5; } x3; struct { struct quiclog_event *x0; } x4; } *)a0;
- (id)processParametersSet:(struct quiclog_event { int x0; char x1[4]; unsigned long long x2; union { struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; unsigned long long x3; unsigned long long x4; char x5[32]; unsigned char x6[21]; unsigned char x7[21]; unsigned char x8[21]; char x9; char x10; char x11; unsigned char x12; struct quic_preferred_address { struct in_addr { unsigned int x0; } x0; unsigned short x1; struct in6_addr { union { unsigned char x0[16]; unsigned short x1[8]; unsigned int x2[4]; } x0; } x2; unsigned short x3; unsigned char x4[21]; unsigned char x5[16]; } x13; unsigned long long x14; unsigned long long x15; unsigned long long x16; unsigned long long x17; unsigned long long x18; unsigned long long x19; } x0; struct { int x0; char x1[4]; struct packet_header *x2; struct quic_frame_list { struct quic_frame *x0; struct quic_frame **x1; } x3; char x4; char x5[3]; union { int x0; unsigned char x1; } x6; } x1; struct { unsigned long long x0; unsigned char x1; unsigned char x2; unsigned char x3; char x4[1]; unsigned char x5; char x6[3]; } x2; struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; unsigned long long x3; unsigned long long x4; unsigned long long x5; unsigned long long x6; unsigned long long x7; unsigned long long x8; char x9; char x10[7]; } x3; struct { unsigned char x0; unsigned char x1; unsigned char x2; } x4; struct { unsigned long long x0; unsigned char x1; unsigned char x2; unsigned char x3; char x4[5]; } x5; } x3; struct { struct quiclog_event *x0; } x4; } *)a0;
- (id)processStreamStateUpdated:(struct quiclog_event { int x0; char x1[4]; unsigned long long x2; union { struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; unsigned long long x3; unsigned long long x4; char x5[32]; unsigned char x6[21]; unsigned char x7[21]; unsigned char x8[21]; char x9; char x10; char x11; unsigned char x12; struct quic_preferred_address { struct in_addr { unsigned int x0; } x0; unsigned short x1; struct in6_addr { union { unsigned char x0[16]; unsigned short x1[8]; unsigned int x2[4]; } x0; } x2; unsigned short x3; unsigned char x4[21]; unsigned char x5[16]; } x13; unsigned long long x14; unsigned long long x15; unsigned long long x16; unsigned long long x17; unsigned long long x18; unsigned long long x19; } x0; struct { int x0; char x1[4]; struct packet_header *x2; struct quic_frame_list { struct quic_frame *x0; struct quic_frame **x1; } x3; char x4; char x5[3]; union { int x0; unsigned char x1; } x6; } x1; struct { unsigned long long x0; unsigned char x1; unsigned char x2; unsigned char x3; char x4[1]; unsigned char x5; char x6[3]; } x2; struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; unsigned long long x3; unsigned long long x4; unsigned long long x5; unsigned long long x6; unsigned long long x7; unsigned long long x8; char x9; char x10[7]; } x3; struct { unsigned char x0; unsigned char x1; unsigned char x2; } x4; struct { unsigned long long x0; unsigned char x1; unsigned char x2; unsigned char x3; char x4[5]; } x5; } x3; struct { struct quiclog_event *x0; } x4; } *)a0;
- (id)processStreamTypeSet:(struct quiclog_event { int x0; char x1[4]; unsigned long long x2; union { struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; unsigned long long x3; unsigned long long x4; char x5[32]; unsigned char x6[21]; unsigned char x7[21]; unsigned char x8[21]; char x9; char x10; char x11; unsigned char x12; struct quic_preferred_address { struct in_addr { unsigned int x0; } x0; unsigned short x1; struct in6_addr { union { unsigned char x0[16]; unsigned short x1[8]; unsigned int x2[4]; } x0; } x2; unsigned short x3; unsigned char x4[21]; unsigned char x5[16]; } x13; unsigned long long x14; unsigned long long x15; unsigned long long x16; unsigned long long x17; unsigned long long x18; unsigned long long x19; } x0; struct { int x0; char x1[4]; struct packet_header *x2; struct quic_frame_list { struct quic_frame *x0; struct quic_frame **x1; } x3; char x4; char x5[3]; union { int x0; unsigned char x1; } x6; } x1; struct { unsigned long long x0; unsigned char x1; unsigned char x2; unsigned char x3; char x4[1]; unsigned char x5; char x6[3]; } x2; struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; unsigned long long x3; unsigned long long x4; unsigned long long x5; unsigned long long x6; unsigned long long x7; unsigned long long x8; char x9; char x10[7]; } x3; struct { unsigned char x0; unsigned char x1; unsigned char x2; } x4; struct { unsigned long long x0; unsigned char x1; unsigned char x2; unsigned char x3; char x4[5]; } x5; } x3; struct { struct quiclog_event *x0; } x4; } *)a0;

@end
