@class RTMapServiceManager, RTLocationManager, RTDaemonClientRegistrarScenarioTrigger, RTMetricManager, RTAccountManager, RTLocationStore, RTDeviceLocationPredictor, RTScenarioTriggerManager, RTEventModelProvider, RTVehicleLocationProvider, NSXPCConnection, RTAuthorizationManager, RTLearnedLocationManager, RTDiagnostics, RTPurgeManager, RTTimerManager, RTDefaultsManager, RTVehicleStore, RTLearnedLocationStore, RTVisitManager, RTContactsManager, RTWiFiManager, RTHealthKitManager, RTMotionActivityManager, RTElevationManager, RTEventAgentManager, RTAssetManager, NSMutableDictionary, RTDaemonClientRegistrarVehicleEvent, RTTripSegmentManager, NSString, RTPlaceInferenceManager, NSObject, RTHintManager, RTEntitlementProvider, RTFingerprintManager, RTPeopleDiscoveryProvider;
@protocol OS_dispatch_queue, RTClientListenerProtocol;

@interface RTDaemonClient : NSObject <RTDaemonClientRegistrarVehicleEventProtocol, RTDaemonClientRegistrarScenarioTriggerProtocol, RTDaemonProtocol, NSXPCConnectionDelegate>

@property BOOL enabled;
@property (nonatomic) BOOL supported;
@property (nonatomic) BOOL monitorVisits;
@property (nonatomic) BOOL leechVisits;
@property (nonatomic) BOOL leechLowConfidenceVisits;
@property (retain, nonatomic) NSMutableDictionary *restorationData;
@property (retain, nonatomic) RTEntitlementProvider *entitlementProvider;
@property (retain, nonatomic) NSMutableDictionary *vendedClassesStoreManagerDict;
@property (retain, nonatomic) RTDaemonClientRegistrarVehicleEvent *vehicleEventRegistrar;
@property (retain, nonatomic) RTDaemonClientRegistrarScenarioTrigger *scenarioTriggerRegistrar;
@property (retain, nonatomic) RTAccountManager *accountManager;
@property (retain, nonatomic) RTAssetManager *assetManager;
@property (retain, nonatomic) RTAuthorizationManager *authorizationManager;
@property (retain, nonatomic) RTContactsManager *contactsManager;
@property (retain, nonatomic) RTDefaultsManager *defaultsManager;
@property (retain, nonatomic) RTDeviceLocationPredictor *deviceLocationPredictor;
@property (retain, nonatomic) RTDiagnostics *diagnostics;
@property (retain, nonatomic) RTElevationManager *elevationManager;
@property (retain, nonatomic) RTEventAgentManager *eventAgentManager;
@property (retain, nonatomic) RTEventModelProvider *eventModelProvider;
@property (retain, nonatomic) RTFingerprintManager *fingerprintManager;
@property (retain, nonatomic) RTHealthKitManager *healthKitManager;
@property (retain, nonatomic) RTHintManager *hintManager;
@property (retain, nonatomic) RTLearnedLocationManager *learnedLocationManager;
@property (retain, nonatomic) RTLearnedLocationStore *learnedLocationStore;
@property (retain, nonatomic) RTLocationManager *locationManager;
@property (retain, nonatomic) RTLocationStore *locationStore;
@property (retain, nonatomic) RTMapServiceManager *mapServiceManager;
@property (retain, nonatomic) RTMetricManager *metricManager;
@property (retain, nonatomic) RTMotionActivityManager *motionActivityManager;
@property (retain, nonatomic) RTPeopleDiscoveryProvider *peopleDiscoveryProvider;
@property (retain, nonatomic) RTPlaceInferenceManager *placeInferenceManager;
@property (retain, nonatomic) RTPurgeManager *purgeManager;
@property (retain, nonatomic) RTScenarioTriggerManager *scenarioTriggerManager;
@property (retain, nonatomic) RTTimerManager *timerManager;
@property (retain, nonatomic) RTVehicleLocationProvider *vehicleLocationProvider;
@property (retain, nonatomic) RTVisitManager *visitManager;
@property (retain, nonatomic) RTTripSegmentManager *tripSegmentManager;
@property (retain, nonatomic) RTVehicleStore *vehicleStore;
@property (retain, nonatomic) RTWiFiManager *wifiManager;
@property (retain, nonatomic) NSObject<OS_dispatch_queue> *queue;
@property (copy, nonatomic) NSString *executablePath;
@property (copy, nonatomic) NSString *executableName;
@property (nonatomic) int processIdentifier;
@property (copy, nonatomic) NSString *signingIdentifier;
@property (copy, nonatomic) NSString *bundleIdentifier;
@property (retain, nonatomic) NSXPCConnection *xpcConnection;
@property (copy, nonatomic) NSString *restorationIdentifier;
@property (weak, nonatomic) id<RTClientListenerProtocol> clientManagerDelegate;
@property (nonatomic) BOOL targetUserSession;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)filterVisits:(id)a0 executable:(id)a1;

- (void)onAuthorizationNotification:(id)a0;
- (void)addLocationOfInterestOfType:(long long)a0 mapItemStorage:(id)a1 customLabel:(id)a2 reply:(id /* block */)a3;
- (void)fetchStoredLocationsWithContext:(id)a0 reply:(id /* block */)a1;
- (void)shutdown;
- (void)fetchLocationsOfInterestWithinDistance:(double)a0 ofLocation:(id)a1 reply:(id /* block */)a2;
- (id)init;
- (void)userInteractionWithPredictedLocationOfInterest:(id)a0 interaction:(unsigned long long)a1 feedback:(id)a2 geoMapItem:(id)a3 reply:(id /* block */)a4;
- (void)fetchVehiclesWithOptions:(id)a0 reply:(id /* block */)a1;
- (void)fetchEnumerableObjectsWithOptions:(id)a0 offset:(id)a1 reply:(id /* block */)a2;
- (void)fetchLocationsOfInterestVisitedBetweenStartDate:(id)a0 endDate:(id)a1 reply:(id /* block */)a2;
- (void)clearRoutineWithReply:(id /* block */)a0;
- (void)updateLocationOfInterestWithIdentifier:(id)a0 mapItemStorage:(id)a1 reply:(id /* block */)a2;
- (void)updateLocationOfInterestWithIdentifier:(id)a0 type:(long long)a1 customLabel:(id)a2 reply:(id /* block */)a3;
- (void)connection:(id)a0 handleInvocation:(id)a1 isReply:(BOOL)a2;
- (void)_onVisitManagerNotification:(id)a0;
- (void)removeLocationOfInterestWithIdentifier:(id)a0 reply:(id /* block */)a1;
- (void)fetchProximityHistoryFromEventIDs:(id)a0 completionHandler:(id /* block */)a1;
- (void)updateLocationOfInterestWithIdentifier:(id)a0 type:(long long)a1 reply:(id /* block */)a2;
- (void)fetchLookbackWindowStarDateWithLocation:(id)a0 reply:(id /* block */)a1;
- (void)extendLifetimeOfVisitsWithIdentifiers:(id)a0 reply:(id /* block */)a1;
- (void)removeVisitWithIdentifier:(id)a0 reply:(id /* block */)a1;
- (void)updateVehicleEventWithIdentifier:(id)a0 geoMapItem:(id)a1 reply:(id /* block */)a2;
- (void)fetchPeopleDensityHistoryFromStartDate:(id)a0 endDate:(id)a1 completionHandler:(id /* block */)a2;
- (void)fetchEstimatedLocationAtDate:(id)a0 options:(id)a1 reply:(id /* block */)a2;
- (void)fetchRoutineEnabledWithReply:(id /* block */)a0;
- (void)deleteTripSegmentWithUUID:(id)a0 reply:(id /* block */)a1;
- (void)setRoutineEnabled:(BOOL)a0 reply:(id /* block */)a1;
- (void)addElevations:(id)a0 handler:(id /* block */)a1;
- (void)setHintForRegionState:(long long)a0 significantRegion:(id)a1 reply:(id /* block */)a2;
- (void)vehicleEventRegistrar:(id)a0 didReceiveVehicleEvents:(id)a1 error:(id)a2;
- (void)fetchLastVehicleEventsWithReply:(id /* block */)a0;
- (void)fetchLocationOfInterestWithIdentifier:(id)a0 reply:(id /* block */)a1;
- (void)fetchRoutineModeFromLocation:(id)a0 reply:(id /* block */)a1;
- (void)fetchLocationOfInterestForRegion:(id)a0 reply:(id /* block */)a1;
- (void)fetchPlaceInferencesWithOptions:(id)a0 reply:(id /* block */)a1;
- (void)updateVehicleEventWithIdentifier:(id)a0 photo:(id)a1 reply:(id /* block */)a2;
- (id)_clientIdentifier;
- (void)fetchMonitoredScenarioTriggerTypesWithReply:(id /* block */)a0;
- (void)fetchLocationsCountForTripSegmentWithOptions:(id)a0 reply:(id /* block */)a1;
- (void)launchClient;
- (void)startLeechingLowConfidenceVisitsWithReply:(id /* block */)a0;
- (void)stopMonitoringScenarioTriggerOfType:(unsigned long long)a0 reply:(id /* block */)a1;
- (void)fetchStoredVisitsWithOptions:(id)a0 reply:(id /* block */)a1;
- (void)fetchElevationsWithOptions:(id)a0 reply:(id /* block */)a1;
- (void)fetchDedupedLocationOfInterestIdentifiersWithIdentifier:(id)a0 reply:(id /* block */)a1;
- (void)fetchLocationOfInterestAtLocation:(id)a0 reply:(id /* block */)a1;
- (BOOL)hasReasonToOutliveClientConnection;
- (void).cxx_destruct;
- (void)fetchProximityHistoryFromStartDate:(id)a0 endDate:(id)a1 completionHandler:(id /* block */)a2;
- (void)stopLeechingVisitsWithReply:(id /* block */)a0;
- (void)fetchCloudSyncAuthorizationStateWithReply:(id /* block */)a0;
- (void)engageInVehicleEventWithIdentifier:(id)a0 reply:(id /* block */)a1;
- (void)fetchNextPredictedLocationsOfInterestFromLocation:(id)a0 startDate:(id)a1 timeInterval:(double)a2 reply:(id /* block */)a3;
- (void)fetchContactScoresFromContactIDs:(id)a0 completionHandler:(id /* block */)a1;
- (void)performBluePOIQueryLookingBack:(double)a0 lookingAhead:(double)a1 reply:(id /* block */)a2;
- (void)startMonitoringScenarioTriggerOfType:(unsigned long long)a0 reply:(id /* block */)a1;
- (void)_fetchRealtimeVisitsWithDateInterval:(id)a0 options:(id)a1 handler:(id /* block */)a2;
- (void)scenarioTriggerRegistrar:(id)a0 didReceiveScenarioTriggers:(id)a1 error:(id)a2;
- (void)fetchCurrentPredictedLocationsOfInterestLookingBack:(double)a0 lookingAhead:(double)a1 reply:(id /* block */)a2;
- (void)updateVehicleEventWithIdentifier:(id)a0 location:(id)a1 reply:(id /* block */)a2;
- (void)updateCloudSyncProvisionedForAccount:(BOOL)a0 reply:(id /* block */)a1;
- (void)fetchLocationsForTripSegmentWithOptions:(id)a0 reply:(id /* block */)a1;
- (void)_fetchHindsightVisitsWithDateInterval:(id)a0 ascending:(BOOL)a1 handler:(id /* block */)a2;
- (void)fetchTransitionsBetweenStartDate:(id)a0 endDate:(id)a1 reply:(id /* block */)a2;
- (void)startLeechingVisitsWithReply:(id /* block */)a0;
- (void)fetchFormattedPostalAddressesFromMeCard:(id /* block */)a0;
- (void)fetchPredictedLocationsOfInterestOnDate:(id)a0 reply:(id /* block */)a1;
- (void)fetchPathToDiagnosticFilesWithOptions:(id)a0 reply:(id /* block */)a1;
- (void)fetchLocationsOfInterestAssociatedToIdentifier:(id)a0 reply:(id /* block */)a1;
- (void)fetchPredictedExitDatesFromLocation:(id)a0 onDate:(id)a1 reply:(id /* block */)a2;
- (void)fetchFamiliarityIndexResultsWithOptions:(id)a0 reply:(id /* block */)a1;
- (void)fetchPredictedLocationsOfInterestAssociatedToTitle:(id)a0 location:(id)a1 calendarIdentifier:(id)a2 reply:(id /* block */)a3;
- (void)fetchPredictedLocationsOfInterestBetweenStartDate:(id)a0 endDate:(id)a1 reply:(id /* block */)a2;
- (id)initWithQueue:(id)a0 restorationData:(id)a1 accountManager:(id)a2 assetManager:(id)a3 authorizationManager:(id)a4 contactsManager:(id)a5 defaultsManager:(id)a6 deviceLocationPredictor:(id)a7 diagnostics:(id)a8 elevationManager:(id)a9 eventAgentManager:(id)a10 eventModelProvider:(id)a11 fingerprintManager:(id)a12 healthKitManager:(id)a13 hintManager:(id)a14 learnedLocationManager:(id)a15 learnedLocationStore:(id)a16 locationManager:(id)a17 locationStore:(id)a18 mapServiceManager:(id)a19 metricManager:(id)a20 motionActivityManager:(id)a21 peopleDiscoveryProvider:(id)a22 placeInferenceManager:(id)a23 purgeManager:(id)a24 scenarioTriggerManager:(id)a25 timerManager:(id)a26 tripSegmentManager:(id)a27 vehicleLocationProvider:(id)a28 vehicleStore:(id)a29 visitManager:(id)a30 wifiManager:(id)a31;
- (void)stopMonitoringVehicleEventsWithReply:(id /* block */)a0;
- (void)updateLocationOfInterestWithIdentifier:(id)a0 type:(long long)a1 mapItemStorage:(id)a2 customLabel:(id)a3 reply:(id /* block */)a4;
- (void)restore;
- (void)fetchAutomaticVehicleEventDetectionSupportedWithReply:(id /* block */)a0;
- (void)stopMonitoringVisitsWithReply:(id /* block */)a0;
- (void)startMonitoringVisitsWithReply:(id /* block */)a0;
- (void)fetchLocationsOfInterestOfType:(long long)a0 reply:(id /* block */)a1;
- (void)fetchTripSegmentMetadataWithOptions:(id)a0 reply:(id /* block */)a1;
- (void)fetchPeopleCountEventsHistory:(id)a0 completionHandler:(id /* block */)a1;
- (void)clearAllVehicleEventsWithReply:(id /* block */)a0;
- (void)fetchAllLocationsOfInterestForSettingsWithReply:(id /* block */)a0;
- (void)updateVehicleEventWithIdentifier:(id)a0 notes:(id)a1 reply:(id /* block */)a2;
- (void)_startMonitoringVehicleEvents;
- (void)updateLocationOfInterestWithIdentifier:(id)a0 customLabel:(id)a1 reply:(id /* block */)a2;
- (void)onVisitManagerNotification:(id)a0;
- (void)vehicleEventAtLocation:(id)a0 notes:(id)a1 reply:(id /* block */)a2;
- (void)fetchTripSegmentsWithOptions:(id)a0 reply:(id /* block */)a1;
- (void)startMonitoringVehicleEventsWithReply:(id /* block */)a0;
- (void)processHindsightVisitsWithReply:(id /* block */)a0;
- (void)stopLeechingLowConfidenceVisitsWithReply:(id /* block */)a0;

@end
