@class RTDistanceCalculator, NSMutableDictionary, NSArray, RTLearnedLocationStore, NSDate, RTLocationManager, RTMotionActivityManager;

@interface RTLocationAwarenessMetricManager : NSObject

@property (readonly, nonatomic) RTLocationManager *locationManager;
@property (readonly, nonatomic) RTMotionActivityManager *motionManager;
@property (readonly, nonatomic) RTLearnedLocationStore *learnedLocationStore;
@property (retain, nonatomic) NSDate *startDate;
@property (retain, nonatomic) NSDate *endDate;
@property (nonatomic) double boutMetricDistanceToSensitiveLocation;
@property (nonatomic) unsigned long long boutMetricType;
@property (nonatomic) double boutMetricDuration;
@property (nonatomic) double boutMetricNumWifiLocationsInBout;
@property (nonatomic) double boutMetricNumGPSLocationsInBout;
@property (nonatomic) double boutMetricNumOtherLocationsInBout;
@property (nonatomic) double boutMetricNumAdditionalFixesPerHourRequired1mDutyCycle;
@property (nonatomic) double boutMetricNumAdditionalFixesPerHourRequired2mDutyCycle;
@property (nonatomic) double boutMetricNumAdditionalFixesPerHourRequired5mDutyCycle;
@property (nonatomic) double boutMetricNumAdditionalFixesPerHourRequired10mDutyCycle;
@property (nonatomic) double boutMetricNumAdditionalFixesPerHourRequired15mDutyCycle;
@property (nonatomic) unsigned long long stateVariableCurrMotionActivityType;
@property (retain, nonatomic) NSDate *stateVariableCurrMotionStart;
@property (nonatomic) int stateVariableCurrSignalEnvironmentType;
@property (retain, nonatomic) NSDate *stateVariablePrevLocationTimestamp;
@property (retain, nonatomic) NSDate *stateVariablePrevWifiLocationTimestamp;
@property (nonatomic) double stateVariableMostRecentDistanceToSensitiveLocation;
@property (retain, nonatomic) NSDate *stateVariableLastSensitiveLocationCheckTimestamp;
@property (retain, nonatomic) NSDate *stateVariableLastSettledStateChangeTimestamp;
@property (retain, nonatomic) NSDate *stateVariableLastWifiStateChangeTimestamp;
@property (retain, nonatomic) NSMutableDictionary *boutStateMotionDwell;
@property (retain, nonatomic) NSMutableDictionary *boutStateMotionLongestDwell;
@property (retain, nonatomic) NSMutableDictionary *boutStateMotionTypeNumBouts;
@property (retain, nonatomic) NSMutableDictionary *boutStateSignalEnvironmentDwell;
@property (nonatomic) unsigned long long boutStateMotion;
@property (nonatomic) unsigned long long boutStateWifi;
@property (nonatomic) unsigned long long boutStateTypeForLastCompleteBout;
@property (retain, nonatomic) NSDate *boutStateCurrBoutStart;
@property (retain, nonatomic) NSDate *boutStateCurrBoutEnd;
@property (nonatomic) double boutBufferNumAdditionalFixesPerHourRequired1mDutyCycle;
@property (nonatomic) double boutBufferNumAdditionalFixesPerHourRequired2mDutyCycle;
@property (nonatomic) double boutBufferNumAdditionalFixesPerHourRequired5mDutyCycle;
@property (nonatomic) double boutBufferNumAdditionalFixesPerHourRequired10mDutyCycle;
@property (nonatomic) double boutBufferNumAdditionalFixesPerHourRequired15mDutyCycle;
@property (nonatomic) double boutBufferNumGPSLocationsInBout;
@property (nonatomic) double boutBufferNumOtherLocationsInBout;
@property (nonatomic) double boutBufferDistanceToSensitiveLocation;
@property (nonatomic) double boutBufferMotionEdgeDwell;
@property (nonatomic) unsigned long long boutBufferMotionEdgeType;
@property (retain, nonatomic) NSMutableDictionary *boutBufferMotionDwell;
@property (retain, nonatomic) NSMutableDictionary *boutBufferMotionLongestDwell;
@property (retain, nonatomic) NSMutableDictionary *boutBufferMotionBoutCounts;
@property (retain, nonatomic) NSMutableDictionary *boutBufferSignalEnvironmentDwell;
@property (retain, nonatomic) NSMutableDictionary *dailyStateSignalEnvironmentDwell;
@property (retain, nonatomic) NSMutableDictionary *dailyStateMotionDwell;
@property (retain, nonatomic) NSMutableDictionary *dailyStateBoutCounts;
@property (retain, nonatomic) NSMutableDictionary *dailyStateBoutDwell;
@property (retain, nonatomic) NSMutableDictionary *dailyStateBoutLongestDwell;
@property (retain, nonatomic) NSArray *sensitiveLocations;
@property (retain, nonatomic) RTDistanceCalculator *distanceCalculator;

- (void)submitMetrics;
- (void).cxx_destruct;
- (void)setup;
- (void)resetBuffer;
- (void)processLastBout;
- (void)addDwellForMotionType:(unsigned long long)a0 startDate:(id)a1 endDate:(id)a2 motionDwellMetrics:(id)a3 longestDwell:(id)a4 boutCounts:(id)a5;
- (void)addDwellForSignalEnvironmentType:(int)a0 startDate:(id)a1 endDate:(id)a2 sigEnvMetrics:(id)a3;
- (id)collectBoutMetrics;
- (id)collectDailyMetrics;
- (id)createBoutDictionary;
- (id)createMotionDictionary;
- (id)createSignalEnvironmentDictionary;
- (double)distanceToNearestSensitiveLocation:(id)a0;
- (void)flushBufferToCurrBoutMetrics;
- (id)initWithLocationManager:(id)a0 motionManager:(id)a1 learnedLocationStore:(id)a2 startDate:(id)a3 endDate:(id)a4;
- (id)locationsAndMotionsForDateInterval:(id)a0;
- (void)monitorStateChange:(id)a0;
- (void)processLastDailyMetrics;
- (void)processMetrics;
- (void)resetBoutMetrics;
- (id)sensitiveLocationsOfInterestWithError:(id *)a0;
- (id)sortLocationsAndMotions:(id)a0;
- (void)submitBoutMetricsToCoreAnalytics;
- (void)submitDailyMetricsToCoreAnalytics;
- (void)updateBoutMetricsForLocation:(id)a0;
- (void)updateBoutMetricsForMotion:(id)a0;
- (void)updateBoutMetricsStateChangeEdgeDwell;
- (void)updateDailyMetrics:(id)a0;
- (void)updateStateVariables:(id)a0;

@end
