@class NSMutableDictionary, RTPersistenceMirroringRequest, RTInvocationDispatcher, RTPersistenceExpirationEnforcer, NSMutableArray, RTPlatform, RTPersistenceCloudDeletionEnforcer, RTTimerManager, NSString, RTDefaultsManager, RTPersistenceManager, RTReachabilityManager, RTXPCActivityManager, RTAccountManager;
@protocol RTPersistenceMirroringMetricsDelegate;

@interface RTPersistenceMirroringManager : RTService <RTPersistenceMirroringMetricsDelegate, RTPersistenceMirroringRequestDelegate, RTPersistenceMirroringDelegate, RTPurgable, RTDiagnosticProvider> {
    RTDefaultsManager *_defaultsManager;
    RTTimerManager *_timerManager;
    RTAccountManager *_accountManager;
    RTReachabilityManager *_reachabilityManager;
    long long _cloudSyncAuthorizationState;
    unsigned long long _currentReachability;
    BOOL _syncDisabledForPerProcessMemoryLimit;
}

@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;
@property (weak) id<RTPersistenceMirroringMetricsDelegate> metricsDelegate;
@property (retain, nonatomic) RTPersistenceManager *persistenceManager;
@property (retain, nonatomic) NSMutableDictionary *mirroringPolicies;
@property (retain, nonatomic) NSMutableDictionary *retryTimers;
@property (retain, nonatomic) NSMutableArray *pendingMirroringRequests;
@property (retain, nonatomic) RTPersistenceMirroringRequest *activeMirroringRequest;
@property (retain, nonatomic) RTXPCActivityManager *xpcActivityManager;
@property (retain, nonatomic) RTPlatform *platform;
@property (retain, nonatomic) RTPersistenceCloudDeletionEnforcer *persistenceCloudDeletionEnforcer;
@property (retain, nonatomic) RTPersistenceExpirationEnforcer *persistenceExpirationEnforcer;
@property (retain, nonatomic) RTInvocationDispatcher *dispatcher;
@property (nonatomic) BOOL exportingAvailable;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (long long)periodicPurgePolicy;

- (void)performPurgeOfType:(long long)a0 referenceDate:(id)a1 completion:(id /* block */)a2;
- (void)onReachabilityChange:(id)a0;
- (void)mirroringManager:(id)a0 mirroringRequestDidSucceed:(id)a1;
- (id)transactionHistoryCountRequestWithManagedObjectContext:(id)a0 currentExporterToken:(id)a1;
- (BOOL)_evaluatePersistentHistoryLengthWithManagedObjectContext:(id)a0 shouldResetSync:(BOOL *)a1 error:(id *)a2;
- (id)init;
- (void)dealloc;
- (void)_scheduleRetryAttemptForRequest:(id)a0 referenceDate:(id)a1 handler:(id /* block */)a2;
- (BOOL)_shouldResetForChangeCountForManagedObjectContext:(id)a0 currentExporterToken:(id)a1 changeRequestError:(id *)a2;
- (id)optionsForQualityOfService:(long long)a0;
- (void)_shutdownWithHandler:(id /* block */)a0;
- (void)mirroringRequestDidSucceed:(id)a0;
- (void)setMirroringAttemptMapValue:(BOOL)a0 buildVersion:(id)a1;
- (id)currentExporterTokenWithManagedObjectContext:(id)a0 error:(id *)a1;
- (void)performMirroringRequestWithType:(long long)a0 affectedStore:(id)a1 qualityOfService:(long long)a2 managedObjectContext:(id)a3 handler:(id /* block */)a4;
- (void)mirroringManager:(id)a0 mirroringRequest:(id)a1 didFailWithError:(id)a2;
- (void)_onCloudSyncAuthorizationChange:(id)a0;
- (void)sendDiagnosticsToURL:(id)a0 options:(id)a1 handler:(id /* block */)a2;
- (BOOL)mirroringRequest:(id)a0 didFailWithError:(id)a1;
- (void)_performExportWithHandler:(id /* block */)a0;
- (BOOL)_authorizedToMirror;
- (void)_enqueueMirroringRequest:(id)a0 context:(id)a1;
- (void)performPeriodicSyncWithHandler:(id /* block */)a0;
- (void)_finalizeMirroringRequest:(id)a0;
- (BOOL)_fetchZoneChangesForDatabase:(id)a0 outputURL:(id)a1 error:(id *)a2;
- (void)_onMirroringDelegateInitialization:(id)a0;
- (void)registerForXPCActivities;
- (id)changeCountForManagedObjectContext:(id)a0 currentExporterToken:(id)a1 changeRequestError:(id *)a2;
- (void)onMirroringDelegateInitialization:(id)a0;
- (id)initWithAccountManager:(id)a0 defaultsManager:(id)a1 mirroringPolicies:(id)a2 persistenceCloudDeletionEnforcer:(id)a3 persistenceExpirationEnforcer:(id)a4 persistenceManager:(id)a5 platform:(id)a6 reachabilityManager:(id)a7 timerManager:(id)a8 xpcActivityManager:(id)a9;
- (id)persistenceOperationMetricWithMirroringRequest:(id)a0 lastMirroringTransactionDate:(id)a1 recordsChanged:(unsigned long long)a2 error:(id)a3;
- (void)_updateMirroringDelegateState;
- (void)_persistenceAvailabilityDidChange:(id)a0;
- (id)transactionHistoryRequestWithManagedObjectContext:(id)a0 currentExporterToken:(id)a1;
- (BOOL)_transactionHistorySizeError:(id *)a0;
- (void)persistenceAvailabilityDidChange:(id)a0;
- (BOOL)_dataAvailableToMirror;
- (void)_updateExportingAvailability:(unsigned long long)a0;
- (void)unregisterForXPCActivities;
- (void)_performMirroringRequestWithType:(long long)a0 affectedStore:(id)a1 qualityOfService:(long long)a2 managedObjectContext:(id)a3 handler:(id /* block */)a4;
- (BOOL)_generateDiagnosticFilesAtURL:(id)a0 error:(id *)a1;
- (BOOL)_fetchDatabaseChangesForDatabase:(id)a0 outputURL:(id)a1 error:(id *)a2;
- (void)performExportWithHandler:(id /* block */)a0;
- (void)_dequeueNextMirroringRequest;
- (void)mirroringManager:(id)a0 exceededHistoryType:(unsigned long long)a1 count:(unsigned long long)a2 limit:(unsigned long long)a3;
- (void)_prepareRequestForRetryAttempt:(id)a0 retryInterval:(double)a1;
- (void).cxx_destruct;
- (void)collectMetricsFromMirroringRequest:(id)a0 error:(id)a1;
- (void)_onReachabilityChange:(id)a0;
- (void)mirroringRequestDidBegin:(id)a0;
- (void)fetchDiagnosticLogsWithHandler:(id /* block */)a0;
- (BOOL)disableMirroringForPerProcessMemoryLimitViolation:(id)a0 platform:(id)a1;
- (void)onCloudSyncAuthorizationChange:(id)a0;
- (void)performMirroringRequestWithType:(long long)a0 affectedStore:(id)a1 qualityOfService:(long long)a2 handler:(id /* block */)a3;
- (BOOL)_calculateStoreShouldResetFromChangeHistoryCount:(unsigned long long)a0;
- (BOOL)_calculateStoreShouldResetFromTransactionHistory:(id)a0;
- (long long)_mirroringDelegateState;
- (id)transactionHistoryFetchRequestWithManagedObjectContext:(id)a0 currentExporterToken:(id)a1;
- (void)_startMirroringRequest:(id)a0 context:(id)a1;
- (BOOL)exportMirroringIsAvailableWithExpirationEnforcer:(id)a0 expirationDate:(id)a1 context:(id)a2 error:(id *)a3;
- (id)initWithAccountManager:(id)a0 defaultsManager:(id)a1 persistenceManager:(id)a2 platform:(id)a3 reachabilityManager:(id)a4 xpcActivityManager:(id)a5;
- (void)_performImportWithHandler:(id /* block */)a0;

@end
