@class SMSessionReceiptZone, RTDefaultsManager, RTContactsManager, RTBatteryManager, NSHashTable, RTWatchWristStateManager, RTNetworkOfInterestManager, NSMutableArray, RTAuthorizationManager, SMSessionMonitor, SMInitiatorSessionInitilizationRequest, RTXPCActivityManager, SMMessagingService, SMSuggestionsManager, SMSessionStore, SMSessionMetricManager, RTPlatform, RTInvocationDispatcher, SMActiveSessionZone, RTLocationManager, RTLearnedLocationManager, SMWatchdog, NSString, RTStarkManager, RTMotionActivityManager, SMCarouselSessionManager, RTDataProtectionManager, RTLocationAwarenessManager, RTVehicleLocationProvider, SMSessionManager, SMSafetyCacheStore;

@interface SMInitiatorService : RTService <SMInitiatorCacheManagerDelegateProtocol, RTPurgable, SMInitiatorCacheProtocol, SMInitiatorProtocol, SMInitiatorSessionConfigurationProtocol, SMSessionManagerObserverProtocol, SMUserNotificationProtocol>

@property (retain, nonatomic) NSHashTable *observers;
@property (nonatomic) BOOL fetchAllZonesRetried;
@property (nonatomic) BOOL frequentSingleShotFetchAllZonesInProgress;
@property (nonatomic) BOOL fetchAllZonesFromContainerInProgress;
@property (retain, nonatomic) RTContactsManager *contactsManager;
@property (retain, nonatomic) RTDefaultsManager *defaultsManager;
@property (retain, nonatomic) RTLocationAwarenessManager *locationAwarenessManager;
@property (readonly, nonatomic) RTPlatform *platform;
@property (readonly, nonatomic) SMSessionMonitor *sessionMonitor;
@property (readonly, nonatomic) SMMessagingService *messagingService;
@property (readonly, nonatomic) SMCarouselSessionManager *carouselSessionManager;
@property (readonly, nonatomic) RTNetworkOfInterestManager *networkOfInterestManager;
@property (retain, nonatomic) NSMutableArray *cacheManagerArray;
@property (readonly, nonatomic) SMSafetyCacheStore *safetyCacheStore;
@property (nonatomic) unsigned long long safetyCacheStoreAvailability;
@property (readonly, nonatomic) SMSessionStore *sessionStore;
@property (nonatomic) unsigned long long sessionStoreAvailability;
@property (readonly, nonatomic) RTDataProtectionManager *dataProtectionManager;
@property (readonly, nonatomic) RTBatteryManager *batteryManager;
@property (readonly, nonatomic) RTXPCActivityManager *xpcActivityManager;
@property (readonly, nonatomic) RTAuthorizationManager *authorizationManager;
@property (nonatomic) BOOL sessionsLoadedFromDisk;
@property (nonatomic) BOOL sessionManagerBootstrapped;
@property (retain, nonatomic) SMSessionReceiptZone *sessionReceiptZone;
@property (retain, nonatomic) SMInitiatorSessionInitilizationRequest *pendingInitializationRequest;
@property (readonly, nonatomic) RTWatchWristStateManager *wristStateManager;
@property (readonly, nonatomic) RTVehicleLocationProvider *vehicleLocationProvider;
@property (readonly, nonatomic) SMSessionMetricManager *sessionMetricManager;
@property (readonly, nonatomic) RTStarkManager *starkManager;
@property (readonly, nonatomic) SMSuggestionsManager *suggestionsManager;
@property (retain, nonatomic) RTInvocationDispatcher *dispatcher;
@property (retain, nonatomic) SMWatchdog *watchdog;
@property (retain, nonatomic) SMActiveSessionZone *activeSessionDetailsZone;
@property (retain, nonatomic) RTLocationManager *locationManager;
@property (retain, nonatomic) RTMotionActivityManager *motionActivityManager;
@property (readonly, nonatomic) SMSessionManager *sessionManager;
@property (readonly, nonatomic) RTLearnedLocationManager *learnedLocationManager;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (long long)periodicPurgePolicy;

- (void)performPurgeOfType:(long long)a0 referenceDate:(id)a1 completion:(id /* block */)a2;
- (void)dealloc;
- (void)removeObserver:(id)a0;
- (void)_setup;
- (void).cxx_destruct;
- (void)addObserver:(id)a0;
- (void)respondToNotificationWithIdentifier:(id)a0 sessionIdentifier:(id)a1 actionIdentifier:(id)a2 handler:(id /* block */)a3;
- (void)fetchCurrentSessionStateWithHandler:(id /* block */)a0;
- (void)_setupCacheManagersWithHandler:(id /* block */)a0;
- (id)invocationError;
- (void)onSafetyCacheStoreNotification:(id)a0;
- (void)_cancelInitializationForSessionID:(id)a0 handler:(id /* block */)a1;
- (void)_cancelInitializationWithHandler:(id /* block */)a0;
- (id)_createInitiatorCacheManagerForSessionID:(id)a0 receiverHandle:(id)a1;
- (void)_endSessionForSessionID:(id)a0 reason:(unsigned long long)a1 handler:(id /* block */)a2;
- (void)_fetchAllZonesFromContainerSynchronizerWithHandler:(id /* block */)a0;
- (void)_fetchAllZonesFromContainerWithHandler:(id /* block */)a0;
- (void)_fetchCurrentSessionStateWithHandler:(id /* block */)a0;
- (void)_fetchInitiatorSafetyCacheForSessionID:(id)a0 completion:(id /* block */)a1;
- (void)_fetchSessionReceiptForSessionID:(id)a0 completion:(id /* block */)a1;
- (BOOL)_hasSetupObjectsDependentOnPersistenceStack;
- (void)_initializeSessionReceiptZone;
- (void)_initializeSessionWithHandle:(id)a0 handler:(id /* block */)a1;
- (void)_modifySessionWithConfiguration:(id)a0 handler:(id /* block */)a1;
- (void)_onBecomingActiveDevice:(id)a0;
- (void)_onDeletedConversation:(id)a0;
- (void)_onDeletedMessage:(id)a0;
- (void)_onMessageReceived:(id)a0;
- (void)_onNearbyEffectivePairedDeviceChangedNotification:(id)a0;
- (void)_onSafetyCacheStoreNotification:(id)a0;
- (void)_onSecondarySOSTriggerWithState:(id)a0 forActiveDevice:(BOOL)a1;
- (void)_onSessionResumedWithState:(id)a0 forActiveDevice:(BOOL)a1;
- (void)_onSessionStartMessageSendResult:(id)a0;
- (void)_onSessionStateChanged:(id)a0 forActiveDevice:(BOOL)a1;
- (void)_onSessionStoreNotification:(id)a0;
- (void)_promptDestinationAnomalyVerificationWithContext:(id)a0 handler:(id /* block */)a1;
- (void)_promptRoundTripAnomalyVerificationWithContext:(id)a0 handler:(id /* block */)a1;
- (void)_promptSafeArrivalWithContext:(id)a0 handler:(id /* block */)a1;
- (void)_promptTimerEndedVerificationWithContext:(id)a0 handler:(id /* block */)a1;
- (void)_purgePredating:(id)a0 completion:(id /* block */)a1;
- (void)_respondToNotificationWithIdentifier:(id)a0 sessionIdentifier:(id)a1 actionIdentifier:(id)a2 handler:(id /* block */)a3;
- (void)_respondToTriggerPromptForSessionID:(id)a0 response:(long long)a1 handler:(id /* block */)a2;
- (void)_sendHeartbeatForSessionID:(id)a0 handler:(id /* block */)a1;
- (void)_sendSafetyCacheForSessionID:(id)a0 handler:(id /* block */)a1;
- (void)_setupOncePersistenceStackAvailable;
- (void)_setupSessionManager;
- (void)_setupSessionMonitor;
- (void)_startFrequentSingleShotFetchAllZonesActivity;
- (void)_startInfrequentPeriodicFetchAllZonesActivity;
- (void)_startInitializationProcess;
- (void)_startSessionWithConfiguration:(id)a0 handler:(id /* block */)a1;
- (void)_stopFrequentSingleShotFetchAllZonesActivity;
- (void)addObserverForSessionManager:(id)a0;
- (void)cacheManagerCleanedUpForSessionID:(id)a0;
- (void)cacheManagerDidUpdateCacheForSessionID:(id)a0 phoneCache:(id)a1 watchCache:(id)a2 cacheExpiryDate:(id)a3 cacheReleaseDate:(id)a4;
- (void)cancelInitializationForSessionID:(id)a0 handler:(id /* block */)a1;
- (void)cancelInitializationWithHandler:(id /* block */)a0;
- (id)convertEligibilityToSMErrorWithInitiator:(long long)a0 receiver:(long long)a1;
- (long long)convertInitiatorEligibilityToSMError:(long long)a0;
- (long long)convertReceiverEligibilityToSMError:(long long)a0;
- (void)endSessionForSessionID:(id)a0 reason:(unsigned long long)a1 handler:(id /* block */)a2;
- (void)fetchInitiatorSafetyCacheForSessionID:(id)a0 completion:(id /* block */)a1;
- (void)fetchSessionReceiptForSessionID:(id)a0 completion:(id /* block */)a1;
- (id)getCacheManagerForSessionID:(id)a0;
- (id)getCacheManagersForReceiverHandle:(id)a0;
- (void)handleSessionStateForNonActiveSessions:(id)a0;
- (id)initWithDefaultsManager:(id)a0 contactsManager:(id)a1 locationManager:(id)a2 motionActivityManager:(id)a3 platform:(id)a4 locationAwarenessManager:(id)a5 messagingService:(id)a6 safetyCacheStore:(id)a7 sessionStore:(id)a8 dataProtectionManager:(id)a9 batteryManager:(id)a10 xpcActivityManager:(id)a11 carouselSessionManager:(id)a12 networkOfInterestManager:(id)a13 authorizationManager:(id)a14 wristStateManager:(id)a15 vehicleLocationProvider:(id)a16 starkManager:(id)a17 suggestionsManager:(id)a18 learnedLocationManager:(id)a19;
- (id)initWithDefaultsManager:(id)a0 contactsManager:(id)a1 locationManager:(id)a2 motionActivityManager:(id)a3 platform:(id)a4 sessionManager:(id)a5 sessionMonitor:(id)a6 locationAwarenessManager:(id)a7 messagingService:(id)a8 safetyCacheStore:(id)a9 sessionStore:(id)a10 dataProtectionManager:(id)a11 batteryManager:(id)a12 xpcActivityManager:(id)a13 carouselSessionManager:(id)a14 networkOfInterestManager:(id)a15 authorizationManager:(id)a16 wristStateManager:(id)a17 vehicleLocationProvider:(id)a18 starkManager:(id)a19 suggestionsManager:(id)a20 learnedLocationManager:(id)a21;
- (void)initializeSessionWithHandle:(id)a0 handler:(id /* block */)a1;
- (void)modifySessionWithConfiguration:(id)a0 handler:(id /* block */)a1;
- (void)notifyObserversSafetyCacheDidUpdateForSessionID:(id)a0 phoneCache:(id)a1 watchCache:(id)a2 cacheExpiryDate:(id)a3 cacheReleaseDate:(id)a4;
- (void)onBecomingActiveDevice:(id)a0;
- (void)onDeletedConversation:(id)a0;
- (void)onDeletedMessage:(id)a0;
- (void)onMessageReceived:(id)a0;
- (void)onNearbyEffectivePairedDeviceChangedNotification:(id)a0;
- (void)onSecondarySOSTriggerWithState:(id)a0 forActiveDevice:(BOOL)a1;
- (void)onSessionResumedWithState:(id)a0 forActiveDevice:(BOOL)a1;
- (void)onSessionStartMessageSendResult:(id)a0;
- (void)onSessionStateChanged:(id)a0 forActiveDevice:(BOOL)a1;
- (void)onSessionStoreNotification:(id)a0;
- (void)promptDestinationAnomalyVerificationWithContext:(id)a0 handler:(id /* block */)a1;
- (void)promptRoundTripAnomalyVerificationWithContext:(id)a0 handler:(id /* block */)a1;
- (void)promptSafeArrivalWithContext:(id)a0 handler:(id /* block */)a1;
- (void)promptTimerEndedVerificationWithContext:(id)a0 handler:(id /* block */)a1;
- (void)receivedEmergencyContactsNotifiedSyncMessage:(id)a0;
- (void)receivedKeyReleaseInfoRequestMessage:(id)a0 fromHandle:(id)a1 fromMe:(BOOL)a2;
- (void)receivedSessionStartInfoRequestMessage:(id)a0 fromHandle:(id)a1 fromMe:(BOOL)a2;
- (void)receivedSessionStateUpdateReqMessage:(id)a0 fromHandle:(id)a1 fromMe:(BOOL)a2;
- (void)receivedSessionSyncMessage:(id)a0 fromHandle:(id)a1 fromMe:(BOOL)a2;
- (void)removeObserverForSessionManager:(id)a0;
- (void)respondToTriggerPromptForSessionID:(id)a0 response:(long long)a1 handler:(id /* block */)a2;
- (void)scheduledSendMessageCanceledForSessionID:(id)a0 guid:(id)a1;
- (void)scheduledSendMessageScheduledForSessionID:(id)a0 guid:(id)a1 date:(id)a2;
- (void)scheduledSendMessageSent:(id)a0;
- (void)sendHeartbeatForSessionID:(id)a0 handler:(id /* block */)a1;
- (void)sendSafetyCacheForSessionID:(id)a0 handler:(id /* block */)a1;
- (void)startSessionWithConfiguration:(id)a0 handler:(id /* block */)a1;

@end
