@class RTDefaultsManager, RTContactsManager, SMEligibilityChecker, RTDeviceLocationPredictor, RTMapServiceManager, RTLocationManager, RTAuthorizationManager, NSMutableSet, SMSuggestionsStore, RTVisitManager, RTLearnedLocationManager, RTXPCTimerAlarm, NSString, SMSessionStore, RTPlatform, RTDistanceCalculator, RTLocation, RTNavigationManager, RTMotionActivityPedometerData, SMSuggestionsMetricsManager, RTHealthKitManager, RTLearnedLocationOfInterest, RTMotionActivityManager, NSDate, RTLearnedLocationStore;

@interface SMSuggestionsManager : RTService <RTPurgable, SMSessionManagerObserverProtocol, SMSuggestionsProtocol>

@property (nonatomic) BOOL routineEnabled;
@property (retain, nonatomic) SMSuggestionsMetricsManager *suggestionsMetricsManager;
@property (retain, nonatomic) RTXPCTimerAlarm *walkingTriggerAlarm;
@property (copy, nonatomic) id /* block */ pedometerDataHandler;
@property (retain, nonatomic) NSDate *pedometerStartDate;
@property (retain, nonatomic) NSMutableSet *pedometerUUIDs;
@property (retain, nonatomic) RTMotionActivityPedometerData *previousPedometerData;
@property (nonatomic) BOOL isPedometerNotificationsSetupAfterRoutineStarted;
@property (readonly, copy, nonatomic) RTAuthorizationManager *authorizationManager;
@property (readonly, copy, nonatomic) RTContactsManager *contactsManager;
@property (readonly, copy, nonatomic) RTDefaultsManager *defaultsManager;
@property (readonly, copy, nonatomic) RTDeviceLocationPredictor *deviceLocationPredictor;
@property (readonly, copy, nonatomic) RTDistanceCalculator *distanceCalculator;
@property (readonly, copy, nonatomic) RTHealthKitManager *healthKitManager;
@property (readonly, copy, nonatomic) RTLearnedLocationStore *learnedLocationStore;
@property (readonly, copy, nonatomic) RTLearnedLocationManager *learnedLocationManager;
@property (readonly, copy, nonatomic) RTLocationManager *locationManager;
@property (readonly, copy, nonatomic) RTMapServiceManager *mapServiceManager;
@property (readonly, copy, nonatomic) RTMotionActivityManager *motionActivityManager;
@property (readonly, copy, nonatomic) RTNavigationManager *navigationManager;
@property (readonly, copy, nonatomic) RTPlatform *platform;
@property (readonly, copy, nonatomic) SMEligibilityChecker *eligibilityChecker;
@property (readonly, copy, nonatomic) SMSessionStore *sessionStore;
@property (readonly, copy, nonatomic) SMSuggestionsStore *suggestionsStore;
@property (readonly, copy, nonatomic) RTVisitManager *visitManager;
@property (copy, nonatomic) RTLocation *latestLocationOfTheDevice;
@property (retain, nonatomic) RTLearnedLocationOfInterest *currentLOI;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (long long)periodicPurgePolicy;

- (void)performPurgeOfType:(long long)a0 referenceDate:(id)a1 completion:(id /* block */)a2;
- (void)onAuthorizationNotification:(id)a0;
- (void)onNavigationNotification:(id)a0;
- (void)_onAuthorizationNotification:(id)a0;
- (void)_setup;
- (void)_onLearnedLocationManagerNotification:(id)a0;
- (void)_onVisitManagerNotification:(id)a0;
- (void)_onVehicleConnectedNotification:(id)a0;
- (void)_onNavigationNotification:(id)a0;
- (void).cxx_destruct;
- (void)onLearnedLocationManagerNotification:(id)a0;
- (void)onVehicleConnectedNotification:(id)a0;
- (void)onVisitManagerNotification:(id)a0;
- (void)fetchMostLikelyReceiverHandlesWithHandler:(id /* block */)a0;
- (void)shouldShowKeyboardSuggestionsForInitiator:(id)a0 receiver:(id)a1 handler:(id /* block */)a2;
- (void)shouldShowTipKitSuggestionsForInitiator:(id)a0 receiver:(id)a1 handler:(id /* block */)a2;
- (BOOL)_shouldShowProactiveSuggestions;
- (id)_generatePersonalizedSuggestionForRegularUserFromContext:(id)a0 error:(id *)a1;
- (BOOL)_checkInitiatorEligibilityWithError:(id *)a0;
- (BOOL)_checkReceiverEligibilityForHandle:(id)a0 error:(id *)a1;
- (id)_dedupePlaceInferencesWithOrder:(id)a0;
- (BOOL)_didInteractInPastWithHandle:(id)a0 timeInterval:(double)a1 error:(id *)a2;
- (void)_fetchMostLikelyReceiverHandlesWithHandler:(id /* block */)a0;
- (void)_fetchMostLikelySessionDestinationsWithHandler:(id /* block */)a0;
- (void)_fetchSuggestedSessionConfigurationWithHandler:(id /* block */)a0;
- (id)_generatePersonalizedSuggestionForFirstTimeUserFromContext:(id)a0 error:(id *)a1;
- (id)_generatePersonalizedSuggestionForOccasionalUserFromContext:(id)a0 error:(id *)a1;
- (id)_generatePersonalizedSuggestionFromContext:(id)a0 error:(id *)a1;
- (id)_getCurrentDateFromContext:(id)a0 error:(id *)a1;
- (id)_getFirstEligibleHandleFromSessionConfigurations:(id)a0 error:(id *)a1;
- (id)_getMessagesURLFromSessionConfig:(id)a0 error:(id *)a1;
- (id)_getNPLOIsToHomeWithOnlyHighConfidence:(BOOL)a0 location:(id)a1 date:(id)a2 error:(id *)a3;
- (id)_getNPLOIsWithOnlyHighConfidence:(BOOL)a0 location:(id)a1 date:(id)a2 error:(id *)a3;
- (id)_getNotificationExpirationDateForSuggestion:(id)a0 error:(id *)a1;
- (id)_getSMContactInformationFromSMHandle:(id)a0 error:(id *)a1;
- (id)_getSMHandlesFromRTContact:(id)a0 error:(id *)a1;
- (id)_getSMHandlesFromRTContacts:(id)a0 error:(id *)a1;
- (id)_getSessionConfigurationsWithOptions:(id)a0 error:(id *)a1;
- (id)_getSourceLocationFromContext:(id)a0 error:(id *)a1;
- (id)_getSuggestionBodyWithPlaceInference:(id)a0;
- (id)_getSuggestionTitleWithHandle:(id)a0 error:(id *)a1;
- (unsigned long long)_getSuggestionTriggerFromContext:(id)a0 error:(id *)a1;
- (id)_getSuggestionsFooter:(id)a0;
- (id)_getSunriseDateAtLocation:(id)a0 date:(id)a1 error:(id *)a2;
- (id)_getSunsetDateAtLocation:(id)a0 date:(id)a1 error:(id *)a2;
- (id)_getSystemVersionUpdateDate;
- (id)_getValuesFromDefaultsIfExists:(id)a0 error:(id *)a1;
- (BOOL)_isFirstTimeUserOfZelkovaWithError:(id *)a0;
- (BOOL)_isSessionConfigurationSimilarToTheSuggestion:(id)a0 sessionConfiguration:(id)a1 error:(id *)a2;
- (BOOL)_isUserInActiveSessionWithError:(id *)a0;
- (BOOL)_isValidDistance:(double)a0;
- (BOOL)_isWalkingBoutDetectedByAppendingPedometerData:(id)a0;
- (void)_launchSessionInitiationUIWithConfiguration:(id)a0 handler:(id /* block */)a1;
- (void)_logStatesForPedometerData;
- (void)_onHealthKitNotification:(id)a0;
- (void)_onSessionStartedWithConfiguration:(id)a0;
- (BOOL)_reRegisterForPedometerNotificationsForLearnedLocationOfInterest:(id)a0 startDate:(id)a1 error:(id *)a2;
- (BOOL)_refreshCurrentLocationWithError:(id *)a0;
- (BOOL)_registerForPedometerNotificationsForLearnedLocationOfInterest:(id)a0 startDate:(id)a1 error:(id *)a2;
- (BOOL)_resetStatesForPedometerData;
- (id)_runProactiveSuggestionsEngineWithContext:(id)a0 shouldStoreSuggestions:(BOOL)a1 error:(id *)a2;
- (BOOL)_setupPedometerDataHandler;
- (BOOL)_setupPedometerNotificationsIfExists:(id *)a0;
- (void)_shouldShowKeyboardSuggestionsForInitiator:(id)a0 receiver:(id)a1 handler:(id /* block */)a2;
- (void)_shouldShowTipKitSuggestionsForInitiator:(id)a0 receiver:(id)a1 handler:(id /* block */)a2;
- (BOOL)_showSuggestionsDetectionUIWithSuggestion:(id)a0 error:(id *)a1;
- (unsigned long long)_suppressSuggestion:(id)a0 context:(id)a1 error:(id *)a2;
- (BOOL)_unregisterForPedometerNotificationsWithError:(id *)a0;
- (void)_updateSystemVersionInDefaults;
- (id)createMasqueradingReferenceLocationFromFenceInfo:(id)a0 placeInference:(id)a1 error:(id *)a2;
- (id)createMasqueradingReferenceLocationFromFenceRadius:(double)a0 location:(id)a1 error:(id *)a2;
- (id)dedupeSessionConfigurations:(id)a0;
- (void)fetchMostLikelySessionDestinationsWithHandler:(id /* block */)a0;
- (void)fetchShouldShowProactiveSuggestionsWithHandler:(id /* block */)a0;
- (void)fetchSuggestedSessionConfigurationWithHandler:(id /* block */)a0;
- (id)initWithAuthorizationManager:(id)a0 contactsManager:(id)a1 defaultsManager:(id)a2 deviceLocationPredictor:(id)a3 distanceCalculator:(id)a4 healthKitManager:(id)a5 learnedLocationStore:(id)a6 learnedLocationManager:(id)a7 locationManager:(id)a8 mapServiceManager:(id)a9 motionActivityManager:(id)a10 navigationManager:(id)a11 platform:(id)a12 visitManager:(id)a13 sessionStore:(id)a14 suggestionsStore:(id)a15;
- (BOOL)isZelkovaSuggestionsFeatureEnabledWithError:(id *)a0;
- (void)launchSessionInitiationUIWithConfiguration:(id)a0 handler:(id /* block */)a1;
- (void)onHealthKitNotification:(id)a0;
- (void)onSessionStartedWithConfiguration:(id)a0;
- (id)placeInferenceFromLOI:(id)a0;
- (id)placeInferenceFromNPLOI:(id)a0;
- (void)runProactiveSuggestionsEngineWithContext:(id)a0 shouldStoreSuggestions:(BOOL)a1 handler:(id /* block */)a2;
- (void)showSuggestionsDetectionUIWithSuggestion:(id)a0 handler:(id /* block */)a1;

@end
