@interface AWDBiometricKitDailyUpdate : PBCodable <NSCopying> {
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _baseTemplateFeatureCounts;
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _bioCheckInfos;
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _bioCheckResults;
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _matchingBinCounts;
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _matchingIdentityCounts;
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _matchingTemplateTypeCounts;
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _onlineUpdateTemplateFeatureCounts;
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _passcodeUpdateTemplateFeatureCounts;
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _passcodeUpdates;
    struct { unsigned char bioLockoutTime : 1; unsigned char timestamp : 1; unsigned char bioLockoutCount : 1; unsigned char enrolledIdentityCount : 1; unsigned char matchingCountDouble01 : 1; unsigned char matchingCountDouble02 : 1; unsigned char matchingCountDouble03 : 1; unsigned char matchingCountDouble04 : 1; unsigned char onlineUnlockCount : 1; unsigned char shortTermUnlockCount : 1; unsigned char staticUnlockCount : 1; unsigned char totalMatchAttempts : 1; unsigned char totalMatchAttemptsFaceDetected : 1; unsigned char totalMatchAttemptsFailed : 1; unsigned char totalMatchAttemptsSuccessful : 1; unsigned char yogiErrorDays : 1; unsigned char applePayEnabled : 1; unsigned char attentionDetectionEnabled : 1; unsigned char autoRetryEnabled : 1; unsigned char cameraInterlock : 1; unsigned char combinedSequenceEnabled : 1; unsigned char unlockEnabled : 1; } _has;
}

@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) unsigned long long timestamp;
@property (readonly, nonatomic) unsigned long long baseTemplateFeatureCountsCount;
@property (readonly, nonatomic) unsigned int *baseTemplateFeatureCounts;
@property (readonly, nonatomic) unsigned long long onlineUpdateTemplateFeatureCountsCount;
@property (readonly, nonatomic) unsigned int *onlineUpdateTemplateFeatureCounts;
@property (readonly, nonatomic) unsigned long long passcodeUpdateTemplateFeatureCountsCount;
@property (readonly, nonatomic) unsigned int *passcodeUpdateTemplateFeatureCounts;
@property (nonatomic) BOOL hasUnlockEnabled;
@property (nonatomic) BOOL unlockEnabled;
@property (nonatomic) BOOL hasApplePayEnabled;
@property (nonatomic) BOOL applePayEnabled;
@property (nonatomic) BOOL hasAttentionDetectionEnabled;
@property (nonatomic) BOOL attentionDetectionEnabled;
@property (nonatomic) BOOL hasMatchingCountDouble01;
@property (nonatomic) unsigned int matchingCountDouble01;
@property (nonatomic) BOOL hasMatchingCountDouble02;
@property (nonatomic) unsigned int matchingCountDouble02;
@property (nonatomic) BOOL hasMatchingCountDouble03;
@property (nonatomic) unsigned int matchingCountDouble03;
@property (nonatomic) BOOL hasMatchingCountDouble04;
@property (nonatomic) unsigned int matchingCountDouble04;
@property (nonatomic) BOOL hasStaticUnlockCount;
@property (nonatomic) unsigned int staticUnlockCount;
@property (nonatomic) BOOL hasOnlineUnlockCount;
@property (nonatomic) unsigned int onlineUnlockCount;
@property (nonatomic) BOOL hasShortTermUnlockCount;
@property (nonatomic) unsigned int shortTermUnlockCount;
@property (readonly, nonatomic) unsigned long long matchingBinCountsCount;
@property (readonly, nonatomic) unsigned int *matchingBinCounts;
@property (readonly, nonatomic) unsigned long long matchingTemplateTypeCountsCount;
@property (readonly, nonatomic) unsigned int *matchingTemplateTypeCounts;
@property (nonatomic) BOOL hasCameraInterlock;
@property (nonatomic) BOOL cameraInterlock;
@property (readonly, nonatomic) unsigned long long bioCheckInfosCount;
@property (readonly, nonatomic) unsigned int *bioCheckInfos;
@property (readonly, nonatomic) unsigned long long bioCheckResultsCount;
@property (readonly, nonatomic) unsigned int *bioCheckResults;
@property (readonly, nonatomic) unsigned long long passcodeUpdatesCount;
@property (readonly, nonatomic) unsigned int *passcodeUpdates;
@property (nonatomic) BOOL hasEnrolledIdentityCount;
@property (nonatomic) unsigned int enrolledIdentityCount;
@property (readonly, nonatomic) unsigned long long matchingIdentityCountsCount;
@property (readonly, nonatomic) unsigned int *matchingIdentityCounts;
@property (nonatomic) BOOL hasCombinedSequenceEnabled;
@property (nonatomic) BOOL combinedSequenceEnabled;
@property (nonatomic) BOOL hasBioLockoutTime;
@property (nonatomic) unsigned long long bioLockoutTime;
@property (nonatomic) BOOL hasBioLockoutCount;
@property (nonatomic) unsigned int bioLockoutCount;
@property (nonatomic) BOOL hasAutoRetryEnabled;
@property (nonatomic) BOOL autoRetryEnabled;
@property (nonatomic) BOOL hasYogiErrorDays;
@property (nonatomic) unsigned int yogiErrorDays;
@property (nonatomic) BOOL hasTotalMatchAttempts;
@property (nonatomic) unsigned int totalMatchAttempts;
@property (nonatomic) BOOL hasTotalMatchAttemptsSuccessful;
@property (nonatomic) unsigned int totalMatchAttemptsSuccessful;
@property (nonatomic) BOOL hasTotalMatchAttemptsFailed;
@property (nonatomic) unsigned int totalMatchAttemptsFailed;
@property (nonatomic) BOOL hasTotalMatchAttemptsFaceDetected;
@property (nonatomic) unsigned int totalMatchAttemptsFaceDetected;

- (id)copyWithZone:(struct _NSZone { } *)a0;
- (void)mergeFrom:(id)a0;
- (void)dealloc;
- (BOOL)readFrom:(id)a0;
- (unsigned long long)hash;
- (void)writeTo:(id)a0;
- (id)description;
- (void)copyTo:(id)a0;
- (BOOL)isEqual:(id)a0;
- (id)dictionaryRepresentation;
- (void)addBaseTemplateFeatureCount:(unsigned int)a0;
- (void)addOnlineUpdateTemplateFeatureCount:(unsigned int)a0;
- (void)addPasscodeUpdateTemplateFeatureCount:(unsigned int)a0;
- (void)addMatchingIdentityCounts:(unsigned int)a0;
- (void)addMatchingTemplateTypeCounts:(unsigned int)a0;
- (void)addMatchingBinCounts:(unsigned int)a0;
- (void)addBioCheckInfo:(unsigned int)a0;
- (void)addBioCheckResult:(unsigned int)a0;
- (void)addPasscodeUpdate:(unsigned int)a0;
- (void)clearBaseTemplateFeatureCounts;
- (unsigned int)baseTemplateFeatureCountAtIndex:(unsigned long long)a0;
- (void)clearOnlineUpdateTemplateFeatureCounts;
- (unsigned int)onlineUpdateTemplateFeatureCountAtIndex:(unsigned long long)a0;
- (void)clearPasscodeUpdateTemplateFeatureCounts;
- (unsigned int)passcodeUpdateTemplateFeatureCountAtIndex:(unsigned long long)a0;
- (void)clearMatchingBinCounts;
- (unsigned int)matchingBinCountsAtIndex:(unsigned long long)a0;
- (void)clearMatchingTemplateTypeCounts;
- (unsigned int)matchingTemplateTypeCountsAtIndex:(unsigned long long)a0;
- (void)clearBioCheckInfos;
- (unsigned int)bioCheckInfoAtIndex:(unsigned long long)a0;
- (void)clearBioCheckResults;
- (unsigned int)bioCheckResultAtIndex:(unsigned long long)a0;
- (void)clearPasscodeUpdates;
- (unsigned int)passcodeUpdateAtIndex:(unsigned long long)a0;
- (void)clearMatchingIdentityCounts;
- (unsigned int)matchingIdentityCountsAtIndex:(unsigned long long)a0;
- (void)setBaseTemplateFeatureCounts:(unsigned int *)a0 count:(unsigned long long)a1;
- (void)setOnlineUpdateTemplateFeatureCounts:(unsigned int *)a0 count:(unsigned long long)a1;
- (void)setPasscodeUpdateTemplateFeatureCounts:(unsigned int *)a0 count:(unsigned long long)a1;
- (void)setMatchingBinCounts:(unsigned int *)a0 count:(unsigned long long)a1;
- (void)setMatchingTemplateTypeCounts:(unsigned int *)a0 count:(unsigned long long)a1;
- (void)setBioCheckInfos:(unsigned int *)a0 count:(unsigned long long)a1;
- (void)setBioCheckResults:(unsigned int *)a0 count:(unsigned long long)a1;
- (void)setPasscodeUpdates:(unsigned int *)a0 count:(unsigned long long)a1;
- (void)setMatchingIdentityCounts:(unsigned int *)a0 count:(unsigned long long)a1;

@end
