@class OTAResistanceData, OTABMUResistance;

@interface OTAParamRC : PBCodable <NSCopying> {
    struct { float *list; unsigned long long count; unsigned long long size; } _agingCoeffForR0TemperatureCoeffs;
    struct { float *list; unsigned long long count; unsigned long long size; } _agingCoeffForR0s;
    struct { float *list; unsigned long long count; unsigned long long size; } _agingCoeffForR1TemperatureCoeffs;
    struct { float *list; unsigned long long count; unsigned long long size; } _agingCoeffForR1s;
    struct { float *list; unsigned long long count; unsigned long long size; } _agingCoeffForR2TemperatureCoeffs;
    struct { float *list; unsigned long long count; unsigned long long size; } _agingCoeffForR2s;
    struct { float *list; unsigned long long count; unsigned long long size; } _agingCoeffForR3TemperatureCoeffs;
    struct { float *list; unsigned long long count; unsigned long long size; } _agingCoeffForR3s;
    struct { float *list; unsigned long long count; unsigned long long size; } _agingCoeffForRCFreq1TemperatureCoeffs;
    struct { float *list; unsigned long long count; unsigned long long size; } _agingCoeffForRCFreq1s;
    struct { float *list; unsigned long long count; unsigned long long size; } _agingCoeffForRCFreq2TemperatureCoeffs;
    struct { float *list; unsigned long long count; unsigned long long size; } _agingCoeffForRCFreq2s;
    struct { float *list; unsigned long long count; unsigned long long size; } _agingCoeffForRCFreq3TemperatureCoeffs;
    struct { float *list; unsigned long long count; unsigned long long size; } _agingCoeffForRCFreq3s;
    struct { float *list; unsigned long long count; unsigned long long size; } _agingCoeffForRCFreq4TemperatureCoeffs;
    struct { float *list; unsigned long long count; unsigned long long size; } _agingCoeffForRCFreq4s;
    struct { float *list; unsigned long long count; unsigned long long size; } _agingCoeffForRdcTemperatureCoeffs;
    struct { float *list; unsigned long long count; unsigned long long size; } _agingCoeffForRdcs;
    struct { float *list; unsigned long long count; unsigned long long size; } _baselineRdcs;
    struct { float *list; unsigned long long count; unsigned long long size; } _coeffSOCs;
    struct { float *list; unsigned long long count; unsigned long long size; } _coeffVs;
    struct { float *list; unsigned long long count; unsigned long long size; } _gridOCVs;
    struct { float *list; unsigned long long count; unsigned long long size; } _gridWRdcRatios;
    struct { float *list; unsigned long long count; unsigned long long size; } _qmaxs;
    struct { float *list; unsigned long long count; unsigned long long size; } _slopeForR0Extraps;
    struct { float *list; unsigned long long count; unsigned long long size; } _slopeForR1Extraps;
    struct { float *list; unsigned long long count; unsigned long long size; } _slopeForR2Extraps;
    struct { float *list; unsigned long long count; unsigned long long size; } _slopeForR3Extraps;
    struct { unsigned char baselineWRdc : 1; unsigned char mLBConfig : 1; unsigned char maxRdcR25Ratio : 1; unsigned char maxRdcRatio : 1; unsigned char maxRdcRatioR2Extrap : 1; unsigned char wRdcRatioThresh : 1; } _has;
}

@property (readonly, nonatomic) BOOL hasR0;
@property (retain, nonatomic) OTAResistanceData *r0;
@property (readonly, nonatomic) BOOL hasR1;
@property (retain, nonatomic) OTAResistanceData *r1;
@property (readonly, nonatomic) BOOL hasBaselineR1;
@property (retain, nonatomic) OTAResistanceData *baselineR1;
@property (readonly, nonatomic) BOOL hasR2;
@property (retain, nonatomic) OTAResistanceData *r2;
@property (readonly, nonatomic) BOOL hasBaselineR2;
@property (retain, nonatomic) OTAResistanceData *baselineR2;
@property (readonly, nonatomic) BOOL hasRCFreq1;
@property (retain, nonatomic) OTAResistanceData *rCFreq1;
@property (readonly, nonatomic) BOOL hasRCFreq2;
@property (retain, nonatomic) OTAResistanceData *rCFreq2;
@property (readonly, nonatomic) BOOL hasRCFreq3;
@property (retain, nonatomic) OTAResistanceData *rCFreq3;
@property (readonly, nonatomic) unsigned long long agingCoeffForR0sCount;
@property (readonly, nonatomic) float *agingCoeffForR0s;
@property (readonly, nonatomic) unsigned long long agingCoeffForR0TemperatureCoeffsCount;
@property (readonly, nonatomic) float *agingCoeffForR0TemperatureCoeffs;
@property (readonly, nonatomic) unsigned long long agingCoeffForR1sCount;
@property (readonly, nonatomic) float *agingCoeffForR1s;
@property (readonly, nonatomic) unsigned long long agingCoeffForR1TemperatureCoeffsCount;
@property (readonly, nonatomic) float *agingCoeffForR1TemperatureCoeffs;
@property (readonly, nonatomic) unsigned long long agingCoeffForR2sCount;
@property (readonly, nonatomic) float *agingCoeffForR2s;
@property (readonly, nonatomic) unsigned long long agingCoeffForR2TemperatureCoeffsCount;
@property (readonly, nonatomic) float *agingCoeffForR2TemperatureCoeffs;
@property (readonly, nonatomic) unsigned long long baselineRdcsCount;
@property (readonly, nonatomic) float *baselineRdcs;
@property (readonly, nonatomic) BOOL hasBaselineR0;
@property (retain, nonatomic) OTAResistanceData *baselineR0;
@property (readonly, nonatomic) BOOL hasBmuResistance;
@property (retain, nonatomic) OTABMUResistance *bmuResistance;
@property (nonatomic) unsigned int chemID;
@property (readonly, nonatomic) unsigned long long gridOCVsCount;
@property (readonly, nonatomic) float *gridOCVs;
@property (readonly, nonatomic) BOOL hasBaselineR3;
@property (retain, nonatomic) OTAResistanceData *baselineR3;
@property (nonatomic) BOOL hasMaxRdcRatio;
@property (nonatomic) float maxRdcRatio;
@property (nonatomic) BOOL hasMaxRdcRatioR2Extrap;
@property (nonatomic) float maxRdcRatioR2Extrap;
@property (nonatomic) BOOL hasBaselineWRdc;
@property (nonatomic) float baselineWRdc;
@property (readonly, nonatomic) unsigned long long slopeForR0ExtrapsCount;
@property (readonly, nonatomic) float *slopeForR0Extraps;
@property (readonly, nonatomic) unsigned long long slopeForR1ExtrapsCount;
@property (readonly, nonatomic) float *slopeForR1Extraps;
@property (readonly, nonatomic) unsigned long long slopeForR2ExtrapsCount;
@property (readonly, nonatomic) float *slopeForR2Extraps;
@property (readonly, nonatomic) unsigned long long slopeForR3ExtrapsCount;
@property (readonly, nonatomic) float *slopeForR3Extraps;
@property (readonly, nonatomic) BOOL hasR3;
@property (retain, nonatomic) OTAResistanceData *r3;
@property (readonly, nonatomic) BOOL hasRCFreq4;
@property (retain, nonatomic) OTAResistanceData *rCFreq4;
@property (readonly, nonatomic) BOOL hasBaselineR4;
@property (retain, nonatomic) OTAResistanceData *baselineR4;
@property (readonly, nonatomic) BOOL hasBaselineRCFreq1;
@property (retain, nonatomic) OTAResistanceData *baselineRCFreq1;
@property (readonly, nonatomic) BOOL hasBaselineRCFreq2;
@property (retain, nonatomic) OTAResistanceData *baselineRCFreq2;
@property (readonly, nonatomic) BOOL hasBaselineRCFreq3;
@property (retain, nonatomic) OTAResistanceData *baselineRCFreq3;
@property (readonly, nonatomic) BOOL hasBaselineRCFreq4;
@property (retain, nonatomic) OTAResistanceData *baselineRCFreq4;
@property (readonly, nonatomic) unsigned long long agingCoeffForR3sCount;
@property (readonly, nonatomic) float *agingCoeffForR3s;
@property (readonly, nonatomic) unsigned long long agingCoeffForR3TemperatureCoeffsCount;
@property (readonly, nonatomic) float *agingCoeffForR3TemperatureCoeffs;
@property (readonly, nonatomic) unsigned long long agingCoeffForRCFreq1sCount;
@property (readonly, nonatomic) float *agingCoeffForRCFreq1s;
@property (readonly, nonatomic) unsigned long long agingCoeffForRCFreq2sCount;
@property (readonly, nonatomic) float *agingCoeffForRCFreq2s;
@property (readonly, nonatomic) unsigned long long agingCoeffForRCFreq3sCount;
@property (readonly, nonatomic) float *agingCoeffForRCFreq3s;
@property (readonly, nonatomic) unsigned long long agingCoeffForRCFreq4sCount;
@property (readonly, nonatomic) float *agingCoeffForRCFreq4s;
@property (readonly, nonatomic) unsigned long long agingCoeffForRCFreq1TemperatureCoeffsCount;
@property (readonly, nonatomic) float *agingCoeffForRCFreq1TemperatureCoeffs;
@property (readonly, nonatomic) unsigned long long agingCoeffForRCFreq2TemperatureCoeffsCount;
@property (readonly, nonatomic) float *agingCoeffForRCFreq2TemperatureCoeffs;
@property (readonly, nonatomic) unsigned long long agingCoeffForRCFreq3TemperatureCoeffsCount;
@property (readonly, nonatomic) float *agingCoeffForRCFreq3TemperatureCoeffs;
@property (readonly, nonatomic) unsigned long long agingCoeffForRCFreq4TemperatureCoeffsCount;
@property (readonly, nonatomic) float *agingCoeffForRCFreq4TemperatureCoeffs;
@property (nonatomic) BOOL hasMLBConfig;
@property (nonatomic) int mLBConfig;
@property (nonatomic) BOOL hasWRdcRatioThresh;
@property (nonatomic) float wRdcRatioThresh;
@property (readonly, nonatomic) unsigned long long gridWRdcRatiosCount;
@property (readonly, nonatomic) float *gridWRdcRatios;
@property (readonly, nonatomic) unsigned long long coeffSOCsCount;
@property (readonly, nonatomic) float *coeffSOCs;
@property (readonly, nonatomic) unsigned long long coeffVsCount;
@property (readonly, nonatomic) float *coeffVs;
@property (readonly, nonatomic) BOOL hasRdc;
@property (retain, nonatomic) OTAResistanceData *rdc;
@property (readonly, nonatomic) unsigned long long agingCoeffForRdcsCount;
@property (readonly, nonatomic) float *agingCoeffForRdcs;
@property (readonly, nonatomic) unsigned long long agingCoeffForRdcTemperatureCoeffsCount;
@property (readonly, nonatomic) float *agingCoeffForRdcTemperatureCoeffs;
@property (readonly, nonatomic) unsigned long long qmaxsCount;
@property (readonly, nonatomic) float *qmaxs;
@property (nonatomic) BOOL hasMaxRdcR25Ratio;
@property (nonatomic) float maxRdcR25Ratio;

- (void)addAgingCoeffForR3TemperatureCoeff:(float)a0;
- (void)clearAgingCoeffForRCFreq2s;
- (void)addAgingCoeffForRCFreq1TemperatureCoeff:(float)a0;
- (void)addAgingCoeffForRdcTemperatureCoeff:(float)a0;
- (unsigned long long)hash;
- (float)agingCoeffForR3AtIndex:(unsigned long long)a0;
- (void)dealloc;
- (float)agingCoeffForRCFreq4AtIndex:(unsigned long long)a0;
- (void)addAgingCoeffForRCFreq2:(float)a0;
- (void)clearAgingCoeffForRCFreq1TemperatureCoeffs;
- (float)coeffVAtIndex:(unsigned long long)a0;
- (BOOL)readFrom:(id)a0;
- (void)setAgingCoeffForR1s:(float *)a0 count:(unsigned long long)a1;
- (void)setAgingCoeffForR2TemperatureCoeffs:(float *)a0 count:(unsigned long long)a1;
- (float)agingCoeffForRCFreq4TemperatureCoeffAtIndex:(unsigned long long)a0;
- (float)slopeForR1ExtrapAtIndex:(unsigned long long)a0;
- (void)clearAgingCoeffForR2s;
- (void)setAgingCoeffForRCFreq4s:(float *)a0 count:(unsigned long long)a1;
- (void)addAgingCoeffForRCFreq4TemperatureCoeff:(float)a0;
- (id)mLBConfigAsString:(int)a0;
- (void)setAgingCoeffForRCFreq2TemperatureCoeffs:(float *)a0 count:(unsigned long long)a1;
- (float)agingCoeffForR2AtIndex:(unsigned long long)a0;
- (float)agingCoeffForR1TemperatureCoeffAtIndex:(unsigned long long)a0;
- (float)agingCoeffForR1AtIndex:(unsigned long long)a0;
- (void)setSlopeForR0Extraps:(float *)a0 count:(unsigned long long)a1;
- (float)agingCoeffForRCFreq3TemperatureCoeffAtIndex:(unsigned long long)a0;
- (void)setSlopeForR1Extraps:(float *)a0 count:(unsigned long long)a1;
- (void)setCoeffSOCs:(float *)a0 count:(unsigned long long)a1;
- (float)agingCoeffForRCFreq1AtIndex:(unsigned long long)a0;
- (void)setAgingCoeffForRCFreq3TemperatureCoeffs:(float *)a0 count:(unsigned long long)a1;
- (void)addAgingCoeffForR0:(float)a0;
- (void)addQmax:(float)a0;
- (void)clearAgingCoeffForRCFreq3TemperatureCoeffs;
- (void)clearAgingCoeffForR2TemperatureCoeffs;
- (void)writeTo:(id)a0;
- (float)agingCoeffForRdcTemperatureCoeffAtIndex:(unsigned long long)a0;
- (void)setAgingCoeffForRCFreq1TemperatureCoeffs:(float *)a0 count:(unsigned long long)a1;
- (void)setSlopeForR2Extraps:(float *)a0 count:(unsigned long long)a1;
- (float)gridWRdcRatioAtIndex:(unsigned long long)a0;
- (float)agingCoeffForR0TemperatureCoeffAtIndex:(unsigned long long)a0;
- (void)clearAgingCoeffForRdcs;
- (void)setAgingCoeffForR3s:(float *)a0 count:(unsigned long long)a1;
- (float)agingCoeffForRdcAtIndex:(unsigned long long)a0;
- (void)clearAgingCoeffForRCFreq4TemperatureCoeffs;
- (void)setAgingCoeffForR0s:(float *)a0 count:(unsigned long long)a1;
- (void)addSlopeForR1Extrap:(float)a0;
- (void)clearSlopeForR0Extraps;
- (void)clearAgingCoeffForR1TemperatureCoeffs;
- (void)clearAgingCoeffForR1s;
- (void)clearCoeffSOCs;
- (float)gridOCVAtIndex:(unsigned long long)a0;
- (void)setGridOCVs:(float *)a0 count:(unsigned long long)a1;
- (void)setSlopeForR3Extraps:(float *)a0 count:(unsigned long long)a1;
- (void)clearAgingCoeffForRdcTemperatureCoeffs;
- (void)setAgingCoeffForR1TemperatureCoeffs:(float *)a0 count:(unsigned long long)a1;
- (void)setBaselineRdcs:(float *)a0 count:(unsigned long long)a1;
- (void)setAgingCoeffForR0TemperatureCoeffs:(float *)a0 count:(unsigned long long)a1;
- (float)agingCoeffForRCFreq2TemperatureCoeffAtIndex:(unsigned long long)a0;
- (void)addAgingCoeffForRCFreq1:(float)a0;
- (float)coeffSOCAtIndex:(unsigned long long)a0;
- (id)description;
- (void)clearAgingCoeffForRCFreq1s;
- (void)setAgingCoeffForRCFreq3s:(float *)a0 count:(unsigned long long)a1;
- (void)addGridWRdcRatio:(float)a0;
- (void)clearAgingCoeffForR3s;
- (float)agingCoeffForR2TemperatureCoeffAtIndex:(unsigned long long)a0;
- (void)addGridOCV:(float)a0;
- (float)agingCoeffForRCFreq1TemperatureCoeffAtIndex:(unsigned long long)a0;
- (void)clearAgingCoeffForRCFreq2TemperatureCoeffs;
- (void)addAgingCoeffForR1:(float)a0;
- (float)baselineRdcAtIndex:(unsigned long long)a0;
- (void)setGridWRdcRatios:(float *)a0 count:(unsigned long long)a1;
- (int)StringAsMLBConfig:(id)a0;
- (void)addSlopeForR0Extrap:(float)a0;
- (void)addAgingCoeffForR2TemperatureCoeff:(float)a0;
- (float)slopeForR3ExtrapAtIndex:(unsigned long long)a0;
- (void)addSlopeForR3Extrap:(float)a0;
- (void).cxx_destruct;
- (float)agingCoeffForRCFreq2AtIndex:(unsigned long long)a0;
- (void)clearSlopeForR3Extraps;
- (float)agingCoeffForR3TemperatureCoeffAtIndex:(unsigned long long)a0;
- (void)addSlopeForR2Extrap:(float)a0;
- (void)clearQmaxs;
- (float)agingCoeffForR0AtIndex:(unsigned long long)a0;
- (void)setAgingCoeffForRCFreq4TemperatureCoeffs:(float *)a0 count:(unsigned long long)a1;
- (void)clearSlopeForR1Extraps;
- (void)addCoeffSOC:(float)a0;
- (void)addAgingCoeffForR1TemperatureCoeff:(float)a0;
- (void)addBaselineRdc:(float)a0;
- (void)clearAgingCoeffForRCFreq4s;
- (void)setAgingCoeffForRCFreq1s:(float *)a0 count:(unsigned long long)a1;
- (void)addAgingCoeffForRCFreq4:(float)a0;
- (void)clearAgingCoeffForR0TemperatureCoeffs;
- (void)addAgingCoeffForRCFreq3:(float)a0;
- (void)addAgingCoeffForRCFreq2TemperatureCoeff:(float)a0;
- (id)dictionaryRepresentation;
- (void)setAgingCoeffForR3TemperatureCoeffs:(float *)a0 count:(unsigned long long)a1;
- (void)setAgingCoeffForRdcTemperatureCoeffs:(float *)a0 count:(unsigned long long)a1;
- (void)clearBaselineRdcs;
- (void)addCoeffV:(float)a0;
- (void)copyTo:(id)a0;
- (void)setAgingCoeffForRCFreq2s:(float *)a0 count:(unsigned long long)a1;
- (void)addAgingCoeffForR0TemperatureCoeff:(float)a0;
- (float)slopeForR0ExtrapAtIndex:(unsigned long long)a0;
- (BOOL)isEqual:(id)a0;
- (float)agingCoeffForRCFreq3AtIndex:(unsigned long long)a0;
- (void)clearAgingCoeffForRCFreq3s;
- (void)setAgingCoeffForRdcs:(float *)a0 count:(unsigned long long)a1;
- (void)clearAgingCoeffForR3TemperatureCoeffs;
- (void)clearCoeffVs;
- (void)setQmaxs:(float *)a0 count:(unsigned long long)a1;
- (void)setCoeffVs:(float *)a0 count:(unsigned long long)a1;
- (void)clearAgingCoeffForR0s;
- (void)mergeFrom:(id)a0;
- (void)clearGridWRdcRatios;
- (void)addAgingCoeffForR3:(float)a0;
- (void)clearSlopeForR2Extraps;
- (void)addAgingCoeffForR2:(float)a0;
- (float)slopeForR2ExtrapAtIndex:(unsigned long long)a0;
- (id)copyWithZone:(struct _NSZone { } *)a0;
- (void)setAgingCoeffForR2s:(float *)a0 count:(unsigned long long)a1;
- (void)addAgingCoeffForRdc:(float)a0;
- (float)qmaxAtIndex:(unsigned long long)a0;
- (void)clearGridOCVs;
- (void)addAgingCoeffForRCFreq3TemperatureCoeff:(float)a0;

@end
