@class NSFileHandle, NSMutableDictionary, NSDate, NSObject, NSDictionary, NSMutableString, BLTemplateList, NSDateFormatter, NSException, BiometricKitIdentity, NSString, BiometricKitXPCServerMesa, BLTimeBox;
@protocol OS_os_log;

@interface BioLogBase : NSObject {
    BiometricKitXPCServerMesa *_server;
    NSString *_rootPath;
    NSString *_logPath;
    NSString *_logFilePath;
    NSString *_lastLogMessage;
    NSDictionary *_fileAttributes;
    NSDictionary *_fileAttributesProtected;
    NSFileHandle *_logFile;
    BLTimeBox *_timeBox;
    NSDate *_logStartDate;
    NSDate *_lastStatusESDRecovery;
    NSException *_lastLogWriteException;
    NSDateFormatter *_timestampFormatter;
    NSDateFormatter *_fileNameFormatter;
    NSDateFormatter *_timeZoneFormatter;
    NSDateFormatter *_milisecondsFormatter;
    unsigned char _fingerStateCaptureCounter;
    unsigned char _mode;
    NSMutableString *_imageCommentString;
    BLTemplateList *_templateList;
    BiometricKitIdentity *_lastMatchedIdentity;
    BOOL _chargerConnected;
    BOOL _compactOSLogOnly;
    BOOL _compact;
    NSObject<OS_os_log> *_osLog;
    unsigned long long _loggingType;
    unsigned long long _lastLogMessageRepeated;
    NSMutableDictionary *_logDetails;
    struct IONotificationPort { } *_notificationPort;
    unsigned int _mesaScanningStateNotification;
    unsigned int _powerSourceNotification;
}

@property unsigned long long absoluteTimeOverride;

+ (void)enableSensorStatusMessages:(BOOL)a0 withServerObject:(id)a1;
+ (int)runInShell:(id)a0;
+ (void)updateLogger:(id *)a0 withServerObject:(id)a1 identities:(id)a2;

- (void)logDelegateRegistered:(BOOL)a0 fromClient:(id)a1;
- (void)logFingerDetectStartWithOptions:(id)a0 fromClient:(id)a1;
- (void)logThermalLevel:(unsigned char)a0;
- (void)logAsync:(id)a0 withDetails:(id)a1 timestamp:(unsigned long long)a2 endingWithToken:(char *)a3;
- (id)packAllLogs;
- (void)dealloc;
- (void)logSKSLockState:(unsigned short)a0 forUser:(unsigned int)a1 withTimestamp:(unsigned long long)a2;
- (void)logEnrollResultIdentity:(id)a0 withTimestamp:(unsigned long long)a1 forClients:(id)a2;
- (void)logMatchStartError:(int)a0;
- (void)logSensorRecoveryReason:(unsigned int)a0 withTimestamp:(unsigned long long)a1;
- (void)logProtectedConfiguration:(id)a0 forUser:(unsigned int)a1 fromClient:(id)a2;
- (void)logKernelMessage:(id)a0;
- (void)logDisplayState:(BOOL)a0 withTimestamp:(unsigned long long)a1;
- (void)logRemoveIdentity:(id)a0 withError:(int)a1;
- (void)logProtectedConfigurationError:(int)a0;
- (id)packCurrentLog;
- (void)logDisconnectingClient:(id)a0;
- (id)logQueue;
- (void)closeLogFile;
- (void)logMatchStartFromClient:(id)a0;
- (void)logSensorStatus:(id)a0;
- (void)logGetMaxIdentityCount:(int)a0 fromClient:(id)a1;
- (void)logUpdateIdentity:(id)a0 withOptions:(id)a1 fromClient:(id)a2;
- (void)logCancelError:(int)a0;
- (void)logEnrollStartForUser:(unsigned int)a0 fromClient:(id)a1;
- (void)logFingerDetectStartError:(int)a0;
- (void)logStatusMessage:(int)a0 withData:(id)a1 timestamp:(unsigned long long)a2 forClients:(id)a3;
- (void)logCall:(SEL)a0 withError:(int)a1;
- (void)logCall:(SEL)a0 withParameters:(id)a1 fromClient:(id)a2;
- (void)logSaveTemplateListError:(int)a0;
- (void)logMatchStart:(id)a0 withOptions:(id)a1 fromClient:(id)a2;
- (void)logRemoveIdentity:(id)a0 withOptions:(id)a1 fromClient:(id)a2 withTimestamp:(unsigned long long)a3;
- (void)logSaveTemplateListWithDetails:(id)a0;
- (void)logEnrollStartError:(int)a0;
- (void)logHomeButtonState:(BOOL)a0 fromKernel:(BOOL)a1 withTimestamp:(unsigned long long)a2;
- (void).cxx_destruct;
- (void)updateIdentity:(id)a0;
- (BOOL)fileRadarWithLogs:(id)a0 withDescription:(id)a1;
- (id)attachmentsFromCurrentLog;
- (void)logRemoveAllIdentitiesForUser:(unsigned int)a0 withOptions:(id)a1 fromClient:(id)a2;
- (void)logUnlockedStateWithIdentities:(id)a0;
- (id)attachmentsFromAllLogs;
- (void)logWakeGestureState:(long long)a0;
- (void)logGetIdentityFromUUID:(id)a0 fromClient:(id)a1;
- (void)logGetIdentities:(id)a0 fromClient:(id)a1;
- (void)logUpdateIdentity:(id)a0 withError:(int)a1;
- (void)logMatchResultIdentity:(id)a0 withDetails:(id)a1 timestamp:(unsigned long long)a2 forClients:(id)a3;
- (void)logCancelFromClient:(id)a0;
- (BOOL)logLogStartSync;
- (id)timeBox;
- (id)_log:(id)a0 withDetails:(id)a1 timestamp:(unsigned long long)a2 fromClient:(id)a3 forClients:(id)a4 endingWithToken:(char *)a5 checkingLogEnd:(BOOL)a6 osLogMsgType:(unsigned char)a7 source:(id)a8 sourceTimestamp:(unsigned long long)a9;
- (void)addImageComment:(id)a0;
- (BOOL)chargerConnected:(BOOL *)a0;
- (void)checkLogEndWithAbsoluteTime:(unsigned long long)a0;
- (void)compactLog;
- (BOOL)createNewLog;
- (BOOL)fileRadarWithLogs:(id)a0 withDescription:(id)a1 andKeywordIDs:(id)a2;
- (id)getLogPath;
- (id)imageFileNameWithTimestamp:(unsigned long long)a0 captureCounter:(unsigned int)a1;
- (id)initToPath:(id)a0 withServerObject:(id)a1 identities:(id)a2 mode:(unsigned char)a3;
- (void)initializeEventSystem;
- (id)log:(id)a0 withDetails:(id)a1 osLogMsgType:(unsigned char)a2 source:(id)a3 sourceTimestamp:(unsigned long long)a4;
- (id)log:(id)a0 withDetails:(id)a1 timestamp:(unsigned long long)a2 forClients:(id)a3 endingWithToken:(char *)a4 osLogMsgType:(unsigned char)a5;
- (id)log:(id)a0 withDetails:(id)a1 timestamp:(unsigned long long)a2 forClients:(id)a3 endingWithToken:(char *)a4 osLogMsgType:(unsigned char)a5 source:(id)a6 sourceTimestamp:(unsigned long long)a7;
- (id)log:(id)a0 withDetails:(id)a1 timestamp:(unsigned long long)a2 fromClient:(id)a3 endingWithToken:(char *)a4 osLogMsgType:(unsigned char)a5;
- (id)log:(id)a0 withDetails:(id)a1 timestamp:(unsigned long long)a2 fromClient:(id)a3 endingWithToken:(char *)a4 osLogMsgType:(unsigned char)a5 source:(id)a6;
- (id)log:(id)a0 withDetails:(id)a1 timestamp:(unsigned long long)a2 osLogMsgType:(unsigned char)a3 source:(id)a4;
- (void)logCalibrationData:(id)a0 withSource:(id)a1;
- (void)logCapture:(id)a0 withTimestamp:(unsigned long long)a1 captureCounter:(unsigned int)a2;
- (void)logError:(id)a0 withDetails:(id)a1 status:(int)a2;
- (void)logImage:(id)a0 withWidth:(unsigned int)a1 height:(unsigned int)a2 timestamp:(unsigned long long)a3 captureCounter:(unsigned int)a4 source:(id)a5;
- (void)logMobileKeyBagLockStatus:(int)a0;
- (id)logNameFromDate:(id)a0;
- (void)logPowerSource:(BOOL)a0 withAbsoluteTime:(unsigned long long)a1 async:(BOOL)a2;
- (void)logPowerSourceStateAsync:(BOOL)a0 initial:(BOOL)a1;
- (void)logPowerStateSync:(BOOL)a0 withTimestamp:(unsigned long long)a1;
- (void)logProtectedConfigurationSync:(id)a0 forUser:(unsigned int)a1 fromClient:(id)a2;
- (void)logSEPTransferData:(id)a0 withTimestamp:(unsigned long long)a1 alsoBinary:(BOOL)a2;
- (void)logStackshotWithErrorCode:(long long)a0;
- (void)logTemplateGraphState:(struct { short x0; short x1; short x2; short x3; short x4; short x5; BOOL x6; struct { short x0; short x1; short x2; short x3; struct { short x0; short x1; short x2; short x3; } x4; } x7; unsigned char x8; unsigned char x9; } *)a0;
- (void)logTemplateList:(id)a0 withIdentity:(id)a1 listingAllIdentitiesForUser:(unsigned int)a2 imageMetadata:(struct { unsigned char x0; unsigned char x1; unsigned char x2; unsigned char x3; unsigned char x4; unsigned int x5; unsigned int x6; unsigned char x7; unsigned char x8; float x9; float x10; float x11; unsigned int x12; unsigned int x13; float x14[5]; unsigned char x15; unsigned char x16; unsigned char x17; unsigned char x18; unsigned long long x19; unsigned int x20; unsigned char x21; unsigned char x22; unsigned char x23; struct { unsigned int x0; unsigned char x1[16]; } x24; float x25; } *)a3;
- (void)logTemplateListWithIdentity:(id)a0 listingAllIdentitiesForUser:(unsigned int)a1;
- (void)logTemplateLists:(id)a0 fromIdentities:(id)a1;
- (void)logTemplateUpdate:(id)a0;
- (void)logTemplateUpdateResult:(id)a0;
- (void)logTopology:(struct { short x0; short x1; short x2; short x3; short x4; short x5; short x6; unsigned char x7[16]; unsigned char x8[16]; short x9; struct { struct { short x0; short x1; short x2; } x0; short x1; short x2; } x10[300]; short x11; short x12; short x13; short x14; short x15; short x16; } *)a0;
- (void)logUnlockedStateSyncWithIdentities:(id)a0;
- (void)noteAssertionFailureWithResultCode:(int)a0;
- (id)stringFromTemplateByIdentity:(id)a0;
- (id)stringFromTemplateListForUser:(unsigned int)a0;
- (void)synchronizeLogFile;
- (void)synchronizeLogFileSync;
- (void)uninitializeEventSystem;

@end
