@class NSDate, NSString, BioLog, NSMutableDictionary, CMWakeGestureManager, NSObject, NSMutableArray, MesaCoreAnalytics, NSMutableData;
@protocol OS_dispatch_queue, OS_dispatch_source;

@interface BiometricKitXPCServerMesa : BiometricKitXPCServer <CMWakeGestureDelegate, NSXPCListenerDelegate> {
    unsigned int _services;
    unsigned int _connect;
    unsigned int _status;
    unsigned short _commProtocolVersion;
    NSMutableDictionary *_cachedImageDB;
    BOOL _showDebugImages;
    NSMutableData *_templListCache;
    long long _enrollmentCount;
    NSDate *_currentDate;
    NSObject<OS_dispatch_queue> *_hidClientQueue;
    struct __IOHIDEventSystemClient { } *_hidClient;
    MesaCoreAnalytics *_statistics;
    struct { unsigned int version; unsigned int structSize; unsigned int sensorType; } _sensorInfo;
    BOOL _hasLegacyCatacomb;
    BOOL _blockHomeButton;
    CMWakeGestureManager *_wakeGestureManager;
    BOOL _autoMatchStartedByHomeButton;
    BOOL _wakeOnMenuPinEnabled;
    BOOL _fingerIsOn;
    BOOL _hidEventFilterCallbackRegistered;
    int _lastSBFingerMsg;
    int _lastSBLockMsg;
    NSMutableArray *_vibrationPatterns;
    BioLog *_log;
    unsigned long long _loggingType;
    NSObject<OS_dispatch_source> *_sigTERMDispatchSource;
    NSObject<OS_dispatch_source> *_dailyUpdateTimer;
}

@property (nonatomic) BOOL sensorReady;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)getSysCfgCalibrationData;

- (id)init;
- (int)getBiometryAvailability:(long long *)a0 forUser:(unsigned int)a1 withClient:(id)a2;
- (long long)getCalibrationDataState;
- (int)performRemoveUserDataCommand:(unsigned int)a0;
- (void)dealloc;
- (id)getLogs:(BOOL)a0 withDetails:(id *)a1;
- (int)diagnostics:(int)a0 withOptions:(id)a1 passed:(BOOL *)a2 withDetails:(id *)a3 withClient:(id)a4;
- (int)initAutoBugCapture;
- (unsigned int)catacombVersion;
- (int)unarchiveCatacombDataForComponent:(id)a0 fromUnarchiver:(id)a1 secureData:(id *)a2 identities:(id *)a3;
- (int)performGetIdentitiesListCommand:(unsigned int)a0 outBuffer:(id)a1;
- (id)getNodeTopologyForIdentity:(id)a0 withClient:(id)a1;
- (id)getSensorInfoWithClient:(id)a0;
- (int)match:(id)a0 withOptions:(id)a1 withClient:(id)a2;
- (void)addIdentityObjects:(id)a0;
- (int)performSaveBioLockoutRecordCommand:(id)a0;
- (int)serviceStatus:(unsigned int)a0 version:(unsigned int)a1 ordinal:(unsigned long long)a2 data:(id)a3 timestamp:(unsigned long long)a4;
- (int)enrollContinue;
- (id)getIdentitiesDatabaseHashForUser:(unsigned int)a0 withClient:(id)a1;
- (int)enroll:(int)a0 forUser:(unsigned int)a1 withOptions:(id)a2 withClient:(id)a3;
- (int)enableBackgroundFdet:(BOOL)a0 withClient:(id)a1;
- (id)getIdentitiesDatabaseUUIDForUser:(unsigned int)a0 withClient:(id)a1;
- (void)enrollResult:(id)a0 withTimestamp:(unsigned long long)a1;
- (void)wakeGestureManager:(id)a0 didUpdateWakeGesture:(long long)a1;
- (int)dropUnlockTokenWithClient:(id)a0;
- (int)performGetProtectedConfigCommand:(unsigned int)a0 outSetCfg:(id *)a1 outEffectiveCfg:(id *)a2;
- (int)loadCatacombForComponent:(id)a0;
- (int)performNoCatacombCommand:(unsigned int)a0;
- (int)performCancelCommand;
- (BOOL)getEnabledForUnlock;
- (int)performGetSKSLockStateCommand:(unsigned int)a0 outState:(unsigned int *)a1;
- (int)performPrepareSaveCatacombCommand:(id)a0 outDataSize:(unsigned int *)a1;
- (int)performSetProtectedConfigCommand:(unsigned int)a0 cfg:(id)a1 authData:(struct { unsigned int x0; unsigned int x1; unsigned char x2[32]; } *)a2;
- (int)removeIdentity:(id)a0 withOptions:(id)a1 withClient:(id)a2;
- (void)disconnectingClient:(id)a0;
- (int)performSetSystemProtectedConfigCommand:(id)a0 authData:(struct { unsigned int x0; unsigned int x1; unsigned char x2[32]; } *)a1;
- (int)forceBioLockoutForUser:(unsigned int)a0 withOptions:(id)a1 withClient:(id)a2;
- (void)clearTemplateList;
- (int)initEnrollOperation:(id)a0 biometricType:(int)a1 userID:(unsigned int)a2 options:(id)a3 client:(id)a4;
- (int)performCompleteSaveCatacombCommand:(id)a0 outBuffer:(id)a1;
- (int)performGetSystemProtectedConfigCommand:(id *)a0;
- (int)performGetCatacombUUIDCommand:(unsigned int)a0 outUUID:(id *)a1;
- (long long)getMaxIdentityCount:(int)a0 withClient:(id)a1;
- (int)getCatacombSaveListForComponents:(id)a0 list:(id *)a1;
- (int)performMatchCommand:(id)a0;
- (int)updateIdentity:(id)a0 withOptions:(id)a1 withClient:(id)a2;
- (void)statusMessage:(unsigned int)a0 withData:(id)a1 timestamp:(unsigned long long)a2;
- (int)detectPresenceWithOptions:(id)a0 withClient:(id)a1;
- (int)setProtectedConfiguration:(id)a0 forUser:(unsigned int)a1 withOptions:(id)a2 withClient:(id)a3;
- (id)pullCalibrationDataWithClient:(id)a0;
- (int)setAppleMesaSEPLoggingLevel;
- (int)performGetBiometrickitdInfoCommand:(struct { unsigned int x0; unsigned int x1; unsigned int x2; unsigned long long x3; unsigned char x4; unsigned char x5; unsigned char x6; } *)a0;
- (long long)getSensorCalibrationStatusWithClient:(id)a0;
- (int)performGetCatacombHashCommand:(unsigned int)a0 outHash:(id *)a1;
- (void)registerDelegate:(BOOL)a0 withClient:(id)a1;
- (int)setSystemProtectedConfiguration:(id)a0 withOptions:(id)a1 withClient:(id)a2;
- (void)touchIDButtonPressed:(BOOL)a0;
- (int)performPresenceDetectCommand:(id)a0;
- (int)performDropUnlockTokenCommand;
- (id)pullDebugImageData:(BOOL)a0 rotated:(BOOL)a1 hasWidth:(unsigned int *)a2 hasHeight:(unsigned int *)a3 withClient:(id)a4;
- (id)getProtectedConfigurationForUser:(unsigned int)a0 withClient:(id)a1;
- (long long)getFreeIdentityCount:(int)a0 forUser:(unsigned int)a1 withClient:(id)a2;
- (int)performDisplayStatusChangedCommand:(BOOL)a0;
- (int)performGetFreeIdentityCountCommand:(unsigned int)a0 outCount:(unsigned int *)a1;
- (void).cxx_destruct;
- (int)saveCatacomb;
- (BOOL)isFingerOnWithClient:(id)a0;
- (int)performRequestMaxIdentityCountCommand:(unsigned int *)a0;
- (long long)getCalBlobVersion;
- (float)getModulationRatio;
- (id)pullAlignmentData;
- (void)deleteUnusedCatacombFiles;
- (BOOL)fileRadarWithLogs:(id)a0 withDescription:(id)a1;
- (int)archiveCatacombDataForComponent:(id)a0 toArchiver:(id)a1;
- (int)saveCatacombForComponents:(id)a0;
- (BOOL)templatesExistAtBoot;
- (BOOL)isXARTAvailableWithClient:(id)a0;
- (id)identities:(id)a0 withClient:(id)a1;
- (int)removeAllIdentitiesForUser:(unsigned int)a0 withOptions:(id)a1 withClient:(id)a2;
- (int)performLoadBioLockoutRecordCommand:(id)a0;
- (long long)getProvisioningStateWithClient:(id)a0;
- (int)initMatchOperation:(id)a0 filter:(id)a1 options:(id)a2 client:(id)a3;
- (int)performEnrollCommand:(id)a0;
- (int)performGetCatacombStateCommand:(id)a0;
- (int)getLastMatchEvent:(id *)a0 withClient:(id)a1;
- (int)performGetLastMatchEventCommand:(struct { unsigned long long x0; unsigned char x1; struct { unsigned int x0; unsigned char x1[16]; } x2; } *)a0;
- (void)homeButtonPressed;
- (id)getCalibrationDataInfoWithClient:(id)a0;
- (id)getIdentityFromUUID:(id)a0 withClient:(id)a1;
- (id)pullCaptureBufferWithClient:(id)a0;
- (int)performRemoveIdentityCommand:(struct { unsigned int x0; unsigned char x1[16]; } *)a0;
- (int)performForceBioLockoutCommand:(unsigned int)a0;
- (int)getBioLockoutState:(long long *)a0 forUser:(unsigned int)a1 withClient:(id)a2;
- (id)getSystemProtectedConfigurationWithClient:(id)a0;
- (int)performLoadCatacombCommand:(id)a0 inData:(id)a1;
- (void)clearTemplateListForUser:(unsigned int)a0;
- (int)restoreAndSyncTemplates;
- (int)loadCatacomb;
- (void)removeIdentityObject:(id)a0;
- (void)notifyAppIsInactive:(BOOL)a0 withClient:(id)a1;
- (int)cancelWithClient:(id)a0;
- (int)setDebugImages:(BOOL)a0 withClient:(id)a1;
- (void)timestampEvent:(unsigned long long)a0 absoluteTime:(unsigned long long)a1;
- (int)performConfirmSaveCatacombCommand:(id)a0;
- (void)matchResult:(id)a0 timestamp:(unsigned long long)a1;
- (void)sendStatusMessage:(unsigned int)a0 toClient:(id)a1;
- (int)performGetTemplatesValidityCommand:(unsigned int)a0 isValid:(BOOL *)a1;
- (int)performRequestMessageDataCommand:(unsigned long long)a0 size:(unsigned long long)a1 outData:(id *)a2;
- (id)createMatchOperation;
- (int)cacheSensorInfo;
- (void)cacheImageDB:(struct { unsigned char x0; unsigned char x1; unsigned char x2; unsigned char x3; unsigned char x4; unsigned int x5; unsigned int x6; unsigned char x7; unsigned char x8; float x9; float x10; float x11; unsigned int x12; unsigned int x13; float x14[5]; unsigned char x15; unsigned char x16; unsigned char x17; unsigned char x18; unsigned long long x19; unsigned int x20; unsigned char x21; unsigned char x22; unsigned char x23; struct { unsigned int x0; unsigned char x1[16]; } x24; float x25; } *)a0;
- (int)cachePatch;
- (void)checkDailyUpdate;
- (int)checkSensorReadiness;
- (int)decodeCatacombDataV1:(char *)a0 withSize:(unsigned long long)a1;
- (void)disableHomeButton:(BOOL)a0;
- (void)dumpSyslog;
- (void)dumpSyslogWithDelay:(double)a0;
- (int)getCommProtocolVersion;
- (int)getDataFromDriverCommand:(unsigned char)a0 value:(unsigned char)a1 data:(char *)a2 size:(unsigned long long)a3;
- (id)getEEPROMCalibrationData;
- (long long)getEnrollmentCount;
- (id)getFDRCalibrationData;
- (unsigned long long)getLoggingType;
- (id)getModuleSerialNumber;
- (id)getRemoteFDRCalibrationData;
- (unsigned long long)getSensorType;
- (id)getSerialisedTemplatesForUser:(unsigned int)a0;
- (id)getSyslog;
- (id)getSyslogArray;
- (id)getSyslogForQuery:(struct __asl_object_s { } *)a0 withFilter:(id /* block */)a1;
- (int)getTimestampCollection:(struct { unsigned long long x0; unsigned long long x1; unsigned long long x2; unsigned long long x3; unsigned long long x4; unsigned long long x5; unsigned long long x6; unsigned char x7; } *)a0;
- (int)initSensor;
- (BOOL)isBaseSystem;
- (int)loadCalibrationData;
- (void)matchEventMessage:(struct { unsigned long long x0; unsigned char x1; struct { unsigned int x0; unsigned char x1[16]; } x2; } *)a0;
- (int)performCommand:(unsigned short)a0 inValue:(unsigned short)a1 inData:(const void *)a2 inSize:(unsigned long long)a3 outData:(char *)a4 outSize:(unsigned long long *)a5;
- (int)performCommand:(unsigned short)a0 version:(unsigned short)a1 inValue:(unsigned short)a2 inData:(const void *)a3 inSize:(unsigned long long)a4 outData:(char *)a5 outSize:(unsigned long long *)a6;
- (void)registerForLiftToWakeNotifications:(BOOL)a0;
- (void)resetContinuousCounters;
- (int)resetSensor;
- (int)restoreTemplateListSU;
- (int)setCalibrationData:(id)a0 source:(int)a1;
- (int)setIORegistryProperty:(id)a0 toValue:(id)a1 onService:(id)a2;
- (void)setupDailyUpdateTimer;
- (BOOL)shouldFilterStatusForSB:(unsigned int)a0;
- (unsigned long long)sizeOfLegacyCatacomb;
- (void)statisticsMessage:(struct { unsigned int x0; union { long long x0; double x1; } x1; } *)a0;
- (int)systemSleepStateChanged:(BOOL)a0;
- (void)templateUpdateMessage:(struct { struct { unsigned int x0; unsigned char x1[16]; } x0; unsigned int x1; struct { short x0; short x1; short x2; struct { short x0; short x1; short x2; } x3; struct { short x0; short x1; short x2; short x3; short x4; short x5; short x6; unsigned char x7[16]; unsigned char x8[16]; short x9; struct { struct { short x0; short x1; short x2; } x0; short x1; short x2; } x10[300]; short x11; short x12; short x13; short x14; short x15; short x16; } x4; int x5; int x6; } x2; struct { unsigned char x0; unsigned char x1; unsigned char x2; unsigned char x3; unsigned char x4; unsigned int x5; unsigned int x6; unsigned char x7; unsigned char x8; float x9; float x10; float x11; unsigned int x12; unsigned int x13; float x14[5]; unsigned char x15; unsigned char x16; unsigned char x17; unsigned char x18; unsigned long long x19; unsigned int x20; unsigned char x21; unsigned char x22; unsigned char x23; struct { unsigned int x0; unsigned char x1[16]; } x24; float x25; } x3; } *)a0;
- (void)updateBioLogState;
- (void)updateImageDB:(id)a0 templateUpdateInfo:(const struct { struct { unsigned int x0; unsigned char x1[16]; } x0; unsigned int x1; struct { short x0; short x1; short x2; struct { short x0; short x1; short x2; } x3; struct { short x0; short x1; short x2; short x3; short x4; short x5; short x6; unsigned char x7[16]; unsigned char x8[16]; short x9; struct { struct { short x0; short x1; short x2; } x0; short x1; short x2; } x10[300]; short x11; short x12; short x13; short x14; short x15; short x16; } x4; int x5; int x6; } x2; struct { unsigned char x0; unsigned char x1; unsigned char x2; unsigned char x3; unsigned char x4; unsigned int x5; unsigned int x6; unsigned char x7; unsigned char x8; float x9; float x10; float x11; unsigned int x12; unsigned int x13; float x14[5]; unsigned char x15; unsigned char x16; unsigned char x17; unsigned char x18; unsigned long long x19; unsigned int x20; unsigned char x21; unsigned char x22; unsigned char x23; struct { unsigned int x0; unsigned char x1[16]; } x24; float x25; } x3; } *)a1;
- (void)vibrate:(long long)a0;

@end
