@class NSNumber;

@interface MesaCoreAnalyticsDailyEvent : MesaCoreAnalyticsEvent

@property (retain) NSNumber *unlockEnabled;
@property (retain) NSNumber *applePayEnabled;
@property (retain) NSNumber *badDay;
@property (retain) NSNumber *operationTimeAverage;
@property (retain) NSNumber *matcherTimeAverage;
@property (retain) NSNumber *matcherTimeMatchAverage;
@property (retain) NSNumber *matcherTimeNoMatchAverage;
@property (retain) NSNumber *captureTimeAverage;
@property (retain) NSNumber *enrolledIdentityCount;
@property (retain) NSNumber *enrolledUserCount;
@property (retain) NSNumber *bioLockoutCount;
@property (retain) NSNumber *totalMatchAttempts;
@property (retain) NSNumber *totalMatchAttemptsSuccessful;
@property (retain) NSNumber *totalMatchAttemptsFailed;
@property (retain) NSNumber *totalMatchAttemptsFingerDetected;
@property (retain) NSNumber *totalMatchAttemptsFailedFingerDetected;
@property (retain) NSNumber *unlockMatchAttempts;
@property (retain) NSNumber *unlockMatchAttemptsSuccessful;
@property (retain) NSNumber *unlockMatchAttemptsFailed;
@property (retain) NSNumber *unlockMatchAttemptsFingerDetected;
@property (retain) NSNumber *unlockMatchAttemptsFailedFingerDetected;
@property (retain) NSNumber *localAuthMatchAttempts;
@property (retain) NSNumber *localAuthMatchAttemptsSuccessful;
@property (retain) NSNumber *localAuthMatchAttemptsFailed;
@property (retain) NSNumber *localAuthMatchAttemptsFingerDetected;
@property (retain) NSNumber *localAuthMatchAttemptsFailedFingerDetected;
@property (retain) NSNumber *preArmMatchAttempts;
@property (retain) NSNumber *preArmMatchAttemptsSuccessful;
@property (retain) NSNumber *preArmMatchAttemptsFailed;
@property (retain) NSNumber *preArmMatchAttemptsFingerDetected;
@property (retain) NSNumber *preArmMatchAttemptsFailedFingerDetected;
@property (retain) NSNumber *templateEnrollmentsCount;
@property (retain) NSNumber *totalMatchOperationsFingerDetected;
@property (retain) NSNumber *totalMatchOperationsFailedRetry;
@property (retain) NSNumber *subsetMatchAttempts;
@property (retain) NSNumber *subsetMatchAttemptsSuccessful;
@property (retain) NSNumber *subsetMatchAttemptsFailed;
@property (retain) NSNumber *subsetMatchAttemptsFingerDetected;
@property (retain) NSNumber *subsetMatchAttemptsFailedFingerDetected;
@property (retain) NSNumber *subsetMatchAttemptsFailedTarget;
@property (retain) NSNumber *totalScanGroupCount;
@property (retain) NSNumber *totalScanCount;
@property (retain) NSNumber *nonArtefactMatchAttempts;
@property (retain) NSNumber *nonArtefactMatchAttemptsSuccessful;
@property (retain) NSNumber *nonArtefactMatchAttemptsFailed;
@property (retain) NSNumber *nonArtefactMatchAttemptsFingerDetected;
@property (retain) NSNumber *nonArtefactMatchAttemptsFailedFingerDetected;
@property (retain) NSNumber *artefactMatchAttempts;
@property (retain) NSNumber *artefactMatchAttemptsSuccessful;
@property (retain) NSNumber *artefactMatchAttemptsFailed;
@property (retain) NSNumber *artefactMatchAttemptsFingerDetected;
@property (retain) NSNumber *artefactMatchAttemptsFailedFingerDetected;
@property (retain) NSNumber *totalFRR;
@property (retain) NSNumber *unlockFRR;
@property (retain) NSNumber *prearmFRR;
@property (retain) NSNumber *localAuthFRR;
@property (retain) NSNumber *badDayFRR;
@property (retain) NSNumber *subsetFRR;
@property (retain) NSNumber *subsetTargetFRR;
@property (retain) NSNumber *subsetMatchFRR;
@property (retain) NSNumber *nonArtefactFRR;
@property (retain) NSNumber *artefactFRR;
@property (retain) NSNumber *drxStrengthPctCol2Bin;
@property (retain) NSNumber *drxStrengthPctCol7Bin;
@property (retain) NSNumber *drxStrengthPctCol2BinAverage;
@property (retain) NSNumber *drxStrengthPctCol7BinAverage;
@property (retain) NSNumber *temperatureBin;
@property (retain) NSNumber *FMRBin;
@property (retain) NSNumber *BSRBin;
@property (retain) NSNumber *fitDiffBin;
@property (retain) NSNumber *carrierAttenBin;
@property (retain) NSNumber *DRXAmpMinBin;
@property (retain) NSNumber *DRXAmpMaxBin;
@property (retain) NSNumber *fitResEdge6SigmaBin;
@property (retain) NSNumber *imagePixelOutlierCountAverage;
@property (retain) NSNumber *numPxOutliersPhase1Average;
@property (retain) NSNumber *numPxOutliersPhase2Average;
@property (retain) NSNumber *artefactScoreAverage;
@property (retain) NSNumber *maxFingerToProbeAttenuationMax;
@property (retain) NSNumber *maxFingerToProbeAttenuationMin;
@property (retain) NSNumber *maxFingerToProbeAttenuationAverage;
@property (retain) NSNumber *drxStrengthPctCol2Raw;
@property (retain) NSNumber *drxStrengthPctCol7Raw;
@property (retain) NSNumber *drxStrengthPctCol2RawAverage;
@property (retain) NSNumber *drxStrengthPctCol7RawAverage;
@property (retain) NSNumber *temperatureRaw;
@property (retain) NSNumber *FMRRaw;
@property (retain) NSNumber *BSRRaw;
@property (retain) NSNumber *fitDiffRaw;
@property (retain) NSNumber *carrierAttenRaw;
@property (retain) NSNumber *DRXAmpMinRaw;
@property (retain) NSNumber *DRXAmpMaxRaw;
@property (retain) NSNumber *fitResEdge6SigmaRaw;
@property (retain) NSNumber *artefactPrevalence;
@property (retain) NSNumber *artefactStrengthAverage;
@property (retain) NSNumber *artefactNonlinearityAverage;
@property (retain) NSNumber *artefactNonlinearitySTD;
@property (retain) NSNumber *artefactAnchorXAverage;
@property (retain) NSNumber *artefactAnchorXSTD;
@property (retain) NSNumber *artefactAnchorYAverage;
@property (retain) NSNumber *artefactAnchorYSTD;
@property (retain) NSNumber *lastEnrollmentTouchesCount;
@property (retain) NSNumber *lastEnrollmentScanCount;
@property (retain) NSNumber *lastEnrollmentScanGroupCount;
@property (retain) NSNumber *lastEnrollmentDeviceOrientation;
@property (retain, nonatomic) NSNumber *timeSinceSecondLastEnrollment;
@property (retain) NSNumber *timeSinceSecondLastEnrollmentBinned;
@property (readonly) NSNumber *operationCount;
@property (readonly) NSNumber *operationTimeSum;
@property (readonly) NSNumber *matcherTimeCount;
@property (readonly) NSNumber *matcherTimeSum;
@property (readonly) NSNumber *matcherTimeMatchCount;
@property (readonly) NSNumber *matcherTimeMatchSum;
@property (readonly) NSNumber *matcherTimeNoMatchCount;
@property (readonly) NSNumber *matcherTimeNoMatchSum;
@property (readonly) NSNumber *captureTimeCount;
@property (readonly) NSNumber *captureTimeSum;
@property (readonly) NSNumber *drxStrengthPctCol2BinCount;
@property (readonly) NSNumber *drxStrengthPctCol2BinSum;
@property (readonly) NSNumber *drxStrengthPctCol7BinCount;
@property (readonly) NSNumber *drxStrengthPctCol7BinSum;
@property (readonly) NSNumber *drxStrengthPctCol2RawCount;
@property (readonly) NSNumber *drxStrengthPctCol2RawSum;
@property (readonly) NSNumber *drxStrengthPctCol7RawCount;
@property (readonly) NSNumber *drxStrengthPctCol7RawSum;
@property (readonly) NSNumber *maxFingerToProbeAttenuationCount;
@property (readonly) NSNumber *maxFingerToProbeAttenuationSum;
@property (readonly) NSNumber *imagePixelOutlierCountCount;
@property (readonly) NSNumber *imagePixelOutlierCountSum;
@property (readonly) NSNumber *numPxOutliersPhase1Count;
@property (readonly) NSNumber *numPxOutliersPhase1Sum;
@property (readonly) NSNumber *numPxOutliersPhase2Count;
@property (readonly) NSNumber *numPxOutliersPhase2Sum;
@property (readonly) NSNumber *artefactScoreCount;
@property (readonly) NSNumber *artefactScoreSum;
@property (readonly) NSNumber *artefactStrengthCount;
@property (readonly) NSNumber *artefactStrengthSum;
@property (readonly) NSNumber *artefactNonlinearityCount;
@property (readonly) NSNumber *artefactNonlinearityM2;
@property (readonly) NSNumber *artefactAnchorXCount;
@property (readonly) NSNumber *artefactAnchorXM2;
@property (readonly) NSNumber *artefactAnchorYCount;
@property (readonly) NSNumber *artefactAnchorYM2;

- (void)reset;
- (id)initWithDictionary:(id)a0;
- (void).cxx_destruct;
- (id)dictionaryRepresentationArchiving:(BOOL)a0;
- (id)initWithName:(id)a0 dictionary:(id)a1;
- (void)setCaptureTime:(id)a0;
- (void)setDrxStrengthPctCol7:(id)a0 rawValue:(id)a1;
- (void)setDrxStrengthPctCol2:(id)a0 rawValue:(id)a1;
- (void)setMatcherTime:(id)a0;
- (void)calculateDailyValues;
- (BOOL)isBadDay;
- (void)setArtefactAnchorX:(id)a0;
- (void)setArtefactAnchorY:(id)a0;
- (void)setArtefactNonlinearity:(id)a0;
- (void)setArtefactScore:(id)a0;
- (void)setArtefactStrength:(id)a0;
- (void)setImagePixelOutlierCount:(id)a0;
- (void)setMatcherTimeMatch:(id)a0;
- (void)setMatcherTimeNoMatch:(id)a0;
- (void)setMaxFingerToProbeAttenuation:(id)a0 calculateAvg:(BOOL)a1;
- (void)setNumPxOutliersPhase1:(id)a0;
- (void)setNumPxOutliersPhase2:(id)a0;
- (void)setOperationTime:(id)a0;

@end
