@class NSUUID, BiometricMatchOperationMesa, NSNumber, NSMutableArray;

@interface MesaCoreAnalyticsMatchEvent : MesaCoreAnalyticsEvent {
    BOOL _valid;
    BOOL _waitingForMatchResult;
    BOOL _acceptPrev;
    unsigned char _lastAcceptCondFeedback;
    NSMutableArray *_targetTemplateUUID;
    NSUUID *_matchingTemplateUUID;
    unsigned long long _buttonStateCount;
}

@property (retain) NSNumber *matcherResult;
@property (retain) NSNumber *matchMode;
@property (retain) NSNumber *matchUseCase;
@property (retain) NSNumber *matchType;
@property (retain) NSNumber *tidButtonState;
@property (retain) NSNumber *imageProblemClass;
@property (retain) NSNumber *deviceWakeReason;
@property (retain) NSNumber *sensorModulationRatio;
@property (retain) NSNumber *imagePixelOutlierCount;
@property (retain) NSNumber *imageContrast;
@property (retain) NSNumber *imageBrightness;
@property (retain) NSNumber *imageFeatureStrength;
@property (retain) NSNumber *imageContrastNorm;
@property (retain) NSNumber *imageBrightnessNorm;
@property (retain) NSNumber *imageFeatureStrengthNorm;
@property (retain, nonatomic) NSNumber *sensorRecoveryReason;
@property (retain) NSNumber *drxStrengthPctCol2Bin;
@property (retain) NSNumber *drxStrengthPctCol7Bin;
@property (retain) NSNumber *temperatureBin;
@property (retain) NSNumber *maxFingerToProbeAttenuationBin;
@property (retain) NSNumber *FMRBin;
@property (retain) NSNumber *BSRBin;
@property (retain) NSNumber *fitDiffBin;
@property (retain) NSNumber *carrierAttenBin;
@property (retain) NSNumber *DRXAmpMinBin;
@property (retain) NSNumber *DRXAmpMaxBin;
@property (retain) NSNumber *fitResEdge6SigmaBin;
@property (retain) NSNumber *tidButtonStateSequenceBounded;
@property (retain) NSNumber *artefactDetectionResult;
@property (retain) NSNumber *artefactScore;
@property (retain) NSNumber *numPxOutliersPhase1;
@property (retain) NSNumber *numPxOutliersPhase2;
@property (retain) NSNumber *overallResult;
@property (retain) NSNumber *wakeOnMenuPinUsed;
@property (retain) NSNumber *templateUpdated;
@property (retain) NSNumber *dirtOnSensor;
@property (retain) NSNumber *pressureMitigationUsed;
@property (retain) NSNumber *desenseMitigationPause;
@property (retain) NSNumber *bioLockout;
@property (retain) NSNumber *requestFingerOff;
@property (retain) NSNumber *preArmedMatch;
@property (retain) NSNumber *captureRestartCount;
@property (retain) NSNumber *capturedImageCount;
@property (retain) NSNumber *acceptedImageCount;
@property (retain) NSNumber *rejectedImageCount;
@property (retain) NSNumber *rejectedImageUnknownCount;
@property (retain) NSNumber *rejectedImageBadBlocksCount;
@property (retain) NSNumber *rejectedImageChFPNCount;
@property (retain) NSNumber *rejectedImageCaFPNCount;
@property (retain) NSNumber *rejectedImageMovementCount;
@property (retain) NSNumber *enrolledUsersCount;
@property (retain) NSNumber *matchIdentityCount;
@property (retain) NSNumber *failedUnlockAttempts;
@property (retain) NSNumber *failedMatchAttempts;
@property (retain) NSNumber *quickTapsCount;
@property (retain) NSNumber *sensorResetCount;
@property (retain) NSNumber *overallTime;
@property (retain) NSNumber *operationStartTime;
@property (retain) NSNumber *fingerDetectEndTime;
@property (retain) NSNumber *firstCaptureEndTime;
@property (retain) NSNumber *imageProcessingEndTime;
@property (retain) NSNumber *matcherEndTime;
@property (retain, nonatomic) NSNumber *captureTime;
@property (retain, nonatomic) NSNumber *imageProcessingTime;
@property (retain) NSNumber *matcherTime;
@property (retain) NSNumber *timeSinceSleep;
@property (retain) NSNumber *requestFingerOffEndTime;
@property (retain) NSNumber *overallTimeFingerOn;
@property (retain) NSNumber *imageDecryptionTime;
@property (retain) NSNumber *imageTransferTime;
@property (retain) NSNumber *firstCaptureEndTimeToFirstMatcherEndTime;
@property (retain) NSNumber *matcherEndTimeWithRetry;
@property (retain) NSNumber *matcherTimeWithRetry;
@property (retain) NSNumber *targetTemplate;
@property (retain) NSNumber *targetTemplateMatchCount;
@property (retain) NSNumber *targetTemplateUsageDaily;
@property (retain) NSNumber *targetTemplateMatchCountContinuous;
@property (retain) NSNumber *targetTemplateUsage;
@property (retain) NSNumber *matchingTemplateMatchCount;
@property (retain) NSNumber *matchingTemplateUsageDaily;
@property (retain) NSNumber *matchingTemplateUsage;
@property (retain) NSNumber *matchingTemplateMatchCountContinuous;
@property (retain) NSNumber *sensorModulationRatioRaw;
@property (retain) NSNumber *maxFingerToProbeAttenuationRaw;
@property (retain) NSNumber *drxStrengthPctCol2Raw;
@property (retain) NSNumber *drxStrengthPctCol7Raw;
@property (retain) NSNumber *temperatureRaw;
@property (retain) NSNumber *FMRRaw;
@property (retain) NSNumber *BSRRaw;
@property (retain) NSNumber *fitDiffRaw;
@property (retain) NSNumber *carrierAttenRaw;
@property (retain) NSNumber *DRXAmpMinRaw;
@property (retain) NSNumber *DRXAmpMaxRaw;
@property (retain) NSNumber *fitResEdge6SigmaRaw;
@property (retain) NSNumber *artefactStrength;
@property (retain) NSNumber *artefactNonlinearity;
@property (retain) NSNumber *artefactAnchorX;
@property (retain) NSNumber *artefactAnchorY;
@property (retain) NSNumber *tidButtonStateSequence;
@property (retain) BiometricMatchOperationMesa *matchOperation;
@property (retain) NSNumber *imageAbsoluteTimeId;

- (id)init;
- (void)reset;
- (id)initWithName:(id)a0;
- (id)initWithDictionary:(id)a0;
- (void).cxx_destruct;
- (void)setEventCanceled:(id)a0;
- (void)setMatchCountsFromIdentityList:(id)a0;
- (void)acceptPreviousImage;
- (void)handleStatusMessage:(unsigned int)a0 withData:(id)a1;
- (BOOL)postEventAndUpdateDailyValues:(id)a0 enrolledIdentities:(id)a1;
- (void)receiveImage:(id)a0;
- (void)setMatchModeWith:(long long)a0;
- (void)setMatchResult:(id)a0 withDetails:(id)a1;
- (void)setMatchTypeWith:(id)a0;
- (void)setSensorModulationRatioWith:(float)a0;
- (void)setTargetTemplates:(id)a0;
- (void)setTidButtonStateWith:(long long)a0;
- (void)updateDailyValuesAfterMatch:(id)a0;

@end
