@class NSString;

@interface AWDThroughputEvaluation : PBCodable <NSCopying> {
    struct { unsigned char wifiRssi : 1; unsigned char actualHighBandwidth : 1; unsigned char actualLowBandwidth : 1; unsigned char badDecisionsCounterVIBE : 1; unsigned char badDecisionsCounterVO : 1; unsigned char bcnPer : 1; unsigned char btRssi : 1; unsigned char btWiFiCoexState : 1; unsigned char bufferInterval : 1; unsigned char cca : 1; unsigned char cellARFCN : 1; unsigned char cellBandInfo : 1; unsigned char cellChannelBW : 1; unsigned char cellEstimatedBW : 1; unsigned char cellLteRSRQ : 1; unsigned char cellModelConfidenceLevel : 1; unsigned char cellModelVersion : 1; unsigned char cellNrRSRP : 1; unsigned char cellNrRSRQ : 1; unsigned char cellNrSNR : 1; unsigned char cellRsrp : 1; unsigned char cellSinr : 1; unsigned char cmDataSentCount : 1; unsigned char cmDataSentDuration : 1; unsigned char cmEstimatedBandwidth : 1; unsigned char coldStartType : 1; unsigned char decisionVIBE : 1; unsigned char decisionVO : 1; unsigned char deviation : 1; unsigned char devicePointOfInterest : 1; unsigned char estimatedHighBandwidth : 1; unsigned char estimatedLowBandwidth : 1; unsigned char estimatedSpeed : 1; unsigned char event : 1; unsigned char expectedThroughputVIBE : 1; unsigned char expectedThroughputVO : 1; unsigned char goodDecisionsCounterVIBE : 1; unsigned char goodDecisionsCounterVO : 1; unsigned char invalidDecisionsCounterVIBE : 1; unsigned char invalidDecisionsCounterVO : 1; unsigned char isWfiCaptive : 1; unsigned char lqmScoreBT : 1; unsigned char lqmScoreWifi : 1; unsigned char lqmScorecellular : 1; unsigned char lteMaxScheduledMimoLayersInACell : 1; unsigned char maxDLCAConfigured : 1; unsigned char maxOfActualLowBandwidth : 1; unsigned char maxULCAConfigured : 1; unsigned char mlPredictedCellBW : 1; unsigned char mlPredictedWiFiBW : 1; unsigned char movingAvgHighBandwidth : 1; unsigned char movingAvgLowBandwidth : 1; unsigned char nrConfiguredBw : 1; unsigned char nrMaxDlModulation : 1; unsigned char nrTotalScheduledMimoLayers : 1; unsigned char pActualLowBandwidth : 1; unsigned char packetLifetimeVIBE : 1; unsigned char packetLossRateVIBE : 1; unsigned char phyRate : 1; unsigned char pkgLifeTimeVO : 1; unsigned char pktLifeTimeVO : 1; unsigned char pktLossRateVO : 1; unsigned char qbssLoad : 1; unsigned char ratioDupeBytes : 1; unsigned char ratioOOBBytes : 1; unsigned char rrcState : 1; unsigned char rxRetransmissionRate : 1; unsigned char rxRetry : 1; unsigned char tcpRTTAvg : 1; unsigned char tcpRTTmin : 1; unsigned char tcpRTTvar : 1; unsigned char totalConfiguredBw : 1; unsigned char totalConfiguredMimoLayers : 1; unsigned char txRetransmissionRate : 1; unsigned char txber : 1; unsigned char videoStreamingStallTime : 1; unsigned char weightedAveragePhyrateRx : 1; unsigned char weightedAveragePhyrateTx : 1; unsigned char weightedAverageRssi : 1; unsigned char weightedAverageSnr : 1; unsigned char wifChannelBW : 1; unsigned char wifChannelType : 1; unsigned char wifiCapability : 1; unsigned char wifiModelConfidenceLevel : 1; unsigned char wifiModelVersion : 1; unsigned char wifiSinr : 1; unsigned char wifichannel : 1; unsigned char wifiguardinterval : 1; unsigned char wifilowDataMode : 1; unsigned char wifimcsindex : 1; unsigned char wifinumberOfSpatialStreams : 1; unsigned char wrmRecommendedRAT : 1; unsigned char cellNsaEnabled : 1; unsigned char isFR1 : 1; } _has;
}

@property (nonatomic) BOOL hasEvent;
@property (nonatomic) unsigned int event;
@property (nonatomic) BOOL hasBufferInterval;
@property (nonatomic) unsigned int bufferInterval;
@property (nonatomic) BOOL hasWifiRssi;
@property (nonatomic) long long wifiRssi;
@property (nonatomic) BOOL hasPhyRate;
@property (nonatomic) unsigned int phyRate;
@property (nonatomic) BOOL hasQbssLoad;
@property (nonatomic) unsigned int qbssLoad;
@property (nonatomic) BOOL hasCca;
@property (nonatomic) unsigned int cca;
@property (nonatomic) BOOL hasBcnPer;
@property (nonatomic) unsigned int bcnPer;
@property (nonatomic) BOOL hasExpectedThroughputVO;
@property (nonatomic) unsigned int expectedThroughputVO;
@property (nonatomic) BOOL hasWifiSinr;
@property (nonatomic) int wifiSinr;
@property (nonatomic) BOOL hasPktLifeTimeVO;
@property (nonatomic) unsigned int pktLifeTimeVO;
@property (nonatomic) BOOL hasPktLossRateVO;
@property (nonatomic) unsigned int pktLossRateVO;
@property (nonatomic) BOOL hasLqmScoreWifi;
@property (nonatomic) int lqmScoreWifi;
@property (nonatomic) BOOL hasPacketLossRateVIBE;
@property (nonatomic) unsigned int packetLossRateVIBE;
@property (nonatomic) BOOL hasExpectedThroughputVIBE;
@property (nonatomic) unsigned int expectedThroughputVIBE;
@property (nonatomic) BOOL hasPacketLifetimeVIBE;
@property (nonatomic) unsigned int packetLifetimeVIBE;
@property (nonatomic) BOOL hasBadDecisionsCounterVO;
@property (nonatomic) unsigned int badDecisionsCounterVO;
@property (nonatomic) BOOL hasGoodDecisionsCounterVO;
@property (nonatomic) unsigned int goodDecisionsCounterVO;
@property (nonatomic) BOOL hasInvalidDecisionsCounterVO;
@property (nonatomic) unsigned int invalidDecisionsCounterVO;
@property (nonatomic) BOOL hasBadDecisionsCounterVIBE;
@property (nonatomic) unsigned int badDecisionsCounterVIBE;
@property (nonatomic) BOOL hasGoodDecisionsCounterVIBE;
@property (nonatomic) unsigned int goodDecisionsCounterVIBE;
@property (nonatomic) BOOL hasInvalidDecisionsCounterVIBE;
@property (nonatomic) unsigned int invalidDecisionsCounterVIBE;
@property (nonatomic) BOOL hasLqmScorecellular;
@property (nonatomic) int lqmScorecellular;
@property (readonly, nonatomic) BOOL hasRatType;
@property (retain, nonatomic) NSString *ratType;
@property (nonatomic) BOOL hasCellRsrp;
@property (nonatomic) int cellRsrp;
@property (nonatomic) BOOL hasCellSinr;
@property (nonatomic) int cellSinr;
@property (nonatomic) BOOL hasBtRssi;
@property (nonatomic) int btRssi;
@property (nonatomic) BOOL hasTxRetransmissionRate;
@property (nonatomic) unsigned int txRetransmissionRate;
@property (nonatomic) BOOL hasRxRetransmissionRate;
@property (nonatomic) unsigned int rxRetransmissionRate;
@property (nonatomic) BOOL hasLqmScoreBT;
@property (nonatomic) int lqmScoreBT;
@property (nonatomic) BOOL hasWrmRecommendedRAT;
@property (nonatomic) unsigned int wrmRecommendedRAT;
@property (nonatomic) BOOL hasActualLowBandwidth;
@property (nonatomic) unsigned int actualLowBandwidth;
@property (nonatomic) BOOL hasActualHighBandwidth;
@property (nonatomic) unsigned int actualHighBandwidth;
@property (nonatomic) BOOL hasEstimatedLowBandwidth;
@property (nonatomic) unsigned int estimatedLowBandwidth;
@property (nonatomic) BOOL hasEstimatedHighBandwidth;
@property (nonatomic) unsigned int estimatedHighBandwidth;
@property (nonatomic) BOOL hasMovingAvgLowBandwidth;
@property (nonatomic) unsigned int movingAvgLowBandwidth;
@property (nonatomic) BOOL hasMovingAvgHighBandwidth;
@property (nonatomic) unsigned int movingAvgHighBandwidth;
@property (nonatomic) BOOL hasDeviation;
@property (nonatomic) int deviation;
@property (nonatomic) BOOL hasMaxOfActualLowBandwidth;
@property (nonatomic) unsigned int maxOfActualLowBandwidth;
@property (nonatomic) BOOL hasPkgLifeTimeVO;
@property (nonatomic) unsigned int pkgLifeTimeVO;
@property (nonatomic) BOOL hasDecisionVO;
@property (nonatomic) unsigned int decisionVO;
@property (nonatomic) BOOL hasDecisionVIBE;
@property (nonatomic) unsigned int decisionVIBE;
@property (nonatomic) BOOL hasVideoStreamingStallTime;
@property (nonatomic) unsigned int videoStreamingStallTime;
@property (nonatomic) BOOL hasTxber;
@property (nonatomic) unsigned int txber;
@property (nonatomic) BOOL hasRxRetry;
@property (nonatomic) unsigned int rxRetry;
@property (nonatomic) BOOL hasWeightedAveragePhyrateTx;
@property (nonatomic) unsigned int weightedAveragePhyrateTx;
@property (nonatomic) BOOL hasWeightedAveragePhyrateRx;
@property (nonatomic) unsigned int weightedAveragePhyrateRx;
@property (nonatomic) BOOL hasWeightedAverageRssi;
@property (nonatomic) unsigned int weightedAverageRssi;
@property (nonatomic) BOOL hasWeightedAverageSnr;
@property (nonatomic) unsigned int weightedAverageSnr;
@property (nonatomic) BOOL hasCmDataSentCount;
@property (nonatomic) unsigned int cmDataSentCount;
@property (nonatomic) BOOL hasCmDataSentDuration;
@property (nonatomic) unsigned int cmDataSentDuration;
@property (nonatomic) BOOL hasCmEstimatedBandwidth;
@property (nonatomic) unsigned int cmEstimatedBandwidth;
@property (nonatomic) BOOL hasDevicePointOfInterest;
@property (nonatomic) unsigned int devicePointOfInterest;
@property (nonatomic) BOOL hasRrcState;
@property (nonatomic) unsigned int rrcState;
@property (nonatomic) BOOL hasMlPredictedWiFiBW;
@property (nonatomic) unsigned int mlPredictedWiFiBW;
@property (nonatomic) BOOL hasWifiModelVersion;
@property (nonatomic) unsigned int wifiModelVersion;
@property (nonatomic) BOOL hasWifiModelConfidenceLevel;
@property (nonatomic) unsigned int wifiModelConfidenceLevel;
@property (nonatomic) BOOL hasMlPredictedCellBW;
@property (nonatomic) unsigned int mlPredictedCellBW;
@property (nonatomic) BOOL hasCellModelVersion;
@property (nonatomic) unsigned int cellModelVersion;
@property (nonatomic) BOOL hasCellModelConfidenceLevel;
@property (nonatomic) unsigned int cellModelConfidenceLevel;
@property (nonatomic) BOOL hasCellEstimatedBW;
@property (nonatomic) unsigned int cellEstimatedBW;
@property (readonly, nonatomic) BOOL hasAppType;
@property (retain, nonatomic) NSString *appType;
@property (nonatomic) BOOL hasTcpRTTAvg;
@property (nonatomic) unsigned int tcpRTTAvg;
@property (nonatomic) BOOL hasTcpRTTmin;
@property (nonatomic) unsigned int tcpRTTmin;
@property (nonatomic) BOOL hasTcpRTTvar;
@property (nonatomic) unsigned int tcpRTTvar;
@property (nonatomic) BOOL hasRatioDupeBytes;
@property (nonatomic) unsigned int ratioDupeBytes;
@property (nonatomic) BOOL hasRatioOOBBytes;
@property (nonatomic) unsigned int ratioOOBBytes;
@property (nonatomic) BOOL hasCellARFCN;
@property (nonatomic) unsigned int cellARFCN;
@property (nonatomic) BOOL hasCellChannelBW;
@property (nonatomic) unsigned int cellChannelBW;
@property (nonatomic) BOOL hasCellBandInfo;
@property (nonatomic) unsigned int cellBandInfo;
@property (nonatomic) BOOL hasMaxDLCAConfigured;
@property (nonatomic) unsigned int maxDLCAConfigured;
@property (nonatomic) BOOL hasMaxULCAConfigured;
@property (nonatomic) unsigned int maxULCAConfigured;
@property (nonatomic) BOOL hasWifChannelBW;
@property (nonatomic) unsigned int wifChannelBW;
@property (nonatomic) BOOL hasWifChannelType;
@property (nonatomic) unsigned int wifChannelType;
@property (nonatomic) BOOL hasWifiCapability;
@property (nonatomic) unsigned int wifiCapability;
@property (nonatomic) BOOL hasEstimatedSpeed;
@property (nonatomic) unsigned int estimatedSpeed;
@property (nonatomic) BOOL hasCellNsaEnabled;
@property (nonatomic) BOOL cellNsaEnabled;
@property (nonatomic) BOOL hasIsFR1;
@property (nonatomic) BOOL isFR1;
@property (nonatomic) BOOL hasCellNrRSRP;
@property (nonatomic) int cellNrRSRP;
@property (nonatomic) BOOL hasCellNrRSRQ;
@property (nonatomic) int cellNrRSRQ;
@property (nonatomic) BOOL hasCellNrSNR;
@property (nonatomic) int cellNrSNR;
@property (nonatomic) BOOL hasCellLteRSRQ;
@property (nonatomic) int cellLteRSRQ;
@property (nonatomic) BOOL hasPActualLowBandwidth;
@property (nonatomic) int pActualLowBandwidth;
@property (nonatomic) BOOL hasWifimcsindex;
@property (nonatomic) int wifimcsindex;
@property (nonatomic) BOOL hasWifiguardinterval;
@property (nonatomic) int wifiguardinterval;
@property (nonatomic) BOOL hasWifinumberOfSpatialStreams;
@property (nonatomic) int wifinumberOfSpatialStreams;
@property (nonatomic) BOOL hasWifichannel;
@property (nonatomic) int wifichannel;
@property (nonatomic) BOOL hasWifilowDataMode;
@property (nonatomic) int wifilowDataMode;
@property (nonatomic) BOOL hasIsWfiCaptive;
@property (nonatomic) int isWfiCaptive;
@property (nonatomic) BOOL hasBtWiFiCoexState;
@property (nonatomic) int btWiFiCoexState;
@property (nonatomic) BOOL hasTotalConfiguredBw;
@property (nonatomic) unsigned int totalConfiguredBw;
@property (nonatomic) BOOL hasNrConfiguredBw;
@property (nonatomic) unsigned int nrConfiguredBw;
@property (nonatomic) BOOL hasNrTotalScheduledMimoLayers;
@property (nonatomic) unsigned int nrTotalScheduledMimoLayers;
@property (nonatomic) BOOL hasTotalConfiguredMimoLayers;
@property (nonatomic) unsigned int totalConfiguredMimoLayers;
@property (nonatomic) BOOL hasLteMaxScheduledMimoLayersInACell;
@property (nonatomic) unsigned int lteMaxScheduledMimoLayersInACell;
@property (nonatomic) BOOL hasNrMaxDlModulation;
@property (nonatomic) unsigned int nrMaxDlModulation;
@property (nonatomic) BOOL hasColdStartType;
@property (nonatomic) unsigned int coldStartType;

- (id)copyWithZone:(struct _NSZone { } *)a0;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)a0;
- (void)dealloc;
- (void)mergeFrom:(id)a0;
- (BOOL)isEqual:(id)a0;
- (unsigned long long)hash;
- (void)writeTo:(id)a0;
- (BOOL)readFrom:(id)a0;
- (id)description;

@end
