@class AWDWiFiMetricsManagerStateMachine;

@interface AWDWiFiMetricsManagerInfraInterface : PBCodable <NSCopying> {
    struct { unsigned char rxBytes : 1; unsigned char rxPackets : 1; unsigned char timestamp : 1; unsigned char txBytes : 1; unsigned char txBytesBe : 1; unsigned char txBytesBk : 1; unsigned char txBytesVi : 1; unsigned char txBytesVo : 1; unsigned char txPackets : 1; unsigned char txPacketsBe : 1; unsigned char txPacketsBk : 1; unsigned char txPacketsVi : 1; unsigned char txPacketsVo : 1; unsigned char avgCCA : 1; unsigned char dataTransferRateMpbs : 1; unsigned char effectiveDataTransferRateMpbs : 1; unsigned char effectiveLinkRateMpbs : 1; unsigned char linkLatencyMs : 1; unsigned char linkOpenPct : 1; unsigned char linkRateMbps : 1; unsigned char lqm : 1; } _has;
}

@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) unsigned long long timestamp;
@property (nonatomic) BOOL hasRxPackets;
@property (nonatomic) unsigned long long rxPackets;
@property (nonatomic) BOOL hasTxPackets;
@property (nonatomic) unsigned long long txPackets;
@property (nonatomic) BOOL hasTxPacketsBe;
@property (nonatomic) unsigned long long txPacketsBe;
@property (nonatomic) BOOL hasTxPacketsBk;
@property (nonatomic) unsigned long long txPacketsBk;
@property (nonatomic) BOOL hasTxPacketsVi;
@property (nonatomic) unsigned long long txPacketsVi;
@property (nonatomic) BOOL hasTxPacketsVo;
@property (nonatomic) unsigned long long txPacketsVo;
@property (nonatomic) BOOL hasRxBytes;
@property (nonatomic) unsigned long long rxBytes;
@property (nonatomic) BOOL hasTxBytes;
@property (nonatomic) unsigned long long txBytes;
@property (nonatomic) BOOL hasTxBytesBe;
@property (nonatomic) unsigned long long txBytesBe;
@property (nonatomic) BOOL hasTxBytesBk;
@property (nonatomic) unsigned long long txBytesBk;
@property (nonatomic) BOOL hasTxBytesVi;
@property (nonatomic) unsigned long long txBytesVi;
@property (nonatomic) BOOL hasTxBytesVo;
@property (nonatomic) unsigned long long txBytesVo;
@property (nonatomic) BOOL hasLinkRateMbps;
@property (nonatomic) unsigned int linkRateMbps;
@property (nonatomic) BOOL hasEffectiveLinkRateMpbs;
@property (nonatomic) unsigned int effectiveLinkRateMpbs;
@property (nonatomic) BOOL hasDataTransferRateMpbs;
@property (nonatomic) unsigned int dataTransferRateMpbs;
@property (nonatomic) BOOL hasEffectiveDataTransferRateMpbs;
@property (nonatomic) unsigned int effectiveDataTransferRateMpbs;
@property (nonatomic) BOOL hasLinkLatencyMs;
@property (nonatomic) unsigned int linkLatencyMs;
@property (readonly, nonatomic) BOOL hasLinkLatency0ms;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *linkLatency0ms;
@property (readonly, nonatomic) BOOL hasLinkLatency64ms;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *linkLatency64ms;
@property (readonly, nonatomic) BOOL hasLinkLatency128ms;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *linkLatency128ms;
@property (readonly, nonatomic) BOOL hasLinkLatency256ms;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *linkLatency256ms;
@property (readonly, nonatomic) BOOL hasLinkLatency512ms;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *linkLatency512ms;
@property (readonly, nonatomic) BOOL hasLinkLatency1024ms;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *linkLatency1024ms;
@property (nonatomic) BOOL hasLinkOpenPct;
@property (nonatomic) unsigned int linkOpenPct;
@property (readonly, nonatomic) BOOL hasLinkOpen0pct;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *linkOpen0pct;
@property (readonly, nonatomic) BOOL hasLinkOpen125pct;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *linkOpen125pct;
@property (readonly, nonatomic) BOOL hasLinkOpen25pct;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *linkOpen25pct;
@property (readonly, nonatomic) BOOL hasLinkOpen375pct;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *linkOpen375pct;
@property (readonly, nonatomic) BOOL hasLinkOpen50pct;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *linkOpen50pct;
@property (readonly, nonatomic) BOOL hasLinkOpen625pct;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *linkOpen625pct;
@property (readonly, nonatomic) BOOL hasLinkOpen75pct;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *linkOpen75pct;
@property (readonly, nonatomic) BOOL hasLinkOpen875pct;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *linkOpen875pct;
@property (readonly, nonatomic) BOOL hasLinkOpen100pct;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *linkOpen100pct;
@property (nonatomic) BOOL hasAvgCCA;
@property (nonatomic) unsigned int avgCCA;
@property (readonly, nonatomic) BOOL hasAvgCCA0pct;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *avgCCA0pct;
@property (readonly, nonatomic) BOOL hasAvgCCA125pct;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *avgCCA125pct;
@property (readonly, nonatomic) BOOL hasAvgCCA25pct;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *avgCCA25pct;
@property (readonly, nonatomic) BOOL hasAvgCCA375pct;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *avgCCA375pct;
@property (readonly, nonatomic) BOOL hasAvgCCA50pct;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *avgCCA50pct;
@property (readonly, nonatomic) BOOL hasAvgCCA625pct;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *avgCCA625pct;
@property (readonly, nonatomic) BOOL hasAvgCCA75pct;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *avgCCA75pct;
@property (readonly, nonatomic) BOOL hasAvgCCA875pct;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *avgCCA875pct;
@property (readonly, nonatomic) BOOL hasAvgCCA100pct;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *avgCCA100pct;
@property (nonatomic) BOOL hasLqm;
@property (nonatomic) unsigned int lqm;
@property (readonly, nonatomic) BOOL hasLqmOff;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *lqmOff;
@property (readonly, nonatomic) BOOL hasLqmUnknown;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *lqmUnknown;
@property (readonly, nonatomic) BOOL hasLqmBad;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *lqmBad;
@property (readonly, nonatomic) BOOL hasLqmPoor;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *lqmPoor;
@property (readonly, nonatomic) BOOL hasLqmGood;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *lqmGood;
@property (readonly, nonatomic) BOOL hasActivityUp;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *activityUp;
@property (readonly, nonatomic) BOOL hasActivityDown;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *activityDown;
@property (readonly, nonatomic) BOOL hasActivityInvoluntarilyDown;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *activityInvoluntarilyDown;
@property (readonly, nonatomic) BOOL hasActivityScanning;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *activityScanning;
@property (readonly, nonatomic) BOOL hasActivityRoaming;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *activityRoaming;

- (id)copyWithZone:(struct _NSZone { } *)a0;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)a0;
- (void)dealloc;
- (void)mergeFrom:(id)a0;
- (BOOL)isEqual:(id)a0;
- (unsigned long long)hash;
- (void)writeTo:(id)a0;
- (BOOL)readFrom:(id)a0;
- (id)description;

@end
