@interface AWDWiFiWcpsStats : PBCodable <NSCopying> {
    struct { unsigned char avgCca : 1; unsigned char avgRssi : 1; unsigned char avgRxRetry : 1; unsigned char avgSnr : 1; unsigned char avgTxAirLatency : 1; unsigned char avgTxPacketLoss : 1; unsigned char avgTxRetrans : 1; unsigned char cntAwdlActive : 1; unsigned char cntDisBtConnLatHi : 1; unsigned char cntDisBtEv3 : 1; unsigned char cntRedBtConnLatLow : 1; unsigned char cntRedBtDisconnLatHi : 1; unsigned char cntVoBadPeriods : 1; unsigned char cntVoGoodPeriods : 1; unsigned char durationBucket : 1; unsigned char endCca : 1; unsigned char endLinkState : 1; unsigned char endRssi : 1; unsigned char endRxRetry : 1; unsigned char endSnr : 1; unsigned char endTxAirLatency : 1; unsigned char endTxPacketLoss : 1; unsigned char endTxRetrans : 1; unsigned char maxCca : 1; unsigned char maxRssi : 1; unsigned char maxRxRetry : 1; unsigned char maxTxAirLatency : 1; unsigned char maxTxPacketLoss : 1; unsigned char maxTxRetrans : 1; unsigned char maxnSnr : 1; unsigned char minCca : 1; unsigned char minRssi : 1; unsigned char minRxRetry : 1; unsigned char minSnr : 1; unsigned char minTxAirLatency : 1; unsigned char minTxPacketLoss : 1; unsigned char minTxRetrans : 1; unsigned char percentageActive : 1; unsigned char percentagePowerSave : 1; unsigned char percentageWcpsDisabled : 1; unsigned char percentageWcpsEnabled : 1; unsigned char percentageWcpsReduced : 1; unsigned char timestamp : 1; } _has;
}

@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) unsigned long long timestamp;
@property (nonatomic) BOOL hasDurationBucket;
@property (nonatomic) unsigned long long durationBucket;
@property (nonatomic) BOOL hasPercentageActive;
@property (nonatomic) unsigned long long percentageActive;
@property (nonatomic) BOOL hasPercentagePowerSave;
@property (nonatomic) unsigned long long percentagePowerSave;
@property (nonatomic) BOOL hasPercentageWcpsEnabled;
@property (nonatomic) unsigned long long percentageWcpsEnabled;
@property (nonatomic) BOOL hasPercentageWcpsReduced;
@property (nonatomic) unsigned long long percentageWcpsReduced;
@property (nonatomic) BOOL hasPercentageWcpsDisabled;
@property (nonatomic) unsigned long long percentageWcpsDisabled;
@property (nonatomic) BOOL hasCntVoGoodPeriods;
@property (nonatomic) unsigned long long cntVoGoodPeriods;
@property (nonatomic) BOOL hasCntVoBadPeriods;
@property (nonatomic) unsigned long long cntVoBadPeriods;
@property (nonatomic) BOOL hasAvgRssi;
@property (nonatomic) unsigned long long avgRssi;
@property (nonatomic) BOOL hasAvgSnr;
@property (nonatomic) unsigned long long avgSnr;
@property (nonatomic) BOOL hasAvgCca;
@property (nonatomic) unsigned long long avgCca;
@property (nonatomic) BOOL hasAvgTxAirLatency;
@property (nonatomic) unsigned long long avgTxAirLatency;
@property (nonatomic) BOOL hasAvgTxPacketLoss;
@property (nonatomic) unsigned long long avgTxPacketLoss;
@property (nonatomic) BOOL hasAvgTxRetrans;
@property (nonatomic) unsigned long long avgTxRetrans;
@property (nonatomic) BOOL hasAvgRxRetry;
@property (nonatomic) unsigned long long avgRxRetry;
@property (nonatomic) BOOL hasEndRssi;
@property (nonatomic) unsigned long long endRssi;
@property (nonatomic) BOOL hasEndSnr;
@property (nonatomic) unsigned long long endSnr;
@property (nonatomic) BOOL hasEndCca;
@property (nonatomic) unsigned long long endCca;
@property (nonatomic) BOOL hasEndTxAirLatency;
@property (nonatomic) unsigned long long endTxAirLatency;
@property (nonatomic) BOOL hasEndTxPacketLoss;
@property (nonatomic) unsigned long long endTxPacketLoss;
@property (nonatomic) BOOL hasEndTxRetrans;
@property (nonatomic) unsigned long long endTxRetrans;
@property (nonatomic) BOOL hasEndRxRetry;
@property (nonatomic) unsigned long long endRxRetry;
@property (nonatomic) BOOL hasMinRssi;
@property (nonatomic) unsigned long long minRssi;
@property (nonatomic) BOOL hasMinSnr;
@property (nonatomic) unsigned long long minSnr;
@property (nonatomic) BOOL hasMinCca;
@property (nonatomic) unsigned long long minCca;
@property (nonatomic) BOOL hasMinTxAirLatency;
@property (nonatomic) unsigned long long minTxAirLatency;
@property (nonatomic) BOOL hasMinTxPacketLoss;
@property (nonatomic) unsigned long long minTxPacketLoss;
@property (nonatomic) BOOL hasMinTxRetrans;
@property (nonatomic) unsigned long long minTxRetrans;
@property (nonatomic) BOOL hasMinRxRetry;
@property (nonatomic) unsigned long long minRxRetry;
@property (nonatomic) BOOL hasMaxRssi;
@property (nonatomic) unsigned long long maxRssi;
@property (nonatomic) BOOL hasMaxnSnr;
@property (nonatomic) unsigned long long maxnSnr;
@property (nonatomic) BOOL hasMaxCca;
@property (nonatomic) unsigned long long maxCca;
@property (nonatomic) BOOL hasMaxTxAirLatency;
@property (nonatomic) unsigned long long maxTxAirLatency;
@property (nonatomic) BOOL hasMaxTxPacketLoss;
@property (nonatomic) unsigned long long maxTxPacketLoss;
@property (nonatomic) BOOL hasMaxTxRetrans;
@property (nonatomic) unsigned long long maxTxRetrans;
@property (nonatomic) BOOL hasMaxRxRetry;
@property (nonatomic) unsigned long long maxRxRetry;
@property (nonatomic) BOOL hasCntRedBtConnLatLow;
@property (nonatomic) unsigned long long cntRedBtConnLatLow;
@property (nonatomic) BOOL hasCntRedBtDisconnLatHi;
@property (nonatomic) unsigned long long cntRedBtDisconnLatHi;
@property (nonatomic) BOOL hasCntDisBtConnLatHi;
@property (nonatomic) unsigned long long cntDisBtConnLatHi;
@property (nonatomic) BOOL hasCntDisBtEv3;
@property (nonatomic) unsigned long long cntDisBtEv3;
@property (nonatomic) BOOL hasCntAwdlActive;
@property (nonatomic) unsigned long long cntAwdlActive;
@property (nonatomic) BOOL hasEndLinkState;
@property (nonatomic) unsigned long long endLinkState;

- (id)copyWithZone:(struct _NSZone { } *)a0;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)a0;
- (void)mergeFrom:(id)a0;
- (BOOL)isEqual:(id)a0;
- (unsigned long long)hash;
- (void)writeTo:(id)a0;
- (BOOL)readFrom:(id)a0;
- (id)description;

@end
