@class NSMutableArray;

@interface AWDWiFiP2PAirplayMetrics : PBCodable <NSCopying> {
    struct { unsigned char rxBytes : 1; unsigned char timestamp : 1; unsigned char txBytes : 1; unsigned char awdlVersion : 1; unsigned char clientModeDuration : 1; unsigned char forceRoamHasChannelsCnt : 1; unsigned char forceRoamHasNoChannel : 1; unsigned char infraDisconnectedCount : 1; unsigned char missingAWStartEventCount : 1; unsigned char peerInfraChannel : 1; unsigned char peerInfraChannelFlags : 1; unsigned char psfEnabledCount : 1; unsigned char roamOutOfOtherCount : 1; unsigned char roamOutOfOtherFailure : 1; unsigned char roamOutOfOtherSuccess : 1; unsigned char routablePeerCount : 1; unsigned char selfInfraChannel : 1; unsigned char selfInfraChannelFlags : 1; unsigned char senderPlatform : 1; unsigned char sequenceNumberNotUpdatedCount : 1; unsigned char serverModeDuration : 1; unsigned char splitModeDuration : 1; unsigned char startingRSSI : 1; unsigned char totalDuration : 1; unsigned char totalPeerCount : 1; unsigned char csaDuringDfspMode : 1; unsigned char csaToDfsChannel : 1; unsigned char dfsProxyMode : 1; unsigned char inRetroMode : 1; unsigned char peerIsSDB : 1; unsigned char selfIsSDB : 1; } _has;
}

@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) unsigned long long timestamp;
@property (nonatomic) BOOL hasTotalDuration;
@property (nonatomic) unsigned int totalDuration;
@property (nonatomic) BOOL hasServerModeDuration;
@property (nonatomic) unsigned int serverModeDuration;
@property (nonatomic) BOOL hasClientModeDuration;
@property (nonatomic) unsigned int clientModeDuration;
@property (nonatomic) BOOL hasSplitModeDuration;
@property (nonatomic) unsigned int splitModeDuration;
@property (nonatomic) BOOL hasTxBytes;
@property (nonatomic) unsigned long long txBytes;
@property (nonatomic) BOOL hasRxBytes;
@property (nonatomic) unsigned long long rxBytes;
@property (nonatomic) BOOL hasStartingRSSI;
@property (nonatomic) int startingRSSI;
@property (nonatomic) BOOL hasAwdlVersion;
@property (nonatomic) unsigned int awdlVersion;
@property (nonatomic) BOOL hasTotalPeerCount;
@property (nonatomic) unsigned int totalPeerCount;
@property (nonatomic) BOOL hasRoutablePeerCount;
@property (nonatomic) unsigned int routablePeerCount;
@property (nonatomic) BOOL hasInfraDisconnectedCount;
@property (nonatomic) unsigned int infraDisconnectedCount;
@property (nonatomic) BOOL hasSequenceNumberNotUpdatedCount;
@property (nonatomic) unsigned int sequenceNumberNotUpdatedCount;
@property (nonatomic) BOOL hasMissingAWStartEventCount;
@property (nonatomic) unsigned int missingAWStartEventCount;
@property (nonatomic) BOOL hasPsfEnabledCount;
@property (nonatomic) unsigned int psfEnabledCount;
@property (nonatomic) BOOL hasSelfInfraChannel;
@property (nonatomic) unsigned int selfInfraChannel;
@property (nonatomic) BOOL hasPeerInfraChannel;
@property (nonatomic) unsigned int peerInfraChannel;
@property (nonatomic) BOOL hasSenderPlatform;
@property (nonatomic) unsigned int senderPlatform;
@property (nonatomic) BOOL hasCsaToDfsChannel;
@property (nonatomic) BOOL csaToDfsChannel;
@property (nonatomic) BOOL hasCsaDuringDfspMode;
@property (nonatomic) BOOL csaDuringDfspMode;
@property (nonatomic) BOOL hasDfsProxyMode;
@property (nonatomic) BOOL dfsProxyMode;
@property (nonatomic) BOOL hasSelfIsSDB;
@property (nonatomic) BOOL selfIsSDB;
@property (nonatomic) BOOL hasPeerIsSDB;
@property (nonatomic) BOOL peerIsSDB;
@property (nonatomic) BOOL hasInRetroMode;
@property (nonatomic) BOOL inRetroMode;
@property (retain, nonatomic) NSMutableArray *peerRSSIs;
@property (retain, nonatomic) NSMutableArray *avgCCASocialChannels;
@property (retain, nonatomic) NSMutableArray *avgCCASelfInfraChannels;
@property (retain, nonatomic) NSMutableArray *avgCCAPeerInfraChannels;
@property (nonatomic) BOOL hasSelfInfraChannelFlags;
@property (nonatomic) unsigned int selfInfraChannelFlags;
@property (nonatomic) BOOL hasPeerInfraChannelFlags;
@property (nonatomic) unsigned int peerInfraChannelFlags;
@property (nonatomic) BOOL hasRoamOutOfOtherCount;
@property (nonatomic) unsigned int roamOutOfOtherCount;
@property (nonatomic) BOOL hasRoamOutOfOtherSuccess;
@property (nonatomic) unsigned int roamOutOfOtherSuccess;
@property (nonatomic) BOOL hasRoamOutOfOtherFailure;
@property (nonatomic) unsigned int roamOutOfOtherFailure;
@property (nonatomic) BOOL hasForceRoamHasChannelsCnt;
@property (nonatomic) unsigned int forceRoamHasChannelsCnt;
@property (nonatomic) BOOL hasForceRoamHasNoChannel;
@property (nonatomic) unsigned int forceRoamHasNoChannel;

+ (Class)avgCCAPeerInfraChannelType;
+ (Class)avgCCASelfInfraChannelType;
+ (Class)avgCCASocialChannelType;
+ (Class)peerRSSIType;

- (id)copyWithZone:(struct _NSZone { } *)a0;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)a0;
- (void)dealloc;
- (void)mergeFrom:(id)a0;
- (BOOL)isEqual:(id)a0;
- (unsigned long long)hash;
- (void)writeTo:(id)a0;
- (BOOL)readFrom:(id)a0;
- (id)description;
- (void)addAvgCCAPeerInfraChannel:(id)a0;
- (void)addAvgCCASelfInfraChannel:(id)a0;
- (void)addAvgCCASocialChannel:(id)a0;
- (void)addPeerRSSI:(id)a0;
- (id)avgCCAPeerInfraChannelAtIndex:(unsigned long long)a0;
- (unsigned long long)avgCCAPeerInfraChannelsCount;
- (id)avgCCASelfInfraChannelAtIndex:(unsigned long long)a0;
- (unsigned long long)avgCCASelfInfraChannelsCount;
- (id)avgCCASocialChannelAtIndex:(unsigned long long)a0;
- (unsigned long long)avgCCASocialChannelsCount;
- (void)clearAvgCCAPeerInfraChannels;
- (void)clearAvgCCASelfInfraChannels;
- (void)clearAvgCCASocialChannels;
- (void)clearPeerRSSIs;
- (id)peerRSSIAtIndex:(unsigned long long)a0;
- (unsigned long long)peerRSSIsCount;

@end
