@class AWDWiFiMetricsManagerStateMachine;

@interface AWDWiFiMetricsManagerBTCoexStats : PBCodable <NSCopying> {
    struct { unsigned long long *list; unsigned long long count; unsigned long long size; } _rxMPDUCountPerMCSs;
    struct { unsigned long long *list; unsigned long long count; unsigned long long size; } _txMPDUCountPerMCSs;
    struct { unsigned char antennaGrants : 1; unsigned char antennaRequests : 1; unsigned char beaconLostCnt : 1; unsigned char envelopeLowToHighAccumulatedMsec : 1; unsigned char guardTimeMicroseconds : 1; unsigned char highUcodeLatency : 1; unsigned char psRequestTxCnt : 1; unsigned char psnullExceeded : 1; unsigned char requestsA2DP : 1; unsigned char requestsACL : 1; unsigned char requestsBLE : 1; unsigned char requestsBLEScan : 1; unsigned char requestsInquiry : 1; unsigned char requestsInquiryScan : 1; unsigned char requestsMSS : 1; unsigned char requestsOther : 1; unsigned char requestsPARK : 1; unsigned char requestsPage : 1; unsigned char requestsPageScan : 1; unsigned char requestsSCO : 1; unsigned char requestsSniff : 1; unsigned char requestseSCO : 1; unsigned char resumeTimeAccumulatedMsec : 1; unsigned char scoReservedSlotDenyCount : 1; unsigned char scoRetransmission1DenyCount : 1; unsigned char scoRetransmission2DenyCount : 1; unsigned char timeTillResumeAccumulatedMsec : 1; unsigned char timestamp : 1; unsigned char txCTS2Self : 1; unsigned char wlanPreempted : 1; } _has;
}

@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) unsigned long long timestamp;
@property (nonatomic) BOOL hasAntennaRequests;
@property (nonatomic) unsigned long long antennaRequests;
@property (nonatomic) BOOL hasAntennaGrants;
@property (nonatomic) unsigned long long antennaGrants;
@property (nonatomic) BOOL hasWlanPreempted;
@property (nonatomic) unsigned long long wlanPreempted;
@property (nonatomic) BOOL hasPsnullExceeded;
@property (nonatomic) unsigned long long psnullExceeded;
@property (nonatomic) BOOL hasHighUcodeLatency;
@property (nonatomic) unsigned long long highUcodeLatency;
@property (readonly, nonatomic) BOOL hasAntennaOwnership2BT;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *antennaOwnership2BT;
@property (readonly, nonatomic) BOOL hasAntennaOwnership2WLAN;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *antennaOwnership2WLAN;
@property (readonly, nonatomic) BOOL hasEnbledStateOn;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *enbledStateOn;
@property (readonly, nonatomic) BOOL hasEnbledStateOff;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *enbledStateOff;
@property (readonly, nonatomic) BOOL hasHybridStateOn;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *hybridStateOn;
@property (readonly, nonatomic) BOOL hasHybridStateOff;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *hybridStateOff;
@property (readonly, nonatomic) BOOL hasTdmStateOn;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *tdmStateOn;
@property (readonly, nonatomic) BOOL hasTdmStateOff;
@property (retain, nonatomic) AWDWiFiMetricsManagerStateMachine *tdmStateOff;
@property (nonatomic) BOOL hasRequestsACL;
@property (nonatomic) unsigned long long requestsACL;
@property (nonatomic) BOOL hasRequestsSCO;
@property (nonatomic) unsigned long long requestsSCO;
@property (nonatomic) BOOL hasRequestseSCO;
@property (nonatomic) unsigned long long requestseSCO;
@property (nonatomic) BOOL hasRequestsA2DP;
@property (nonatomic) unsigned long long requestsA2DP;
@property (nonatomic) BOOL hasRequestsSniff;
@property (nonatomic) unsigned long long requestsSniff;
@property (nonatomic) BOOL hasRequestsPageScan;
@property (nonatomic) unsigned long long requestsPageScan;
@property (nonatomic) BOOL hasRequestsInquiryScan;
@property (nonatomic) unsigned long long requestsInquiryScan;
@property (nonatomic) BOOL hasRequestsPage;
@property (nonatomic) unsigned long long requestsPage;
@property (nonatomic) BOOL hasRequestsInquiry;
@property (nonatomic) unsigned long long requestsInquiry;
@property (nonatomic) BOOL hasRequestsBLE;
@property (nonatomic) unsigned long long requestsBLE;
@property (nonatomic) BOOL hasRequestsOther;
@property (nonatomic) unsigned long long requestsOther;
@property (nonatomic) BOOL hasRequestsBLEScan;
@property (nonatomic) unsigned long long requestsBLEScan;
@property (nonatomic) BOOL hasRequestsMSS;
@property (nonatomic) unsigned long long requestsMSS;
@property (nonatomic) BOOL hasRequestsPARK;
@property (nonatomic) unsigned long long requestsPARK;
@property (nonatomic) BOOL hasBeaconLostCnt;
@property (nonatomic) unsigned long long beaconLostCnt;
@property (readonly, nonatomic) unsigned long long rxMPDUCountPerMCSsCount;
@property (readonly, nonatomic) unsigned long long *rxMPDUCountPerMCSs;
@property (readonly, nonatomic) unsigned long long txMPDUCountPerMCSsCount;
@property (readonly, nonatomic) unsigned long long *txMPDUCountPerMCSs;
@property (nonatomic) BOOL hasTimeTillResumeAccumulatedMsec;
@property (nonatomic) unsigned long long timeTillResumeAccumulatedMsec;
@property (nonatomic) BOOL hasResumeTimeAccumulatedMsec;
@property (nonatomic) unsigned long long resumeTimeAccumulatedMsec;
@property (nonatomic) BOOL hasEnvelopeLowToHighAccumulatedMsec;
@property (nonatomic) unsigned long long envelopeLowToHighAccumulatedMsec;
@property (nonatomic) BOOL hasScoReservedSlotDenyCount;
@property (nonatomic) unsigned long long scoReservedSlotDenyCount;
@property (nonatomic) BOOL hasScoRetransmission1DenyCount;
@property (nonatomic) unsigned long long scoRetransmission1DenyCount;
@property (nonatomic) BOOL hasScoRetransmission2DenyCount;
@property (nonatomic) unsigned long long scoRetransmission2DenyCount;
@property (nonatomic) BOOL hasGuardTimeMicroseconds;
@property (nonatomic) unsigned long long guardTimeMicroseconds;
@property (nonatomic) BOOL hasPsRequestTxCnt;
@property (nonatomic) unsigned long long psRequestTxCnt;
@property (nonatomic) BOOL hasTxCTS2Self;
@property (nonatomic) unsigned long long txCTS2Self;

- (id)copyWithZone:(struct _NSZone { } *)a0;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)a0;
- (void)dealloc;
- (void)mergeFrom:(id)a0;
- (BOOL)isEqual:(id)a0;
- (unsigned long long)hash;
- (void)writeTo:(id)a0;
- (BOOL)readFrom:(id)a0;
- (id)description;
- (void)addRxMPDUCountPerMCS:(unsigned long long)a0;
- (void)addTxMPDUCountPerMCS:(unsigned long long)a0;
- (void)clearRxMPDUCountPerMCSs;
- (void)clearTxMPDUCountPerMCSs;
- (unsigned long long)rxMPDUCountPerMCSAtIndex:(unsigned long long)a0;
- (void)setRxMPDUCountPerMCSs:(unsigned long long *)a0 count:(unsigned long long)a1;
- (void)setTxMPDUCountPerMCSs:(unsigned long long *)a0 count:(unsigned long long)a1;
- (unsigned long long)txMPDUCountPerMCSAtIndex:(unsigned long long)a0;

@end
