@interface AWDWiFiNWActivityAssoc : PBCodable <NSCopying> {
    struct { unsigned char assocDoneFailed : 1; unsigned char assocDoneSuccess : 1; unsigned char assocFailed : 1; unsigned char assocReady : 1; unsigned char assocSuccess : 1; unsigned char authFailed : 1; unsigned char authSuccess : 1; unsigned char bssDisallowEvent : 1; unsigned char bssidChanged : 1; unsigned char chanSwitchEvent : 1; unsigned char crashTracerTrig : 1; unsigned char deauthReceived : 1; unsigned char decryptError : 1; unsigned char disassocReceived : 1; unsigned char dpsSymptom : 1; unsigned char escoTrafficInd : 1; unsigned char homeChanQualChanged : 1; unsigned char linkChanged : 1; unsigned char macAddrChanged : 1; unsigned char pruned : 1; unsigned char rc1Stats : 1; unsigned char rc2Stats : 1; unsigned char reassocFailed : 1; unsigned char reassocSuccess : 1; unsigned char roamFailed : 1; unsigned char roamPrep : 1; unsigned char roamScanEnd : 1; unsigned char roamScanStart : 1; unsigned char roamSuccess : 1; unsigned char rssiChanged : 1; unsigned char scanDone : 1; unsigned char scanInternalDone : 1; unsigned char scanResults : 1; unsigned char scanSummary : 1; unsigned char slowWiFiSymptom : 1; unsigned char ssidChanged : 1; unsigned char supplicant : 1; } _has;
}

@property (nonatomic) BOOL hasAuthSuccess;
@property (nonatomic) unsigned int authSuccess;
@property (nonatomic) BOOL hasAuthFailed;
@property (nonatomic) unsigned int authFailed;
@property (nonatomic) BOOL hasAssocSuccess;
@property (nonatomic) unsigned int assocSuccess;
@property (nonatomic) BOOL hasAssocFailed;
@property (nonatomic) unsigned int assocFailed;
@property (nonatomic) BOOL hasReassocSuccess;
@property (nonatomic) unsigned int reassocSuccess;
@property (nonatomic) BOOL hasReassocFailed;
@property (nonatomic) unsigned int reassocFailed;
@property (nonatomic) BOOL hasLinkChanged;
@property (nonatomic) unsigned int linkChanged;
@property (nonatomic) BOOL hasRoamSuccess;
@property (nonatomic) unsigned int roamSuccess;
@property (nonatomic) BOOL hasRoamFailed;
@property (nonatomic) unsigned int roamFailed;
@property (nonatomic) BOOL hasAssocDoneSuccess;
@property (nonatomic) unsigned int assocDoneSuccess;
@property (nonatomic) BOOL hasAssocDoneFailed;
@property (nonatomic) unsigned int assocDoneFailed;
@property (nonatomic) BOOL hasAssocReady;
@property (nonatomic) unsigned int assocReady;
@property (nonatomic) BOOL hasSsidChanged;
@property (nonatomic) unsigned int ssidChanged;
@property (nonatomic) BOOL hasBssidChanged;
@property (nonatomic) unsigned int bssidChanged;
@property (nonatomic) BOOL hasDeauthReceived;
@property (nonatomic) unsigned int deauthReceived;
@property (nonatomic) BOOL hasDisassocReceived;
@property (nonatomic) unsigned int disassocReceived;
@property (nonatomic) BOOL hasDecryptError;
@property (nonatomic) unsigned int decryptError;
@property (nonatomic) BOOL hasPruned;
@property (nonatomic) unsigned int pruned;
@property (nonatomic) BOOL hasSupplicant;
@property (nonatomic) unsigned int supplicant;
@property (nonatomic) BOOL hasMacAddrChanged;
@property (nonatomic) unsigned int macAddrChanged;
@property (nonatomic) BOOL hasRssiChanged;
@property (nonatomic) unsigned int rssiChanged;
@property (nonatomic) BOOL hasHomeChanQualChanged;
@property (nonatomic) unsigned int homeChanQualChanged;
@property (nonatomic) BOOL hasChanSwitchEvent;
@property (nonatomic) unsigned int chanSwitchEvent;
@property (nonatomic) BOOL hasRoamPrep;
@property (nonatomic) unsigned int roamPrep;
@property (nonatomic) BOOL hasRoamScanStart;
@property (nonatomic) unsigned int roamScanStart;
@property (nonatomic) BOOL hasRoamScanEnd;
@property (nonatomic) unsigned int roamScanEnd;
@property (nonatomic) BOOL hasScanResults;
@property (nonatomic) unsigned int scanResults;
@property (nonatomic) BOOL hasScanSummary;
@property (nonatomic) unsigned int scanSummary;
@property (nonatomic) BOOL hasScanDone;
@property (nonatomic) unsigned int scanDone;
@property (nonatomic) BOOL hasScanInternalDone;
@property (nonatomic) unsigned int scanInternalDone;
@property (nonatomic) BOOL hasBssDisallowEvent;
@property (nonatomic) unsigned int bssDisallowEvent;
@property (nonatomic) BOOL hasSlowWiFiSymptom;
@property (nonatomic) unsigned int slowWiFiSymptom;
@property (nonatomic) BOOL hasDpsSymptom;
@property (nonatomic) unsigned int dpsSymptom;
@property (nonatomic) BOOL hasCrashTracerTrig;
@property (nonatomic) unsigned int crashTracerTrig;
@property (nonatomic) BOOL hasRc1Stats;
@property (nonatomic) unsigned int rc1Stats;
@property (nonatomic) BOOL hasRc2Stats;
@property (nonatomic) unsigned int rc2Stats;
@property (nonatomic) BOOL hasEscoTrafficInd;
@property (nonatomic) unsigned int escoTrafficInd;

- (id)copyWithZone:(struct _NSZone { } *)a0;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)a0;
- (void)mergeFrom:(id)a0;
- (BOOL)isEqual:(id)a0;
- (unsigned long long)hash;
- (void)writeTo:(id)a0;
- (BOOL)readFrom:(id)a0;
- (id)description;

@end
