@class NSData, NSString;

@interface AWDWiFiMetricLinkChangeData : PBCodable <NSCopying> {
    struct { int *list; unsigned long long count; unsigned long long size; } _bcnFrmsHistorys;
    struct { int *list; unsigned long long count; unsigned long long size; } _bcnPerHistorys;
    struct { int *list; unsigned long long count; unsigned long long size; } _fwTxFrmsHistorys;
    struct { int *list; unsigned long long count; unsigned long long size; } _fwTxPerHistorys;
    struct { int *list; unsigned long long count; unsigned long long size; } _rssiHistorys;
    struct { int *list; unsigned long long count; unsigned long long size; } _txFrmsHistorys;
    struct { int *list; unsigned long long count; unsigned long long size; } _txPerHistorys;
    struct { unsigned char associationDuration : 1; unsigned char timestamp : 1; unsigned char akmSuites : 1; unsigned char capabilities : 1; unsigned char channel : 1; unsigned char channelSwitchDuringHostSleep : 1; unsigned char channelSwitchDuringHostWake : 1; unsigned char channelWidth : 1; unsigned char enhancedSecurityType : 1; unsigned char flags : 1; unsigned char gatewayARPHistory : 1; unsigned char htASel : 1; unsigned char htAmpduParams : 1; unsigned char htExtended : 1; unsigned char htInfo : 1; unsigned char htTxBf : 1; unsigned char mcastCipher : 1; unsigned char phyMode : 1; unsigned char reason : 1; unsigned char rxCSAFrames : 1; unsigned char securityType : 1; unsigned char subreason : 1; unsigned char ucastCipher : 1; unsigned char vhtInfo : 1; unsigned char wpaProtocol : 1; unsigned char isInVol : 1; unsigned char isLinkUp : 1; } _has;
}

@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) unsigned long long timestamp;
@property (readonly, nonatomic) unsigned long long rssiHistorysCount;
@property (readonly, nonatomic) int *rssiHistorys;
@property (nonatomic) BOOL hasIsLinkUp;
@property (nonatomic) BOOL isLinkUp;
@property (nonatomic) BOOL hasIsInVol;
@property (nonatomic) BOOL isInVol;
@property (nonatomic) BOOL hasReason;
@property (nonatomic) unsigned int reason;
@property (nonatomic) BOOL hasSubreason;
@property (nonatomic) unsigned int subreason;
@property (nonatomic) BOOL hasChannel;
@property (nonatomic) unsigned int channel;
@property (nonatomic) BOOL hasChannelWidth;
@property (nonatomic) unsigned int channelWidth;
@property (nonatomic) BOOL hasPhyMode;
@property (nonatomic) unsigned int phyMode;
@property (nonatomic) BOOL hasFlags;
@property (nonatomic) unsigned int flags;
@property (readonly, nonatomic) BOOL hasOui;
@property (retain, nonatomic) NSData *oui;
@property (nonatomic) BOOL hasSecurityType;
@property (nonatomic) unsigned int securityType;
@property (nonatomic) BOOL hasWpaProtocol;
@property (nonatomic) unsigned int wpaProtocol;
@property (nonatomic) BOOL hasMcastCipher;
@property (nonatomic) unsigned int mcastCipher;
@property (nonatomic) BOOL hasUcastCipher;
@property (nonatomic) unsigned int ucastCipher;
@property (nonatomic) BOOL hasAkmSuites;
@property (nonatomic) unsigned int akmSuites;
@property (nonatomic) BOOL hasCapabilities;
@property (nonatomic) unsigned int capabilities;
@property (nonatomic) BOOL hasEnhancedSecurityType;
@property (nonatomic) unsigned int enhancedSecurityType;
@property (nonatomic) BOOL hasHtInfo;
@property (nonatomic) unsigned int htInfo;
@property (nonatomic) BOOL hasHtExtended;
@property (nonatomic) unsigned int htExtended;
@property (nonatomic) BOOL hasHtTxBf;
@property (nonatomic) unsigned int htTxBf;
@property (nonatomic) BOOL hasHtASel;
@property (nonatomic) unsigned int htASel;
@property (nonatomic) BOOL hasHtAmpduParams;
@property (nonatomic) unsigned int htAmpduParams;
@property (readonly, nonatomic) BOOL hasHtSupportedMcsSet;
@property (retain, nonatomic) NSData *htSupportedMcsSet;
@property (nonatomic) BOOL hasVhtInfo;
@property (nonatomic) unsigned int vhtInfo;
@property (readonly, nonatomic) BOOL hasVhtSupportedMcsSet;
@property (retain, nonatomic) NSData *vhtSupportedMcsSet;
@property (readonly, nonatomic) unsigned long long txPerHistorysCount;
@property (readonly, nonatomic) int *txPerHistorys;
@property (readonly, nonatomic) unsigned long long txFrmsHistorysCount;
@property (readonly, nonatomic) int *txFrmsHistorys;
@property (readonly, nonatomic) unsigned long long fwTxPerHistorysCount;
@property (readonly, nonatomic) int *fwTxPerHistorys;
@property (readonly, nonatomic) unsigned long long fwTxFrmsHistorysCount;
@property (readonly, nonatomic) int *fwTxFrmsHistorys;
@property (readonly, nonatomic) unsigned long long bcnPerHistorysCount;
@property (readonly, nonatomic) int *bcnPerHistorys;
@property (readonly, nonatomic) unsigned long long bcnFrmsHistorysCount;
@property (readonly, nonatomic) int *bcnFrmsHistorys;
@property (nonatomic) BOOL hasGatewayARPHistory;
@property (nonatomic) unsigned int gatewayARPHistory;
@property (readonly, nonatomic) BOOL hasLocale;
@property (retain, nonatomic) NSString *locale;
@property (nonatomic) BOOL hasAssociationDuration;
@property (nonatomic) double associationDuration;
@property (readonly, nonatomic) BOOL hasWpsResponseType;
@property (retain, nonatomic) NSString *wpsResponseType;
@property (readonly, nonatomic) BOOL hasWpsManufacturerElement;
@property (retain, nonatomic) NSString *wpsManufacturerElement;
@property (readonly, nonatomic) BOOL hasWpsModelName;
@property (retain, nonatomic) NSString *wpsModelName;
@property (readonly, nonatomic) BOOL hasWpsModelNumber;
@property (retain, nonatomic) NSString *wpsModelNumber;
@property (readonly, nonatomic) BOOL hasCountryCode;
@property (retain, nonatomic) NSString *countryCode;
@property (readonly, nonatomic) BOOL hasWpsPrimaryDeviceTypeCategory;
@property (retain, nonatomic) NSString *wpsPrimaryDeviceTypeCategory;
@property (readonly, nonatomic) BOOL hasWpsPrimaryDeviceTypeSubCategory;
@property (retain, nonatomic) NSString *wpsPrimaryDeviceTypeSubCategory;
@property (readonly, nonatomic) BOOL hasWpsDeviceNameElement;
@property (retain, nonatomic) NSString *wpsDeviceNameElement;
@property (readonly, nonatomic) BOOL hasWpsDeviceNameData;
@property (retain, nonatomic) NSString *wpsDeviceNameData;
@property (readonly, nonatomic) BOOL hasWpsConfigMethods;
@property (retain, nonatomic) NSString *wpsConfigMethods;
@property (readonly, nonatomic) BOOL hasLocaleSource;
@property (retain, nonatomic) NSString *localeSource;
@property (nonatomic) BOOL hasRxCSAFrames;
@property (nonatomic) unsigned int rxCSAFrames;
@property (nonatomic) BOOL hasChannelSwitchDuringHostSleep;
@property (nonatomic) unsigned int channelSwitchDuringHostSleep;
@property (nonatomic) BOOL hasChannelSwitchDuringHostWake;
@property (nonatomic) unsigned int channelSwitchDuringHostWake;
@property (readonly, nonatomic) BOOL hasPrivateMacType;
@property (retain, nonatomic) NSString *privateMacType;

- (int)fwTxFrmsHistoryAtIndex:(unsigned long long)a0;
- (int)txFrmsHistoryAtIndex:(unsigned long long)a0;
- (void)setRssiHistorys:(int *)a0 count:(unsigned long long)a1;
- (int)rssiHistoryAtIndex:(unsigned long long)a0;
- (void)addRssiHistory:(int)a0;
- (void)clearTxFrmsHistorys;
- (void)addBcnPerHistory:(int)a0;
- (void)clearTxPerHistorys;
- (void)setTxFrmsHistorys:(int *)a0 count:(unsigned long long)a1;
- (int)bcnPerHistoryAtIndex:(unsigned long long)a0;
- (int)fwTxPerHistoryAtIndex:(unsigned long long)a0;
- (void)addTxPerHistory:(int)a0;
- (void)setBcnPerHistorys:(int *)a0 count:(unsigned long long)a1;
- (void)clearFwTxFrmsHistorys;
- (void)addTxFrmsHistory:(int)a0;
- (void)setBcnFrmsHistorys:(int *)a0 count:(unsigned long long)a1;
- (void)addFwTxFrmsHistory:(int)a0;
- (void)setFwTxFrmsHistorys:(int *)a0 count:(unsigned long long)a1;
- (void)setFwTxPerHistorys:(int *)a0 count:(unsigned long long)a1;
- (void)setTxPerHistorys:(int *)a0 count:(unsigned long long)a1;
- (id)copyWithZone:(struct _NSZone { } *)a0;
- (id)dictionaryRepresentation;
- (void)addFwTxPerHistory:(int)a0;
- (void)copyTo:(id)a0;
- (void)dealloc;
- (void)mergeFrom:(id)a0;
- (BOOL)isEqual:(id)a0;
- (void)clearFwTxPerHistorys;
- (unsigned long long)hash;
- (void)addBcnFrmsHistory:(int)a0;
- (int)bcnFrmsHistoryAtIndex:(unsigned long long)a0;
- (void)writeTo:(id)a0;
- (BOOL)readFrom:(id)a0;
- (void)clearRssiHistorys;
- (id)description;
- (void)clearBcnPerHistorys;
- (void)clearBcnFrmsHistorys;
- (int)txPerHistoryAtIndex:(unsigned long long)a0;

@end
