blank_issues_enabled: false
contact_links:
    -
        name: Other feature request & feedback
        url: https://github.com/akariicafe#-feedback
        about: This repository does not handle feature requests or other types of feedback.
