@interface AWDLinkQualityMeasurements : PBCodable <NSCopying> {
    struct { unsigned char aPTxDataStall : 1; unsigned char accessPointOUI : 1; unsigned char availWLANDurMS : 1; unsigned char availWLANRxDurMS : 1; unsigned char availWLANTxDurMS : 1; unsigned char avgTxLatencyMS : 1; unsigned char bTAntennaDurMS : 1; unsigned char baselineThroughput : 1; unsigned char cCA : 1; unsigned char concurrentIntDurMS : 1; unsigned char delayedThroughput : 1; unsigned char expectedThroughput : 1; unsigned char highRxDataPERFalse : 1; unsigned char highRxDataPERTrue : 1; unsigned char highRxDecryptErrsFalse : 1; unsigned char highRxDecryptErrsTrue : 1; unsigned char highRxDupsFalse : 1; unsigned char highRxDupsTrue : 1; unsigned char highRxFCSErrsFalse : 1; unsigned char highRxFCSErrsTrue : 1; unsigned char highRxOverflowsFalse : 1; unsigned char highRxOverflowsTrue : 1; unsigned char highRxPhyPERFalse : 1; unsigned char highRxPhyPERTrue : 1; unsigned char highRxReplaysFalse : 1; unsigned char highRxReplaysTrue : 1; unsigned char highRxRetriesFalse : 1; unsigned char highRxRetriesTrue : 1; unsigned char highTxLatencyFalse : 1; unsigned char highTxLatencyTrue : 1; unsigned char highTxPerFalse : 1; unsigned char highTxPerTrue : 1; unsigned char highTxRetriesFalse : 1; unsigned char highTxRetriesTrue : 1; unsigned char infraDutyCycle : 1; unsigned char inputThroughput : 1; unsigned char is2GBand : 1; unsigned char isFGTraffic : 1; unsigned char lTECoexDurationMS : 1; unsigned char lastScanReason : 1; unsigned char lowAvailWLANDurFalse : 1; unsigned char lowAvailWLANDurTrue : 1; unsigned char lowAvailWLANRxDurFalse : 1; unsigned char lowAvailWLANRxDurTrue : 1; unsigned char lowAvailWLANTxDurFalse : 1; unsigned char lowAvailWLANTxDurTrue : 1; unsigned char lowTxAMPDUDensityFalse : 1; unsigned char lowTxAMPDUDensityTrue : 1; unsigned char lowTxPhyRateFalse : 1; unsigned char lowTxPhyRateTrue : 1; unsigned char maxQueueFullDurMS : 1; unsigned char measurementDurMS : 1; unsigned char offChanDurMS : 1; unsigned char outputThroughput : 1; unsigned char phyRxActivityDurMS : 1; unsigned char phyTxActivityDurMS : 1; unsigned char rC1CoexDurationMS : 1; unsigned char rC2CoexDurationMS : 1; unsigned char rSSI : 1; unsigned char rxAmpduTxBaMismatch : 1; unsigned char rxCRSErrs : 1; unsigned char rxDecryErrs : 1; unsigned char rxDupErrs : 1; unsigned char rxFCSErrs : 1; unsigned char rxFrames : 1; unsigned char rxGoodPlcps : 1; unsigned char rxLowFrameCountFalse : 1; unsigned char rxLowFrameCountTrue : 1; unsigned char rxOvflErrs : 1; unsigned char rxPLCPErrs : 1; unsigned char rxPhyRate : 1; unsigned char rxReplayErrs : 1; unsigned char rxRetries : 1; unsigned char rxThroughput : 1; unsigned char sNR : 1; unsigned char symptomsFails : 1; unsigned char tVPMActiveDurationMS : 1; unsigned char testThroughput : 1; unsigned char timeSinceLastRecovery : 1; unsigned char timestamp : 1; unsigned char txAMPDUDensity : 1; unsigned char txCompBytes : 1; unsigned char txCompPkts : 1; unsigned char txDelayBytes : 1; unsigned char txExpectedAMPDUDensity : 1; unsigned char txFails : 1; unsigned char txFrames : 1; unsigned char txLowFrameCountFalse : 1; unsigned char txLowFrameCountTrue : 1; unsigned char txOutputBelowExpectedFalse : 1; unsigned char txOutputBelowExpectedTrue : 1; unsigned char txOutputBelowInputFalse : 1; unsigned char txOutputBelowInputTrue : 1; unsigned char txPhyRate : 1; unsigned char txQueueFullFalse : 1; unsigned char txQueueFullTrue : 1; unsigned char txRetries : 1; unsigned char txSubBytes : 1; unsigned char txSubPkts : 1; } _has;
}

@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) unsigned long long timestamp;
@property (nonatomic) BOOL hasTxOutputBelowExpectedTrue;
@property (nonatomic) unsigned long long txOutputBelowExpectedTrue;
@property (nonatomic) BOOL hasTxOutputBelowExpectedFalse;
@property (nonatomic) unsigned long long txOutputBelowExpectedFalse;
@property (nonatomic) BOOL hasTxOutputBelowInputTrue;
@property (nonatomic) unsigned long long txOutputBelowInputTrue;
@property (nonatomic) BOOL hasTxOutputBelowInputFalse;
@property (nonatomic) unsigned long long txOutputBelowInputFalse;
@property (nonatomic) BOOL hasTxLowFrameCountTrue;
@property (nonatomic) unsigned long long txLowFrameCountTrue;
@property (nonatomic) BOOL hasTxLowFrameCountFalse;
@property (nonatomic) unsigned long long txLowFrameCountFalse;
@property (nonatomic) BOOL hasRxLowFrameCountTrue;
@property (nonatomic) unsigned long long rxLowFrameCountTrue;
@property (nonatomic) BOOL hasRxLowFrameCountFalse;
@property (nonatomic) unsigned long long rxLowFrameCountFalse;
@property (nonatomic) BOOL hasHighTxLatencyTrue;
@property (nonatomic) unsigned long long highTxLatencyTrue;
@property (nonatomic) BOOL hasHighTxLatencyFalse;
@property (nonatomic) unsigned long long highTxLatencyFalse;
@property (nonatomic) BOOL hasLowTxPhyRateTrue;
@property (nonatomic) unsigned long long lowTxPhyRateTrue;
@property (nonatomic) BOOL hasLowTxPhyRateFalse;
@property (nonatomic) unsigned long long lowTxPhyRateFalse;
@property (nonatomic) BOOL hasHighTxPerTrue;
@property (nonatomic) unsigned long long highTxPerTrue;
@property (nonatomic) BOOL hasHighTxPerFalse;
@property (nonatomic) unsigned long long highTxPerFalse;
@property (nonatomic) BOOL hasHighTxRetriesTrue;
@property (nonatomic) unsigned long long highTxRetriesTrue;
@property (nonatomic) BOOL hasHighTxRetriesFalse;
@property (nonatomic) unsigned long long highTxRetriesFalse;
@property (nonatomic) BOOL hasTxQueueFullTrue;
@property (nonatomic) unsigned long long txQueueFullTrue;
@property (nonatomic) BOOL hasTxQueueFullFalse;
@property (nonatomic) unsigned long long txQueueFullFalse;
@property (nonatomic) BOOL hasLowTxAMPDUDensityTrue;
@property (nonatomic) unsigned long long lowTxAMPDUDensityTrue;
@property (nonatomic) BOOL hasLowTxAMPDUDensityFalse;
@property (nonatomic) unsigned long long lowTxAMPDUDensityFalse;
@property (nonatomic) BOOL hasHighRxRetriesTrue;
@property (nonatomic) unsigned long long highRxRetriesTrue;
@property (nonatomic) BOOL hasHighRxRetriesFalse;
@property (nonatomic) unsigned long long highRxRetriesFalse;
@property (nonatomic) BOOL hasHighRxPhyPERTrue;
@property (nonatomic) unsigned long long highRxPhyPERTrue;
@property (nonatomic) BOOL hasHighRxPhyPERFalse;
@property (nonatomic) unsigned long long highRxPhyPERFalse;
@property (nonatomic) BOOL hasHighRxFCSErrsTrue;
@property (nonatomic) unsigned long long highRxFCSErrsTrue;
@property (nonatomic) BOOL hasHighRxFCSErrsFalse;
@property (nonatomic) unsigned long long highRxFCSErrsFalse;
@property (nonatomic) BOOL hasHighRxOverflowsTrue;
@property (nonatomic) unsigned long long highRxOverflowsTrue;
@property (nonatomic) BOOL hasHighRxOverflowsFalse;
@property (nonatomic) unsigned long long highRxOverflowsFalse;
@property (nonatomic) BOOL hasHighRxDupsTrue;
@property (nonatomic) unsigned long long highRxDupsTrue;
@property (nonatomic) BOOL hasHighRxDupsFalse;
@property (nonatomic) unsigned long long highRxDupsFalse;
@property (nonatomic) BOOL hasHighRxReplaysTrue;
@property (nonatomic) unsigned long long highRxReplaysTrue;
@property (nonatomic) BOOL hasHighRxReplaysFalse;
@property (nonatomic) unsigned long long highRxReplaysFalse;
@property (nonatomic) BOOL hasHighRxDecryptErrsTrue;
@property (nonatomic) unsigned long long highRxDecryptErrsTrue;
@property (nonatomic) BOOL hasHighRxDecryptErrsFalse;
@property (nonatomic) unsigned long long highRxDecryptErrsFalse;
@property (nonatomic) BOOL hasHighRxDataPERTrue;
@property (nonatomic) unsigned long long highRxDataPERTrue;
@property (nonatomic) BOOL hasHighRxDataPERFalse;
@property (nonatomic) unsigned long long highRxDataPERFalse;
@property (nonatomic) BOOL hasLowAvailWLANDurTrue;
@property (nonatomic) unsigned long long lowAvailWLANDurTrue;
@property (nonatomic) BOOL hasLowAvailWLANDurFalse;
@property (nonatomic) unsigned long long lowAvailWLANDurFalse;
@property (nonatomic) BOOL hasLowAvailWLANTxDurTrue;
@property (nonatomic) unsigned long long lowAvailWLANTxDurTrue;
@property (nonatomic) BOOL hasLowAvailWLANTxDurFalse;
@property (nonatomic) unsigned long long lowAvailWLANTxDurFalse;
@property (nonatomic) BOOL hasLowAvailWLANRxDurTrue;
@property (nonatomic) unsigned long long lowAvailWLANRxDurTrue;
@property (nonatomic) BOOL hasLowAvailWLANRxDurFalse;
@property (nonatomic) unsigned long long lowAvailWLANRxDurFalse;
@property (nonatomic) BOOL hasCCA;
@property (nonatomic) unsigned long long cCA;
@property (nonatomic) BOOL hasRSSI;
@property (nonatomic) long long rSSI;
@property (nonatomic) BOOL hasTxPhyRate;
@property (nonatomic) unsigned long long txPhyRate;
@property (nonatomic) BOOL hasRxPhyRate;
@property (nonatomic) unsigned long long rxPhyRate;
@property (nonatomic) BOOL hasTxAMPDUDensity;
@property (nonatomic) unsigned long long txAMPDUDensity;
@property (nonatomic) BOOL hasMeasurementDurMS;
@property (nonatomic) unsigned long long measurementDurMS;
@property (nonatomic) BOOL hasConcurrentIntDurMS;
@property (nonatomic) unsigned long long concurrentIntDurMS;
@property (nonatomic) BOOL hasTVPMActiveDurationMS;
@property (nonatomic) unsigned long long tVPMActiveDurationMS;
@property (nonatomic) BOOL hasPhyTxActivityDurMS;
@property (nonatomic) unsigned long long phyTxActivityDurMS;
@property (nonatomic) BOOL hasPhyRxActivityDurMS;
@property (nonatomic) unsigned long long phyRxActivityDurMS;
@property (nonatomic) BOOL hasTxSubBytes;
@property (nonatomic) unsigned long long txSubBytes;
@property (nonatomic) BOOL hasTxCompBytes;
@property (nonatomic) unsigned long long txCompBytes;
@property (nonatomic) BOOL hasTxDelayBytes;
@property (nonatomic) unsigned long long txDelayBytes;
@property (nonatomic) BOOL hasOffChanDurMS;
@property (nonatomic) unsigned long long offChanDurMS;
@property (nonatomic) BOOL hasTxSubPkts;
@property (nonatomic) unsigned long long txSubPkts;
@property (nonatomic) BOOL hasTxCompPkts;
@property (nonatomic) unsigned long long txCompPkts;
@property (nonatomic) BOOL hasMaxQueueFullDurMS;
@property (nonatomic) unsigned long long maxQueueFullDurMS;
@property (nonatomic) BOOL hasAvgTxLatencyMS;
@property (nonatomic) unsigned long long avgTxLatencyMS;
@property (nonatomic) BOOL hasBTAntennaDurMS;
@property (nonatomic) unsigned long long bTAntennaDurMS;
@property (nonatomic) BOOL hasOutputThroughput;
@property (nonatomic) unsigned long long outputThroughput;
@property (nonatomic) BOOL hasInputThroughput;
@property (nonatomic) unsigned long long inputThroughput;
@property (nonatomic) BOOL hasExpectedThroughput;
@property (nonatomic) unsigned long long expectedThroughput;
@property (nonatomic) BOOL hasDelayedThroughput;
@property (nonatomic) unsigned long long delayedThroughput;
@property (nonatomic) BOOL hasAvailWLANDurMS;
@property (nonatomic) unsigned long long availWLANDurMS;
@property (nonatomic) BOOL hasAvailWLANTxDurMS;
@property (nonatomic) unsigned long long availWLANTxDurMS;
@property (nonatomic) BOOL hasAvailWLANRxDurMS;
@property (nonatomic) unsigned long long availWLANRxDurMS;
@property (nonatomic) BOOL hasTxRetries;
@property (nonatomic) unsigned long long txRetries;
@property (nonatomic) BOOL hasTxFails;
@property (nonatomic) unsigned long long txFails;
@property (nonatomic) BOOL hasTxFrames;
@property (nonatomic) unsigned long long txFrames;
@property (nonatomic) BOOL hasRxOvflErrs;
@property (nonatomic) unsigned long long rxOvflErrs;
@property (nonatomic) BOOL hasRxFCSErrs;
@property (nonatomic) unsigned long long rxFCSErrs;
@property (nonatomic) BOOL hasRxPLCPErrs;
@property (nonatomic) unsigned long long rxPLCPErrs;
@property (nonatomic) BOOL hasRxCRSErrs;
@property (nonatomic) unsigned long long rxCRSErrs;
@property (nonatomic) BOOL hasRxDupErrs;
@property (nonatomic) unsigned long long rxDupErrs;
@property (nonatomic) BOOL hasRxReplayErrs;
@property (nonatomic) unsigned long long rxReplayErrs;
@property (nonatomic) BOOL hasRxDecryErrs;
@property (nonatomic) unsigned long long rxDecryErrs;
@property (nonatomic) BOOL hasRxRetries;
@property (nonatomic) unsigned long long rxRetries;
@property (nonatomic) BOOL hasRxGoodPlcps;
@property (nonatomic) unsigned long long rxGoodPlcps;
@property (nonatomic) BOOL hasRxFrames;
@property (nonatomic) unsigned long long rxFrames;
@property (nonatomic) BOOL hasSNR;
@property (nonatomic) unsigned long long sNR;
@property (nonatomic) BOOL hasTxExpectedAMPDUDensity;
@property (nonatomic) unsigned long long txExpectedAMPDUDensity;
@property (nonatomic) BOOL hasRC1CoexDurationMS;
@property (nonatomic) unsigned long long rC1CoexDurationMS;
@property (nonatomic) BOOL hasRC2CoexDurationMS;
@property (nonatomic) unsigned long long rC2CoexDurationMS;
@property (nonatomic) BOOL hasLTECoexDurationMS;
@property (nonatomic) unsigned long long lTECoexDurationMS;
@property (nonatomic) BOOL hasRxThroughput;
@property (nonatomic) unsigned long long rxThroughput;
@property (nonatomic) BOOL hasAPTxDataStall;
@property (nonatomic) unsigned long long aPTxDataStall;
@property (nonatomic) BOOL hasRxAmpduTxBaMismatch;
@property (nonatomic) unsigned long long rxAmpduTxBaMismatch;
@property (nonatomic) BOOL hasSymptomsFails;
@property (nonatomic) unsigned long long symptomsFails;
@property (nonatomic) BOOL hasIs2GBand;
@property (nonatomic) unsigned long long is2GBand;
@property (nonatomic) BOOL hasIsFGTraffic;
@property (nonatomic) unsigned long long isFGTraffic;
@property (nonatomic) BOOL hasBaselineThroughput;
@property (nonatomic) unsigned long long baselineThroughput;
@property (nonatomic) BOOL hasTestThroughput;
@property (nonatomic) unsigned long long testThroughput;
@property (nonatomic) BOOL hasInfraDutyCycle;
@property (nonatomic) unsigned long long infraDutyCycle;
@property (nonatomic) BOOL hasLastScanReason;
@property (nonatomic) unsigned long long lastScanReason;
@property (nonatomic) BOOL hasAccessPointOUI;
@property (nonatomic) unsigned long long accessPointOUI;
@property (nonatomic) BOOL hasTimeSinceLastRecovery;
@property (nonatomic) unsigned long long timeSinceLastRecovery;

- (id)copyWithZone:(struct _NSZone { } *)a0;
- (void)mergeFrom:(id)a0;
- (BOOL)readFrom:(id)a0;
- (unsigned long long)hash;
- (void)writeTo:(id)a0;
- (id)description;
- (void)copyTo:(id)a0;
- (BOOL)isEqual:(id)a0;
- (id)dictionaryRepresentation;

@end
