@class NSString, AWDNWL2Report, NSMutableArray, AWDNWDeviceReport;

@interface AWDNWConnectionReport : PBCodable <NSCopying> {
    struct { unsigned char bestRTT : 1; unsigned char bytesDuplicate : 1; unsigned char bytesIn : 1; unsigned char bytesOut : 1; unsigned char bytesOutOfOrder : 1; unsigned char bytesRetransmitted : 1; unsigned char connectedAddressIndex : 1; unsigned char connectionReuseCount : 1; unsigned char currentRTT : 1; unsigned char dataStallCount : 1; unsigned char flowConnectMilliseconds : 1; unsigned char flowDurationMilliseconds : 1; unsigned char ipv4AddressCount : 1; unsigned char ipv4DNSServerCount : 1; unsigned char ipv6AddressCount : 1; unsigned char ipv6DNSServerCount : 1; unsigned char multipathBytesInCell : 1; unsigned char multipathBytesInInitial : 1; unsigned char multipathBytesInWiFi : 1; unsigned char multipathBytesOutCell : 1; unsigned char multipathBytesOutInitial : 1; unsigned char multipathBytesOutWiFi : 1; unsigned char multipathServiceType : 1; unsigned char packetsIn : 1; unsigned char packetsOut : 1; unsigned char pathTriggerMilliseconds : 1; unsigned char proxyMilliseconds : 1; unsigned char rTTvariance : 1; unsigned char resolutionMilliseconds : 1; unsigned char secondsSinceInterfaceChange : 1; unsigned char smoothedRTT : 1; unsigned char synRetransmissionCount : 1; unsigned char timestamp : 1; unsigned char tlsMilliseconds : 1; unsigned char trafficClass : 1; unsigned char appleApp : 1; unsigned char appleHost : 1; unsigned char connectedAddressFamily : 1; unsigned char connectedInterfaceType : 1; unsigned char connectionMode : 1; unsigned char dnsProtocol : 1; unsigned char dnsProvider : 1; unsigned char failureReason : 1; unsigned char firstAddressFamily : 1; unsigned char stackLevel : 1; unsigned char tlsVersion : 1; unsigned char transportProtocol : 1; unsigned char usedProxyType : 1; unsigned char customProxyConfigured : 1; unsigned char fallbackEligible : 1; unsigned char firstParty : 1; unsigned char ipv4Available : 1; unsigned char ipv6Available : 1; unsigned char isDaemon : 1; unsigned char isPathConstrained : 1; unsigned char isPathExpensive : 1; unsigned char multipathConfigured : 1; unsigned char prohibitsConstrained : 1; unsigned char prohibitsExpensive : 1; unsigned char resolutionRequired : 1; unsigned char synthesizedExtraIPv6Address : 1; unsigned char synthesizedIPv6Address : 1; unsigned char systemProxyConfigured : 1; unsigned char tfoConfigured : 1; unsigned char tfoUsed : 1; unsigned char tlsConfigured : 1; unsigned char tlsHandshakeTimedOut : 1; unsigned char tlsVersionTimeout : 1; unsigned char triggeredPath : 1; unsigned char usedFallback : 1; unsigned char weakFallback : 1; } _has;
}

@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) unsigned long long timestamp;
@property (nonatomic) BOOL hasTriggeredPath;
@property (nonatomic) BOOL triggeredPath;
@property (nonatomic) BOOL hasSystemProxyConfigured;
@property (nonatomic) BOOL systemProxyConfigured;
@property (nonatomic) BOOL hasCustomProxyConfigured;
@property (nonatomic) BOOL customProxyConfigured;
@property (nonatomic) BOOL hasUsedProxyType;
@property (nonatomic) int usedProxyType;
@property (nonatomic) BOOL hasFallbackEligible;
@property (nonatomic) BOOL fallbackEligible;
@property (nonatomic) BOOL hasWeakFallback;
@property (nonatomic) BOOL weakFallback;
@property (nonatomic) BOOL hasUsedFallback;
@property (nonatomic) BOOL usedFallback;
@property (nonatomic) BOOL hasResolutionRequired;
@property (nonatomic) BOOL resolutionRequired;
@property (nonatomic) BOOL hasTlsConfigured;
@property (nonatomic) BOOL tlsConfigured;
@property (nonatomic) BOOL hasTfoConfigured;
@property (nonatomic) BOOL tfoConfigured;
@property (nonatomic) BOOL hasMultipathConfigured;
@property (nonatomic) BOOL multipathConfigured;
@property (nonatomic) BOOL hasTrafficClass;
@property (nonatomic) unsigned long long trafficClass;
@property (nonatomic) BOOL hasFailureReason;
@property (nonatomic) int failureReason;
@property (nonatomic) BOOL hasPathTriggerMilliseconds;
@property (nonatomic) unsigned long long pathTriggerMilliseconds;
@property (nonatomic) BOOL hasResolutionMilliseconds;
@property (nonatomic) unsigned long long resolutionMilliseconds;
@property (nonatomic) BOOL hasProxyMilliseconds;
@property (nonatomic) unsigned long long proxyMilliseconds;
@property (nonatomic) BOOL hasFlowConnectMilliseconds;
@property (nonatomic) unsigned long long flowConnectMilliseconds;
@property (nonatomic) BOOL hasTlsMilliseconds;
@property (nonatomic) unsigned long long tlsMilliseconds;
@property (nonatomic) BOOL hasFlowDurationMilliseconds;
@property (nonatomic) unsigned long long flowDurationMilliseconds;
@property (nonatomic) BOOL hasIpv4AddressCount;
@property (nonatomic) unsigned long long ipv4AddressCount;
@property (nonatomic) BOOL hasIpv6AddressCount;
@property (nonatomic) unsigned long long ipv6AddressCount;
@property (nonatomic) BOOL hasSynthesizedIPv6Address;
@property (nonatomic) BOOL synthesizedIPv6Address;
@property (nonatomic) BOOL hasFirstAddressFamily;
@property (nonatomic) int firstAddressFamily;
@property (nonatomic) BOOL hasConnectedAddressFamily;
@property (nonatomic) int connectedAddressFamily;
@property (nonatomic) BOOL hasConnectedAddressIndex;
@property (nonatomic) unsigned long long connectedAddressIndex;
@property (nonatomic) BOOL hasConnectedInterfaceType;
@property (nonatomic) int connectedInterfaceType;
@property (nonatomic) BOOL hasConnectionReuseCount;
@property (nonatomic) unsigned long long connectionReuseCount;
@property (nonatomic) BOOL hasDataStallCount;
@property (nonatomic) unsigned long long dataStallCount;
@property (nonatomic) BOOL hasConnectionMode;
@property (nonatomic) int connectionMode;
@property (nonatomic) BOOL hasAppleHost;
@property (nonatomic) int appleHost;
@property (nonatomic) BOOL hasAppleApp;
@property (nonatomic) int appleApp;
@property (nonatomic) BOOL hasTlsVersion;
@property (nonatomic) int tlsVersion;
@property (nonatomic) BOOL hasStackLevel;
@property (nonatomic) int stackLevel;
@property (nonatomic) BOOL hasIpv4Available;
@property (nonatomic) BOOL ipv4Available;
@property (nonatomic) BOOL hasIpv6Available;
@property (nonatomic) BOOL ipv6Available;
@property (nonatomic) BOOL hasIpv4DNSServerCount;
@property (nonatomic) unsigned long long ipv4DNSServerCount;
@property (nonatomic) BOOL hasIpv6DNSServerCount;
@property (nonatomic) unsigned long long ipv6DNSServerCount;
@property (nonatomic) BOOL hasTlsVersionTimeout;
@property (nonatomic) BOOL tlsVersionTimeout;
@property (nonatomic) BOOL hasSynthesizedExtraIPv6Address;
@property (nonatomic) BOOL synthesizedExtraIPv6Address;
@property (nonatomic) BOOL hasBytesIn;
@property (nonatomic) unsigned long long bytesIn;
@property (nonatomic) BOOL hasBytesOut;
@property (nonatomic) unsigned long long bytesOut;
@property (nonatomic) BOOL hasBytesDuplicate;
@property (nonatomic) unsigned long long bytesDuplicate;
@property (nonatomic) BOOL hasBytesOutOfOrder;
@property (nonatomic) unsigned long long bytesOutOfOrder;
@property (nonatomic) BOOL hasBytesRetransmitted;
@property (nonatomic) unsigned long long bytesRetransmitted;
@property (nonatomic) BOOL hasPacketsIn;
@property (nonatomic) unsigned long long packetsIn;
@property (nonatomic) BOOL hasPacketsOut;
@property (nonatomic) unsigned long long packetsOut;
@property (nonatomic) BOOL hasCurrentRTT;
@property (nonatomic) unsigned long long currentRTT;
@property (nonatomic) BOOL hasSmoothedRTT;
@property (nonatomic) unsigned long long smoothedRTT;
@property (nonatomic) BOOL hasBestRTT;
@property (nonatomic) unsigned long long bestRTT;
@property (nonatomic) BOOL hasRTTvariance;
@property (nonatomic) unsigned long long rTTvariance;
@property (nonatomic) BOOL hasSynRetransmissionCount;
@property (nonatomic) unsigned long long synRetransmissionCount;
@property (nonatomic) BOOL hasTfoUsed;
@property (nonatomic) BOOL tfoUsed;
@property (nonatomic) BOOL hasMultipathServiceType;
@property (nonatomic) unsigned long long multipathServiceType;
@property (nonatomic) BOOL hasFirstParty;
@property (nonatomic) BOOL firstParty;
@property (nonatomic) BOOL hasMultipathBytesInCell;
@property (nonatomic) unsigned long long multipathBytesInCell;
@property (nonatomic) BOOL hasMultipathBytesOutCell;
@property (nonatomic) unsigned long long multipathBytesOutCell;
@property (nonatomic) BOOL hasMultipathBytesInWiFi;
@property (nonatomic) unsigned long long multipathBytesInWiFi;
@property (nonatomic) BOOL hasMultipathBytesOutWiFi;
@property (nonatomic) unsigned long long multipathBytesOutWiFi;
@property (nonatomic) BOOL hasMultipathBytesInInitial;
@property (nonatomic) unsigned long long multipathBytesInInitial;
@property (nonatomic) BOOL hasMultipathBytesOutInitial;
@property (nonatomic) unsigned long long multipathBytesOutInitial;
@property (nonatomic) BOOL hasSecondsSinceInterfaceChange;
@property (nonatomic) unsigned long long secondsSinceInterfaceChange;
@property (nonatomic) BOOL hasIsDaemon;
@property (nonatomic) BOOL isDaemon;
@property (readonly, nonatomic) BOOL hasProcessName;
@property (retain, nonatomic) NSString *processName;
@property (retain, nonatomic) NSMutableArray *activities;
@property (readonly, nonatomic) BOOL hasConnectionUUID;
@property (retain, nonatomic) NSString *connectionUUID;
@property (nonatomic) BOOL hasTlsHandshakeTimedOut;
@property (nonatomic) BOOL tlsHandshakeTimedOut;
@property (nonatomic) BOOL hasIsPathExpensive;
@property (nonatomic) BOOL isPathExpensive;
@property (nonatomic) BOOL hasIsPathConstrained;
@property (nonatomic) BOOL isPathConstrained;
@property (nonatomic) BOOL hasProhibitsExpensive;
@property (nonatomic) BOOL prohibitsExpensive;
@property (nonatomic) BOOL hasProhibitsConstrained;
@property (nonatomic) BOOL prohibitsConstrained;
@property (readonly, nonatomic) BOOL hasL2Report;
@property (retain, nonatomic) AWDNWL2Report *l2Report;
@property (readonly, nonatomic) BOOL hasDeviceReport;
@property (retain, nonatomic) AWDNWDeviceReport *deviceReport;
@property (nonatomic) BOOL hasTransportProtocol;
@property (nonatomic) int transportProtocol;
@property (nonatomic) BOOL hasDnsProtocol;
@property (nonatomic) int dnsProtocol;
@property (nonatomic) BOOL hasDnsProvider;
@property (nonatomic) int dnsProvider;
@property (readonly, nonatomic) BOOL hasBundleID;
@property (retain, nonatomic) NSString *bundleID;
@property (readonly, nonatomic) BOOL hasEffectiveBundleID;
@property (retain, nonatomic) NSString *effectiveBundleID;

+ (Class)activitiesType;

- (id)connectedAddressFamilyAsString:(int)a0;
- (int)StringAsAppleHost:(id)a0;
- (id)failureReasonAsString:(int)a0;
- (int)StringAsConnectedAddressFamily:(id)a0;
- (id)copyWithZone:(struct _NSZone { } *)a0;
- (void)mergeFrom:(id)a0;
- (int)StringAsDnsProvider:(id)a0;
- (void)dealloc;
- (int)StringAsUsedProxyType:(id)a0;
- (id)dnsProviderAsString:(int)a0;
- (id)appleAppAsString:(int)a0;
- (void)addActivities:(id)a0;
- (BOOL)readFrom:(id)a0;
- (int)StringAsFirstAddressFamily:(id)a0;
- (id)connectionModeAsString:(int)a0;
- (id)dnsProtocolAsString:(int)a0;
- (unsigned long long)hash;
- (id)stackLevelAsString:(int)a0;
- (void)writeTo:(id)a0;
- (id)appleHostAsString:(int)a0;
- (int)StringAsAppleApp:(id)a0;
- (int)StringAsDnsProtocol:(id)a0;
- (id)description;
- (void)copyTo:(id)a0;
- (id)usedProxyTypeAsString:(int)a0;
- (BOOL)isEqual:(id)a0;
- (id)dictionaryRepresentation;
- (id)firstAddressFamilyAsString:(int)a0;
- (id)connectedInterfaceTypeAsString:(int)a0;
- (id)tlsVersionAsString:(int)a0;
- (int)StringAsTransportProtocol:(id)a0;
- (int)StringAsTlsVersion:(id)a0;
- (id)activitiesAtIndex:(unsigned long long)a0;
- (int)StringAsConnectedInterfaceType:(id)a0;
- (int)StringAsStackLevel:(id)a0;
- (id)transportProtocolAsString:(int)a0;
- (unsigned long long)activitiesCount;
- (int)StringAsConnectionMode:(id)a0;
- (int)StringAsFailureReason:(id)a0;
- (void)clearActivities;

@end
