@class AWDWifiAwdlD2dMigrationStats, NSMutableArray;

@interface AWDWiFiMetricsManagerAwdlUsage : PBCodable <NSCopying> {
    struct { unsigned char noServiceIdleTime : 1; unsigned char syncChangesCount : 1; unsigned char timestamp : 1; unsigned char advertiseAddFilteredCount : 1; unsigned char advertiseAddTotalCount : 1; unsigned char advertiseDeleteFilteredCount : 1; unsigned char advertiseDeleteTotalCount : 1; unsigned char appRxBytes : 1; unsigned char appTxBytes : 1; unsigned char browseAddFilteredCount : 1; unsigned char browseAddTotalCount : 1; unsigned char browseDeleteFilteredCount : 1; unsigned char browseDeleteTotalCount : 1; unsigned char cachedPeersDifferentInfra : 1; unsigned char cachedPeersNotAssociated : 1; unsigned char cachedPeersOn24G : 1; unsigned char cachedPeersOn5G : 1; unsigned char cachedPeersOnDFS : 1; unsigned char cachedPeersSameInfra : 1; unsigned char dfspAirplayConnected : 1; unsigned char dfspAirplayFailed : 1; unsigned char dfspCSAReceivedFromAP : 1; unsigned char dfspCSAReceivedFromPeer : 1; unsigned char dfspResume : 1; unsigned char dfspSuspect : 1; unsigned char flags : 1; unsigned char ifPacketFailures : 1; unsigned char ifRxBytes : 1; unsigned char ifTxBytes : 1; unsigned char numAirplaySessions : 1; unsigned char numDynSdbAirplayAllowed : 1; unsigned char numDynSdbEntrySuccess : 1; unsigned char numDynSdbExitDueToRate : 1; unsigned char numDynSdbReEntrySuccess : 1; unsigned char numOfCachedPeers : 1; unsigned char numOfPeers : 1; unsigned char peerInfraChannel : 1; unsigned char periodInMinutes : 1; unsigned char selfInfraChannel : 1; } _has;
}

@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) unsigned long long timestamp;
@property (nonatomic) BOOL hasSelfInfraChannel;
@property (nonatomic) unsigned int selfInfraChannel;
@property (nonatomic) BOOL hasPeerInfraChannel;
@property (nonatomic) unsigned int peerInfraChannel;
@property (nonatomic) BOOL hasNumOfPeers;
@property (nonatomic) unsigned int numOfPeers;
@property (nonatomic) BOOL hasNumOfCachedPeers;
@property (nonatomic) unsigned int numOfCachedPeers;
@property (nonatomic) BOOL hasCachedPeersOn24G;
@property (nonatomic) unsigned int cachedPeersOn24G;
@property (nonatomic) BOOL hasCachedPeersOn5G;
@property (nonatomic) unsigned int cachedPeersOn5G;
@property (nonatomic) BOOL hasCachedPeersOnDFS;
@property (nonatomic) unsigned int cachedPeersOnDFS;
@property (nonatomic) BOOL hasCachedPeersNotAssociated;
@property (nonatomic) unsigned int cachedPeersNotAssociated;
@property (nonatomic) BOOL hasFlags;
@property (nonatomic) unsigned int flags;
@property (nonatomic) BOOL hasIfPacketFailures;
@property (nonatomic) unsigned int ifPacketFailures;
@property (nonatomic) BOOL hasIfRxBytes;
@property (nonatomic) unsigned int ifRxBytes;
@property (nonatomic) BOOL hasIfTxBytes;
@property (nonatomic) unsigned int ifTxBytes;
@property (nonatomic) BOOL hasAppRxBytes;
@property (nonatomic) unsigned int appRxBytes;
@property (nonatomic) BOOL hasAppTxBytes;
@property (nonatomic) unsigned int appTxBytes;
@property (nonatomic) BOOL hasPeriodInMinutes;
@property (nonatomic) unsigned int periodInMinutes;
@property (retain, nonatomic) NSMutableArray *states;
@property (nonatomic) BOOL hasNoServiceIdleTime;
@property (nonatomic) unsigned long long noServiceIdleTime;
@property (nonatomic) BOOL hasBrowseAddTotalCount;
@property (nonatomic) unsigned int browseAddTotalCount;
@property (nonatomic) BOOL hasBrowseAddFilteredCount;
@property (nonatomic) unsigned int browseAddFilteredCount;
@property (nonatomic) BOOL hasBrowseDeleteTotalCount;
@property (nonatomic) unsigned int browseDeleteTotalCount;
@property (nonatomic) BOOL hasBrowseDeleteFilteredCount;
@property (nonatomic) unsigned int browseDeleteFilteredCount;
@property (nonatomic) BOOL hasAdvertiseAddTotalCount;
@property (nonatomic) unsigned int advertiseAddTotalCount;
@property (nonatomic) BOOL hasAdvertiseAddFilteredCount;
@property (nonatomic) unsigned int advertiseAddFilteredCount;
@property (nonatomic) BOOL hasAdvertiseDeleteTotalCount;
@property (nonatomic) unsigned int advertiseDeleteTotalCount;
@property (nonatomic) BOOL hasAdvertiseDeleteFilteredCount;
@property (nonatomic) unsigned int advertiseDeleteFilteredCount;
@property (retain, nonatomic) NSMutableArray *services;
@property (nonatomic) BOOL hasCachedPeersSameInfra;
@property (nonatomic) unsigned int cachedPeersSameInfra;
@property (nonatomic) BOOL hasCachedPeersDifferentInfra;
@property (nonatomic) unsigned int cachedPeersDifferentInfra;
@property (nonatomic) BOOL hasDfspCSAReceivedFromPeer;
@property (nonatomic) unsigned int dfspCSAReceivedFromPeer;
@property (nonatomic) BOOL hasDfspCSAReceivedFromAP;
@property (nonatomic) unsigned int dfspCSAReceivedFromAP;
@property (nonatomic) BOOL hasDfspSuspect;
@property (nonatomic) unsigned int dfspSuspect;
@property (nonatomic) BOOL hasDfspResume;
@property (nonatomic) unsigned int dfspResume;
@property (nonatomic) BOOL hasDfspAirplayConnected;
@property (nonatomic) unsigned int dfspAirplayConnected;
@property (nonatomic) BOOL hasDfspAirplayFailed;
@property (nonatomic) unsigned int dfspAirplayFailed;
@property (retain, nonatomic) NSMutableArray *hopCountHistograms;
@property (retain, nonatomic) NSMutableArray *parentRssiHistograms;
@property (nonatomic) BOOL hasSyncChangesCount;
@property (nonatomic) unsigned long long syncChangesCount;
@property (nonatomic) BOOL hasNumAirplaySessions;
@property (nonatomic) unsigned int numAirplaySessions;
@property (nonatomic) BOOL hasNumDynSdbAirplayAllowed;
@property (nonatomic) unsigned int numDynSdbAirplayAllowed;
@property (nonatomic) BOOL hasNumDynSdbEntrySuccess;
@property (nonatomic) unsigned int numDynSdbEntrySuccess;
@property (nonatomic) BOOL hasNumDynSdbExitDueToRate;
@property (nonatomic) unsigned int numDynSdbExitDueToRate;
@property (nonatomic) BOOL hasNumDynSdbReEntrySuccess;
@property (nonatomic) unsigned int numDynSdbReEntrySuccess;
@property (readonly, nonatomic) BOOL hasD2dMigrationStats;
@property (retain, nonatomic) AWDWifiAwdlD2dMigrationStats *d2dMigrationStats;

+ (Class)parentRssiHistogramType;
+ (Class)servicesType;
+ (Class)hopCountHistogramType;
+ (Class)statesType;

- (void)addStates:(id)a0;
- (id)parentRssiHistogramAtIndex:(unsigned long long)a0;
- (unsigned long long)statesCount;
- (void)addServices:(id)a0;
- (id)copyWithZone:(struct _NSZone { } *)a0;
- (void)mergeFrom:(id)a0;
- (unsigned long long)servicesCount;
- (void)dealloc;
- (unsigned long long)parentRssiHistogramsCount;
- (void)clearServices;
- (BOOL)readFrom:(id)a0;
- (void)addHopCountHistogram:(id)a0;
- (void)clearStates;
- (id)statesAtIndex:(unsigned long long)a0;
- (unsigned long long)hash;
- (void)writeTo:(id)a0;
- (id)description;
- (void)copyTo:(id)a0;
- (unsigned long long)hopCountHistogramsCount;
- (BOOL)isEqual:(id)a0;
- (id)dictionaryRepresentation;
- (void)addParentRssiHistogram:(id)a0;
- (id)hopCountHistogramAtIndex:(unsigned long long)a0;
- (void)clearHopCountHistograms;
- (void)clearParentRssiHistograms;
- (id)servicesAtIndex:(unsigned long long)a0;

@end
