@class NSString;

@interface AWDWRMWiFiCell5GData : PBCodable <NSCopying> {
    struct { unsigned char timestamp : 1; unsigned char cellDataLQM : 1; unsigned char cellDlBw : 1; unsigned char cellEstimatedBw : 1; unsigned char cellEstimatedLoad : 1; unsigned char cellLteEstimatedThroughput : 1; unsigned char cellLteRSRP : 1; unsigned char cellLteRSRQ : 1; unsigned char cellLteSNR : 1; unsigned char cellMaxDlCaNumConfigured : 1; unsigned char cellMaxUlCaNumConfigured : 1; unsigned char cellNrEstimatedThroughput : 1; unsigned char cellNrFR2active : 1; unsigned char cellNrRSRP : 1; unsigned char cellNrRSRQ : 1; unsigned char cellNrSNR : 1; unsigned char cellNsaEnabled : 1; unsigned char cellRrcState : 1; unsigned char cellUlBw : 1; unsigned char recommendedlink : 1; unsigned char wifPoi : 1; unsigned char wifiCca : 1; unsigned char wifiEstThoughtput : 1; unsigned char wifiQbssLoad : 1; unsigned char wifiRssi : 1; unsigned char wifiRxRetry : 1; unsigned char wifiSnr : 1; unsigned char wifiStationCount : 1; unsigned char wifiTxPER : 1; unsigned char wifiWghtAVGRXPHYRATE : 1; unsigned char wifiWghtAVGSNR : 1; unsigned char wifiWghtAVGTXPHYRATE : 1; unsigned char wifiWgtAVGRSSI : 1; unsigned char wifiWifiEstThoughtputConfidence : 1; } _has;
}

@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) unsigned long long timestamp;
@property (nonatomic) BOOL hasWifiRssi;
@property (nonatomic) int wifiRssi;
@property (nonatomic) BOOL hasWifiSnr;
@property (nonatomic) unsigned int wifiSnr;
@property (nonatomic) BOOL hasWifiTxPER;
@property (nonatomic) unsigned int wifiTxPER;
@property (nonatomic) BOOL hasWifiRxRetry;
@property (nonatomic) unsigned int wifiRxRetry;
@property (nonatomic) BOOL hasWifiCca;
@property (nonatomic) unsigned int wifiCca;
@property (nonatomic) BOOL hasWifiQbssLoad;
@property (nonatomic) unsigned int wifiQbssLoad;
@property (nonatomic) BOOL hasWifiStationCount;
@property (nonatomic) unsigned int wifiStationCount;
@property (nonatomic) BOOL hasWifPoi;
@property (nonatomic) unsigned int wifPoi;
@property (nonatomic) BOOL hasWifiWgtAVGRSSI;
@property (nonatomic) int wifiWgtAVGRSSI;
@property (nonatomic) BOOL hasWifiWghtAVGSNR;
@property (nonatomic) unsigned int wifiWghtAVGSNR;
@property (nonatomic) BOOL hasWifiWghtAVGTXPHYRATE;
@property (nonatomic) unsigned int wifiWghtAVGTXPHYRATE;
@property (nonatomic) BOOL hasWifiWghtAVGRXPHYRATE;
@property (nonatomic) unsigned int wifiWghtAVGRXPHYRATE;
@property (nonatomic) BOOL hasWifiEstThoughtput;
@property (nonatomic) unsigned int wifiEstThoughtput;
@property (nonatomic) BOOL hasWifiWifiEstThoughtputConfidence;
@property (nonatomic) unsigned int wifiWifiEstThoughtputConfidence;
@property (readonly, nonatomic) BOOL hasCellRatType;
@property (retain, nonatomic) NSString *cellRatType;
@property (nonatomic) BOOL hasCellLteRSRP;
@property (nonatomic) int cellLteRSRP;
@property (nonatomic) BOOL hasCellLteSNR;
@property (nonatomic) int cellLteSNR;
@property (nonatomic) BOOL hasCellLteRSRQ;
@property (nonatomic) int cellLteRSRQ;
@property (nonatomic) BOOL hasCellNrRSRP;
@property (nonatomic) int cellNrRSRP;
@property (nonatomic) BOOL hasCellNrRSRQ;
@property (nonatomic) int cellNrRSRQ;
@property (nonatomic) BOOL hasCellNrSNR;
@property (nonatomic) int cellNrSNR;
@property (nonatomic) BOOL hasCellDataLQM;
@property (nonatomic) unsigned int cellDataLQM;
@property (nonatomic) BOOL hasCellRrcState;
@property (nonatomic) unsigned int cellRrcState;
@property (nonatomic) BOOL hasCellNrFR2active;
@property (nonatomic) unsigned int cellNrFR2active;
@property (nonatomic) BOOL hasCellLteEstimatedThroughput;
@property (nonatomic) unsigned int cellLteEstimatedThroughput;
@property (nonatomic) BOOL hasCellNrEstimatedThroughput;
@property (nonatomic) unsigned int cellNrEstimatedThroughput;
@property (nonatomic) BOOL hasCellNsaEnabled;
@property (nonatomic) unsigned int cellNsaEnabled;
@property (nonatomic) BOOL hasCellDlBw;
@property (nonatomic) unsigned int cellDlBw;
@property (nonatomic) BOOL hasCellUlBw;
@property (nonatomic) unsigned int cellUlBw;
@property (nonatomic) BOOL hasCellMaxDlCaNumConfigured;
@property (nonatomic) unsigned int cellMaxDlCaNumConfigured;
@property (nonatomic) BOOL hasCellMaxUlCaNumConfigured;
@property (nonatomic) unsigned int cellMaxUlCaNumConfigured;
@property (nonatomic) BOOL hasCellEstimatedLoad;
@property (nonatomic) unsigned int cellEstimatedLoad;
@property (nonatomic) BOOL hasCellEstimatedBw;
@property (nonatomic) unsigned int cellEstimatedBw;
@property (nonatomic) BOOL hasRecommendedlink;
@property (nonatomic) unsigned int recommendedlink;

- (id)copyWithZone:(struct _NSZone { } *)a0;
- (void)mergeFrom:(id)a0;
- (void)dealloc;
- (BOOL)readFrom:(id)a0;
- (unsigned long long)hash;
- (void)writeTo:(id)a0;
- (id)description;
- (void)copyTo:(id)a0;
- (BOOL)isEqual:(id)a0;
- (id)dictionaryRepresentation;

@end
