@interface AWDBasebandPowerToolKPIs : PBCodable <NSCopying> {
    struct { int *list; unsigned long long count; unsigned long long size; } _armUtilityPDFs;
    struct { int *list; unsigned long long count; unsigned long long size; } _causeCodeBackgroundActivityARMUtilitys;
    struct { int *list; unsigned long long count; unsigned long long size; } _causeCodeBackgroundActivityDurations;
    struct { int *list; unsigned long long count; unsigned long long size; } _causeCodeCumulativeARMUtilitys;
    struct { int *list; unsigned long long count; unsigned long long size; } _causeCodeCumulativeDurations;
    struct { int *list; unsigned long long count; unsigned long long size; } _causeCodeMarginalCoverageARMUtilitys;
    struct { int *list; unsigned long long count; unsigned long long size; } _causeCodeMarginalCoverageDurations;
    struct { int *list; unsigned long long count; unsigned long long size; } _causeCodeOOSARMUtilitys;
    struct { int *list; unsigned long long count; unsigned long long size; } _causeCodeOOSDurations;
    struct { int *list; unsigned long long count; unsigned long long size; } _causeCodeRACHFailARMUtilitys;
    struct { int *list; unsigned long long count; unsigned long long size; } _causeCodeRACHFailDurations;
    struct { int *list; unsigned long long count; unsigned long long size; } _causeCodeStruckInDCHARMUtilitys;
    struct { int *list; unsigned long long count; unsigned long long size; } _causeCodeStruckInDCHDurations;
    struct { int *list; unsigned long long count; unsigned long long size; } _causeCodeTcXONotShuttingARMUtilitys;
    struct { int *list; unsigned long long count; unsigned long long size; } _causeCodeTcXONotShuttingDurations;
    struct { int *list; unsigned long long count; unsigned long long size; } _causeCodeUnknownARMUtilitys;
    struct { int *list; unsigned long long count; unsigned long long size; } _causeCodeUnknownDurations;
    struct { unsigned char timestamp : 1; unsigned char armUtilityThresholdPoint : 1; unsigned char radarPriority : 1; } _has;
}

@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) unsigned long long timestamp;
@property (nonatomic) BOOL hasRadarPriority;
@property (nonatomic) int radarPriority;
@property (nonatomic) BOOL hasArmUtilityThresholdPoint;
@property (nonatomic) int armUtilityThresholdPoint;
@property (readonly, nonatomic) unsigned long long armUtilityPDFsCount;
@property (readonly, nonatomic) int *armUtilityPDFs;
@property (readonly, nonatomic) unsigned long long causeCodeOOSARMUtilitysCount;
@property (readonly, nonatomic) int *causeCodeOOSARMUtilitys;
@property (readonly, nonatomic) unsigned long long causeCodeOOSDurationsCount;
@property (readonly, nonatomic) int *causeCodeOOSDurations;
@property (readonly, nonatomic) unsigned long long causeCodeTcXONotShuttingARMUtilitysCount;
@property (readonly, nonatomic) int *causeCodeTcXONotShuttingARMUtilitys;
@property (readonly, nonatomic) unsigned long long causeCodeTcXONotShuttingDurationsCount;
@property (readonly, nonatomic) int *causeCodeTcXONotShuttingDurations;
@property (readonly, nonatomic) unsigned long long causeCodeBackgroundActivityARMUtilitysCount;
@property (readonly, nonatomic) int *causeCodeBackgroundActivityARMUtilitys;
@property (readonly, nonatomic) unsigned long long causeCodeBackgroundActivityDurationsCount;
@property (readonly, nonatomic) int *causeCodeBackgroundActivityDurations;
@property (readonly, nonatomic) unsigned long long causeCodeRACHFailARMUtilitysCount;
@property (readonly, nonatomic) int *causeCodeRACHFailARMUtilitys;
@property (readonly, nonatomic) unsigned long long causeCodeRACHFailDurationsCount;
@property (readonly, nonatomic) int *causeCodeRACHFailDurations;
@property (readonly, nonatomic) unsigned long long causeCodeStruckInDCHARMUtilitysCount;
@property (readonly, nonatomic) int *causeCodeStruckInDCHARMUtilitys;
@property (readonly, nonatomic) unsigned long long causeCodeStruckInDCHDurationsCount;
@property (readonly, nonatomic) int *causeCodeStruckInDCHDurations;
@property (readonly, nonatomic) unsigned long long causeCodeMarginalCoverageARMUtilitysCount;
@property (readonly, nonatomic) int *causeCodeMarginalCoverageARMUtilitys;
@property (readonly, nonatomic) unsigned long long causeCodeMarginalCoverageDurationsCount;
@property (readonly, nonatomic) int *causeCodeMarginalCoverageDurations;
@property (readonly, nonatomic) unsigned long long causeCodeUnknownARMUtilitysCount;
@property (readonly, nonatomic) int *causeCodeUnknownARMUtilitys;
@property (readonly, nonatomic) unsigned long long causeCodeUnknownDurationsCount;
@property (readonly, nonatomic) int *causeCodeUnknownDurations;
@property (readonly, nonatomic) unsigned long long causeCodeCumulativeARMUtilitysCount;
@property (readonly, nonatomic) int *causeCodeCumulativeARMUtilitys;
@property (readonly, nonatomic) unsigned long long causeCodeCumulativeDurationsCount;
@property (readonly, nonatomic) int *causeCodeCumulativeDurations;

- (unsigned long long)hash;
- (void)dealloc;
- (BOOL)readFrom:(id)a0;
- (void)writeTo:(id)a0;
- (id)description;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)a0;
- (BOOL)isEqual:(id)a0;
- (void)mergeFrom:(id)a0;
- (id)copyWithZone:(struct _NSZone { } *)a0;
- (void)addCauseCodeRACHFailARMUtility:(int)a0;
- (void)clearCauseCodeRACHFailDurations;
- (void)setCauseCodeOOSDurations:(int *)a0 count:(unsigned long long)a1;
- (void)addArmUtilityPDF:(int)a0;
- (void)addCauseCodeBackgroundActivityARMUtility:(int)a0;
- (void)addCauseCodeBackgroundActivityDurations:(int)a0;
- (void)addCauseCodeCumulativeARMUtility:(int)a0;
- (void)addCauseCodeCumulativeDurations:(int)a0;
- (void)addCauseCodeMarginalCoverageARMUtility:(int)a0;
- (void)addCauseCodeMarginalCoverageDurations:(int)a0;
- (void)addCauseCodeOOSARMUtility:(int)a0;
- (void)addCauseCodeOOSDurations:(int)a0;
- (void)addCauseCodeRACHFailDurations:(int)a0;
- (void)addCauseCodeStruckInDCHARMUtility:(int)a0;
- (void)addCauseCodeStruckInDCHDurations:(int)a0;
- (void)addCauseCodeTcXONotShuttingARMUtility:(int)a0;
- (void)addCauseCodeTcXONotShuttingDurations:(int)a0;
- (void)addCauseCodeUnknownARMUtility:(int)a0;
- (void)addCauseCodeUnknownDurations:(int)a0;
- (int)armUtilityPDFAtIndex:(unsigned long long)a0;
- (int)causeCodeBackgroundActivityARMUtilityAtIndex:(unsigned long long)a0;
- (int)causeCodeBackgroundActivityDurationsAtIndex:(unsigned long long)a0;
- (int)causeCodeCumulativeARMUtilityAtIndex:(unsigned long long)a0;
- (int)causeCodeCumulativeDurationsAtIndex:(unsigned long long)a0;
- (int)causeCodeMarginalCoverageARMUtilityAtIndex:(unsigned long long)a0;
- (int)causeCodeMarginalCoverageDurationsAtIndex:(unsigned long long)a0;
- (int)causeCodeOOSARMUtilityAtIndex:(unsigned long long)a0;
- (int)causeCodeOOSDurationsAtIndex:(unsigned long long)a0;
- (int)causeCodeRACHFailARMUtilityAtIndex:(unsigned long long)a0;
- (int)causeCodeRACHFailDurationsAtIndex:(unsigned long long)a0;
- (int)causeCodeStruckInDCHARMUtilityAtIndex:(unsigned long long)a0;
- (int)causeCodeStruckInDCHDurationsAtIndex:(unsigned long long)a0;
- (int)causeCodeTcXONotShuttingARMUtilityAtIndex:(unsigned long long)a0;
- (int)causeCodeTcXONotShuttingDurationsAtIndex:(unsigned long long)a0;
- (int)causeCodeUnknownARMUtilityAtIndex:(unsigned long long)a0;
- (int)causeCodeUnknownDurationsAtIndex:(unsigned long long)a0;
- (void)clearArmUtilityPDFs;
- (void)clearCauseCodeBackgroundActivityARMUtilitys;
- (void)clearCauseCodeBackgroundActivityDurations;
- (void)clearCauseCodeCumulativeARMUtilitys;
- (void)clearCauseCodeCumulativeDurations;
- (void)clearCauseCodeMarginalCoverageARMUtilitys;
- (void)clearCauseCodeMarginalCoverageDurations;
- (void)clearCauseCodeOOSARMUtilitys;
- (void)clearCauseCodeOOSDurations;
- (void)clearCauseCodeRACHFailARMUtilitys;
- (void)clearCauseCodeStruckInDCHARMUtilitys;
- (void)clearCauseCodeStruckInDCHDurations;
- (void)clearCauseCodeTcXONotShuttingARMUtilitys;
- (void)clearCauseCodeTcXONotShuttingDurations;
- (void)clearCauseCodeUnknownARMUtilitys;
- (void)clearCauseCodeUnknownDurations;
- (void)setArmUtilityPDFs:(int *)a0 count:(unsigned long long)a1;
- (void)setCauseCodeBackgroundActivityARMUtilitys:(int *)a0 count:(unsigned long long)a1;
- (void)setCauseCodeBackgroundActivityDurations:(int *)a0 count:(unsigned long long)a1;
- (void)setCauseCodeCumulativeARMUtilitys:(int *)a0 count:(unsigned long long)a1;
- (void)setCauseCodeCumulativeDurations:(int *)a0 count:(unsigned long long)a1;
- (void)setCauseCodeMarginalCoverageARMUtilitys:(int *)a0 count:(unsigned long long)a1;
- (void)setCauseCodeMarginalCoverageDurations:(int *)a0 count:(unsigned long long)a1;
- (void)setCauseCodeOOSARMUtilitys:(int *)a0 count:(unsigned long long)a1;
- (void)setCauseCodeRACHFailARMUtilitys:(int *)a0 count:(unsigned long long)a1;
- (void)setCauseCodeRACHFailDurations:(int *)a0 count:(unsigned long long)a1;
- (void)setCauseCodeStruckInDCHARMUtilitys:(int *)a0 count:(unsigned long long)a1;
- (void)setCauseCodeStruckInDCHDurations:(int *)a0 count:(unsigned long long)a1;
- (void)setCauseCodeTcXONotShuttingARMUtilitys:(int *)a0 count:(unsigned long long)a1;
- (void)setCauseCodeTcXONotShuttingDurations:(int *)a0 count:(unsigned long long)a1;
- (void)setCauseCodeUnknownARMUtilitys:(int *)a0 count:(unsigned long long)a1;
- (void)setCauseCodeUnknownDurations:(int *)a0 count:(unsigned long long)a1;

@end
