@interface AWDMMCSTcpInfo : PBCodable <NSCopying> {
    struct { unsigned char tcpiCellRxbytes : 1; unsigned char tcpiCellRxpackets : 1; unsigned char tcpiCellTxbytes : 1; unsigned char tcpiCellTxpackets : 1; unsigned char tcpiRxbytes : 1; unsigned char tcpiRxduplicatebytes : 1; unsigned char tcpiRxoutoforderbytes : 1; unsigned char tcpiRxpackets : 1; unsigned char tcpiSndBw : 1; unsigned char tcpiTxbytes : 1; unsigned char tcpiTxpackets : 1; unsigned char tcpiTxretransmitbytes : 1; unsigned char tcpiTxunacked : 1; unsigned char tcpiWifiRxbytes : 1; unsigned char tcpiWifiRxpackets : 1; unsigned char tcpiWifiTxbytes : 1; unsigned char tcpiWifiTxpackets : 1; unsigned char tcpiFlags : 1; unsigned char tcpiLastOutif : 1; unsigned char tcpiOptions : 1; unsigned char tcpiRcvMss : 1; unsigned char tcpiRcvNxt : 1; unsigned char tcpiRcvSpace : 1; unsigned char tcpiRcvWscale : 1; unsigned char tcpiRto : 1; unsigned char tcpiRttbest : 1; unsigned char tcpiRttcur : 1; unsigned char tcpiRttvar : 1; unsigned char tcpiSndCwnd : 1; unsigned char tcpiSndMss : 1; unsigned char tcpiSndNxt : 1; unsigned char tcpiSndSbbytes : 1; unsigned char tcpiSndSsthresh : 1; unsigned char tcpiSndWnd : 1; unsigned char tcpiSndWscale : 1; unsigned char tcpiSrtt : 1; unsigned char tcpiState : 1; unsigned char tcpiSynrexmits : 1; unsigned char tcpiUnused1 : 1; unsigned char tcpiUnused2 : 1; } _has;
}

@property (nonatomic) BOOL hasTcpiState;
@property (nonatomic) unsigned int tcpiState;
@property (nonatomic) BOOL hasTcpiOptions;
@property (nonatomic) unsigned int tcpiOptions;
@property (nonatomic) BOOL hasTcpiSndWscale;
@property (nonatomic) unsigned int tcpiSndWscale;
@property (nonatomic) BOOL hasTcpiRcvWscale;
@property (nonatomic) unsigned int tcpiRcvWscale;
@property (nonatomic) BOOL hasTcpiFlags;
@property (nonatomic) unsigned int tcpiFlags;
@property (nonatomic) BOOL hasTcpiRto;
@property (nonatomic) unsigned int tcpiRto;
@property (nonatomic) BOOL hasTcpiSndMss;
@property (nonatomic) unsigned int tcpiSndMss;
@property (nonatomic) BOOL hasTcpiRcvMss;
@property (nonatomic) unsigned int tcpiRcvMss;
@property (nonatomic) BOOL hasTcpiRttcur;
@property (nonatomic) unsigned int tcpiRttcur;
@property (nonatomic) BOOL hasTcpiSrtt;
@property (nonatomic) unsigned int tcpiSrtt;
@property (nonatomic) BOOL hasTcpiRttvar;
@property (nonatomic) unsigned int tcpiRttvar;
@property (nonatomic) BOOL hasTcpiRttbest;
@property (nonatomic) unsigned int tcpiRttbest;
@property (nonatomic) BOOL hasTcpiSndSsthresh;
@property (nonatomic) unsigned int tcpiSndSsthresh;
@property (nonatomic) BOOL hasTcpiSndCwnd;
@property (nonatomic) unsigned int tcpiSndCwnd;
@property (nonatomic) BOOL hasTcpiRcvSpace;
@property (nonatomic) unsigned int tcpiRcvSpace;
@property (nonatomic) BOOL hasTcpiSndWnd;
@property (nonatomic) unsigned int tcpiSndWnd;
@property (nonatomic) BOOL hasTcpiSndNxt;
@property (nonatomic) unsigned int tcpiSndNxt;
@property (nonatomic) BOOL hasTcpiRcvNxt;
@property (nonatomic) unsigned int tcpiRcvNxt;
@property (nonatomic) BOOL hasTcpiLastOutif;
@property (nonatomic) int tcpiLastOutif;
@property (nonatomic) BOOL hasTcpiSndSbbytes;
@property (nonatomic) unsigned int tcpiSndSbbytes;
@property (nonatomic) BOOL hasTcpiTxpackets;
@property (nonatomic) unsigned long long tcpiTxpackets;
@property (nonatomic) BOOL hasTcpiTxbytes;
@property (nonatomic) unsigned long long tcpiTxbytes;
@property (nonatomic) BOOL hasTcpiTxretransmitbytes;
@property (nonatomic) unsigned long long tcpiTxretransmitbytes;
@property (nonatomic) BOOL hasTcpiTxunacked;
@property (nonatomic) unsigned long long tcpiTxunacked;
@property (nonatomic) BOOL hasTcpiRxpackets;
@property (nonatomic) unsigned long long tcpiRxpackets;
@property (nonatomic) BOOL hasTcpiRxbytes;
@property (nonatomic) unsigned long long tcpiRxbytes;
@property (nonatomic) BOOL hasTcpiRxduplicatebytes;
@property (nonatomic) unsigned long long tcpiRxduplicatebytes;
@property (nonatomic) BOOL hasTcpiRxoutoforderbytes;
@property (nonatomic) unsigned long long tcpiRxoutoforderbytes;
@property (nonatomic) BOOL hasTcpiSndBw;
@property (nonatomic) unsigned long long tcpiSndBw;
@property (nonatomic) BOOL hasTcpiSynrexmits;
@property (nonatomic) int tcpiSynrexmits;
@property (nonatomic) BOOL hasTcpiUnused1;
@property (nonatomic) int tcpiUnused1;
@property (nonatomic) BOOL hasTcpiUnused2;
@property (nonatomic) unsigned int tcpiUnused2;
@property (nonatomic) BOOL hasTcpiCellRxpackets;
@property (nonatomic) unsigned long long tcpiCellRxpackets;
@property (nonatomic) BOOL hasTcpiCellRxbytes;
@property (nonatomic) unsigned long long tcpiCellRxbytes;
@property (nonatomic) BOOL hasTcpiCellTxpackets;
@property (nonatomic) unsigned long long tcpiCellTxpackets;
@property (nonatomic) BOOL hasTcpiCellTxbytes;
@property (nonatomic) unsigned long long tcpiCellTxbytes;
@property (nonatomic) BOOL hasTcpiWifiRxpackets;
@property (nonatomic) unsigned long long tcpiWifiRxpackets;
@property (nonatomic) BOOL hasTcpiWifiRxbytes;
@property (nonatomic) unsigned long long tcpiWifiRxbytes;
@property (nonatomic) BOOL hasTcpiWifiTxpackets;
@property (nonatomic) unsigned long long tcpiWifiTxpackets;
@property (nonatomic) BOOL hasTcpiWifiTxbytes;
@property (nonatomic) unsigned long long tcpiWifiTxbytes;

- (unsigned long long)hash;
- (BOOL)readFrom:(id)a0;
- (void)writeTo:(id)a0;
- (id)description;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)a0;
- (BOOL)isEqual:(id)a0;
- (void)mergeFrom:(id)a0;
- (id)copyWithZone:(struct _NSZone { } *)a0;

@end
