@class NSMutableArray;

@interface AWDSidecarPeerTraffic : PBCodable <NSCopying> {
    struct { unsigned char txErrorCount : 1; unsigned char txExpiredCount : 1; unsigned char txSuccessCount : 1; } _has;
}

@property (nonatomic) BOOL hasTxSuccessCount;
@property (nonatomic) unsigned long long txSuccessCount;
@property (nonatomic) BOOL hasTxExpiredCount;
@property (nonatomic) unsigned long long txExpiredCount;
@property (nonatomic) BOOL hasTxErrorCount;
@property (nonatomic) unsigned long long txErrorCount;
@property (retain, nonatomic) NSMutableArray *txTotalDelays;
@property (retain, nonatomic) NSMutableArray *txIPCDelays;
@property (retain, nonatomic) NSMutableArray *txFWDelays;
@property (retain, nonatomic) NSMutableArray *txHWDelays;
@property (retain, nonatomic) NSMutableArray *txDataRates;
@property (retain, nonatomic) NSMutableArray *txCCAs;
@property (retain, nonatomic) NSMutableArray *txRetries;
@property (retain, nonatomic) NSMutableArray *txPacketBurstSizes;
@property (retain, nonatomic) NSMutableArray *txPacketBurstIntervals;
@property (retain, nonatomic) NSMutableArray *rxTotalDelays;
@property (retain, nonatomic) NSMutableArray *rxIPCDelays;
@property (retain, nonatomic) NSMutableArray *rxFWDelays;
@property (retain, nonatomic) NSMutableArray *rxDataRates;
@property (retain, nonatomic) NSMutableArray *rxRSSIs;

+ (Class)rxDataRateType;
+ (Class)rxFWDelayType;
+ (Class)rxIPCDelayType;
+ (Class)rxRSSIType;
+ (Class)rxTotalDelayType;
+ (Class)txCCAType;
+ (Class)txDataRateType;
+ (Class)txFWDelayType;
+ (Class)txHWDelayType;
+ (Class)txIPCDelayType;
+ (Class)txPacketBurstIntervalType;
+ (Class)txPacketBurstSizeType;
+ (Class)txRetriesType;
+ (Class)txTotalDelayType;

- (unsigned long long)hash;
- (void)dealloc;
- (BOOL)readFrom:(id)a0;
- (void)writeTo:(id)a0;
- (id)description;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)a0;
- (BOOL)isEqual:(id)a0;
- (void)mergeFrom:(id)a0;
- (id)copyWithZone:(struct _NSZone { } *)a0;
- (void)clearRxFWDelays;
- (void)clearTxFWDelays;
- (unsigned long long)rxFWDelaysCount;
- (void)clearTxHWDelays;
- (unsigned long long)txFWDelaysCount;
- (unsigned long long)txHWDelaysCount;
- (void)addRxDataRate:(id)a0;
- (void)addRxFWDelay:(id)a0;
- (void)addRxIPCDelay:(id)a0;
- (void)addRxRSSI:(id)a0;
- (void)addRxTotalDelay:(id)a0;
- (void)addTxCCA:(id)a0;
- (void)addTxDataRate:(id)a0;
- (void)addTxFWDelay:(id)a0;
- (void)addTxHWDelay:(id)a0;
- (void)addTxIPCDelay:(id)a0;
- (void)addTxPacketBurstInterval:(id)a0;
- (void)addTxPacketBurstSize:(id)a0;
- (void)addTxRetries:(id)a0;
- (void)addTxTotalDelay:(id)a0;
- (void)clearRxDataRates;
- (void)clearRxIPCDelays;
- (void)clearRxRSSIs;
- (void)clearRxTotalDelays;
- (void)clearTxCCAs;
- (void)clearTxDataRates;
- (void)clearTxIPCDelays;
- (void)clearTxPacketBurstIntervals;
- (void)clearTxPacketBurstSizes;
- (void)clearTxRetries;
- (void)clearTxTotalDelays;
- (id)rxDataRateAtIndex:(unsigned long long)a0;
- (unsigned long long)rxDataRatesCount;
- (id)rxFWDelayAtIndex:(unsigned long long)a0;
- (id)rxIPCDelayAtIndex:(unsigned long long)a0;
- (unsigned long long)rxIPCDelaysCount;
- (id)rxRSSIAtIndex:(unsigned long long)a0;
- (unsigned long long)rxRSSIsCount;
- (id)rxTotalDelayAtIndex:(unsigned long long)a0;
- (unsigned long long)rxTotalDelaysCount;
- (id)txCCAAtIndex:(unsigned long long)a0;
- (unsigned long long)txCCAsCount;
- (id)txDataRateAtIndex:(unsigned long long)a0;
- (unsigned long long)txDataRatesCount;
- (id)txFWDelayAtIndex:(unsigned long long)a0;
- (id)txHWDelayAtIndex:(unsigned long long)a0;
- (id)txIPCDelayAtIndex:(unsigned long long)a0;
- (unsigned long long)txIPCDelaysCount;
- (id)txPacketBurstIntervalAtIndex:(unsigned long long)a0;
- (unsigned long long)txPacketBurstIntervalsCount;
- (id)txPacketBurstSizeAtIndex:(unsigned long long)a0;
- (unsigned long long)txPacketBurstSizesCount;
- (id)txRetriesAtIndex:(unsigned long long)a0;
- (unsigned long long)txRetriesCount;
- (id)txTotalDelayAtIndex:(unsigned long long)a0;
- (unsigned long long)txTotalDelaysCount;

@end
