@interface AWDWiFiMetricExtendedTrapInfo : PBCodable <NSCopying> {
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _backplanes;
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _bus;
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _deepSleeps;
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _macEnabs;
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _macs;
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _memoryDumps;
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _pcieQueueStates;
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _phyTxErrThreshs;
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _phys;
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _psmWDs;
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _signatures;
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _stackTraces;
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _ucodeErrors;
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _wlcStates;
    struct { unsigned char sequence : 1; } _has;
}

@property (nonatomic) BOOL hasSequence;
@property (nonatomic) unsigned int sequence;
@property (readonly, nonatomic) unsigned long long signaturesCount;
@property (readonly, nonatomic) unsigned int *signatures;
@property (readonly, nonatomic) unsigned long long stackTracesCount;
@property (readonly, nonatomic) unsigned int *stackTraces;
@property (readonly, nonatomic) unsigned long long ucodeErrorsCount;
@property (readonly, nonatomic) unsigned int *ucodeErrors;
@property (readonly, nonatomic) unsigned long long memoryDumpsCount;
@property (readonly, nonatomic) unsigned int *memoryDumps;
@property (readonly, nonatomic) unsigned long long deepSleepsCount;
@property (readonly, nonatomic) unsigned int *deepSleeps;
@property (readonly, nonatomic) unsigned long long psmWDsCount;
@property (readonly, nonatomic) unsigned int *psmWDs;
@property (readonly, nonatomic) unsigned long long physCount;
@property (readonly, nonatomic) unsigned int *phys;
@property (readonly, nonatomic) unsigned long long busCount;
@property (readonly, nonatomic) unsigned int *bus;
@property (readonly, nonatomic) unsigned long long macsCount;
@property (readonly, nonatomic) unsigned int *macs;
@property (readonly, nonatomic) unsigned long long backplanesCount;
@property (readonly, nonatomic) unsigned int *backplanes;
@property (readonly, nonatomic) unsigned long long pcieQueueStatesCount;
@property (readonly, nonatomic) unsigned int *pcieQueueStates;
@property (readonly, nonatomic) unsigned long long wlcStatesCount;
@property (readonly, nonatomic) unsigned int *wlcStates;
@property (readonly, nonatomic) unsigned long long macEnabsCount;
@property (readonly, nonatomic) unsigned int *macEnabs;
@property (readonly, nonatomic) unsigned long long phyTxErrThreshsCount;
@property (readonly, nonatomic) unsigned int *phyTxErrThreshs;

- (unsigned long long)hash;
- (void)dealloc;
- (BOOL)readFrom:(id)a0;
- (void)writeTo:(id)a0;
- (id)description;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)a0;
- (BOOL)isEqual:(id)a0;
- (void)mergeFrom:(id)a0;
- (id)copyWithZone:(struct _NSZone { } *)a0;
- (void)addSignature:(unsigned int)a0;
- (void)addBus:(unsigned int)a0;
- (void)addMac:(unsigned int)a0;
- (void)addPhy:(unsigned int)a0;
- (void)addStackTraces:(unsigned int)a0;
- (void)clearBackplanes;
- (void)clearSignatures;
- (unsigned int)macEnabAtIndex:(unsigned long long)a0;
- (void)addUcodeErrors:(unsigned int)a0;
- (void)clearDeepSleeps;
- (void)addBackplane:(unsigned int)a0;
- (void)addDeepSleep:(unsigned int)a0;
- (void)addMacEnab:(unsigned int)a0;
- (void)addMemoryDump:(unsigned int)a0;
- (void)addPcieQueueState:(unsigned int)a0;
- (void)addPhyTxErrThresh:(unsigned int)a0;
- (void)addPsmWD:(unsigned int)a0;
- (void)addWlcState:(unsigned int)a0;
- (unsigned int)backplaneAtIndex:(unsigned long long)a0;
- (unsigned int)busAtIndex:(unsigned long long)a0;
- (void)clearBus;
- (void)clearMacEnabs;
- (void)clearMacs;
- (void)clearMemoryDumps;
- (void)clearPcieQueueStates;
- (void)clearPhyTxErrThreshs;
- (void)clearPhys;
- (void)clearPsmWDs;
- (void)clearStackTraces;
- (void)clearUcodeErrors;
- (void)clearWlcStates;
- (unsigned int)deepSleepAtIndex:(unsigned long long)a0;
- (unsigned int)macAtIndex:(unsigned long long)a0;
- (unsigned int)memoryDumpAtIndex:(unsigned long long)a0;
- (unsigned int)pcieQueueStateAtIndex:(unsigned long long)a0;
- (unsigned int)phyAtIndex:(unsigned long long)a0;
- (unsigned int)phyTxErrThreshAtIndex:(unsigned long long)a0;
- (unsigned int)psmWDAtIndex:(unsigned long long)a0;
- (void)setBackplanes:(unsigned int *)a0 count:(unsigned long long)a1;
- (void)setBus:(unsigned int *)a0 count:(unsigned long long)a1;
- (void)setDeepSleeps:(unsigned int *)a0 count:(unsigned long long)a1;
- (void)setMacEnabs:(unsigned int *)a0 count:(unsigned long long)a1;
- (void)setMacs:(unsigned int *)a0 count:(unsigned long long)a1;
- (void)setMemoryDumps:(unsigned int *)a0 count:(unsigned long long)a1;
- (void)setPcieQueueStates:(unsigned int *)a0 count:(unsigned long long)a1;
- (void)setPhyTxErrThreshs:(unsigned int *)a0 count:(unsigned long long)a1;
- (void)setPhys:(unsigned int *)a0 count:(unsigned long long)a1;
- (void)setPsmWDs:(unsigned int *)a0 count:(unsigned long long)a1;
- (void)setSignatures:(unsigned int *)a0 count:(unsigned long long)a1;
- (void)setStackTraces:(unsigned int *)a0 count:(unsigned long long)a1;
- (void)setUcodeErrors:(unsigned int *)a0 count:(unsigned long long)a1;
- (void)setWlcStates:(unsigned int *)a0 count:(unsigned long long)a1;
- (unsigned int)signatureAtIndex:(unsigned long long)a0;
- (unsigned int)stackTracesAtIndex:(unsigned long long)a0;
- (unsigned int)ucodeErrorsAtIndex:(unsigned long long)a0;
- (unsigned int)wlcStateAtIndex:(unsigned long long)a0;

@end
