@interface AWDWifiLinkQualityRecord : PBCodable <NSCopying> {
    struct { unsigned char gateOpenTime : 1; unsigned char rapidLqmDuration : 1; unsigned char roamWaitTime : 1; unsigned char tdEvalDuration : 1; unsigned char trafficWatchDuration : 1; unsigned char trafficWatchTime : 1; unsigned char arpFailureCount : 1; unsigned char bcnPerSign : 1; unsigned char bcnRcvs : 1; unsigned char bcnSched : 1; unsigned char dnsServersImpacted : 1; unsigned char dnsServersTotal : 1; unsigned char fwTxFail : 1; unsigned char fwTxFrames : 1; unsigned char fwTxPerSign : 1; unsigned char fwTxRetrans : 1; unsigned char gwArpExpiry : 1; unsigned char metricReason : 1; unsigned char netScore : 1; unsigned char rssi : 1; unsigned char rxFrames : 1; unsigned char sympAwdCode : 1; unsigned char sympSign : 1; unsigned char trafficWatchRx : 1; unsigned char trgDisc : 1; unsigned char txFail : 1; unsigned char txFrames : 1; unsigned char txPerSign : 1; unsigned char txRetrans : 1; unsigned char usrImpact : 1; unsigned char usrInput : 1; unsigned char validState : 1; } _has;
}

@property (nonatomic) BOOL hasTxFrames;
@property (nonatomic) unsigned int txFrames;
@property (nonatomic) BOOL hasTxFail;
@property (nonatomic) unsigned int txFail;
@property (nonatomic) BOOL hasTxRetrans;
@property (nonatomic) unsigned int txRetrans;
@property (nonatomic) BOOL hasBcnSched;
@property (nonatomic) unsigned int bcnSched;
@property (nonatomic) BOOL hasBcnRcvs;
@property (nonatomic) unsigned int bcnRcvs;
@property (nonatomic) BOOL hasFwTxFrames;
@property (nonatomic) unsigned int fwTxFrames;
@property (nonatomic) BOOL hasFwTxFail;
@property (nonatomic) unsigned int fwTxFail;
@property (nonatomic) BOOL hasFwTxRetrans;
@property (nonatomic) unsigned int fwTxRetrans;
@property (nonatomic) BOOL hasRxFrames;
@property (nonatomic) unsigned int rxFrames;
@property (nonatomic) BOOL hasRssi;
@property (nonatomic) int rssi;
@property (nonatomic) BOOL hasTrgDisc;
@property (nonatomic) unsigned int trgDisc;
@property (nonatomic) BOOL hasGwArpExpiry;
@property (nonatomic) unsigned int gwArpExpiry;
@property (nonatomic) BOOL hasUsrInput;
@property (nonatomic) unsigned int usrInput;
@property (nonatomic) BOOL hasTxPerSign;
@property (nonatomic) unsigned int txPerSign;
@property (nonatomic) BOOL hasFwTxPerSign;
@property (nonatomic) unsigned int fwTxPerSign;
@property (nonatomic) BOOL hasBcnPerSign;
@property (nonatomic) unsigned int bcnPerSign;
@property (nonatomic) BOOL hasSympSign;
@property (nonatomic) unsigned int sympSign;
@property (nonatomic) BOOL hasNetScore;
@property (nonatomic) unsigned int netScore;
@property (nonatomic) BOOL hasUsrImpact;
@property (nonatomic) unsigned int usrImpact;
@property (nonatomic) BOOL hasSympAwdCode;
@property (nonatomic) unsigned int sympAwdCode;
@property (nonatomic) BOOL hasArpFailureCount;
@property (nonatomic) unsigned int arpFailureCount;
@property (nonatomic) BOOL hasDnsServersImpacted;
@property (nonatomic) unsigned int dnsServersImpacted;
@property (nonatomic) BOOL hasDnsServersTotal;
@property (nonatomic) unsigned int dnsServersTotal;
@property (nonatomic) BOOL hasGateOpenTime;
@property (nonatomic) double gateOpenTime;
@property (nonatomic) BOOL hasTrafficWatchRx;
@property (nonatomic) unsigned int trafficWatchRx;
@property (nonatomic) BOOL hasTrafficWatchDuration;
@property (nonatomic) double trafficWatchDuration;
@property (nonatomic) BOOL hasTrafficWatchTime;
@property (nonatomic) double trafficWatchTime;
@property (nonatomic) BOOL hasValidState;
@property (nonatomic) unsigned int validState;
@property (nonatomic) BOOL hasMetricReason;
@property (nonatomic) unsigned int metricReason;
@property (nonatomic) BOOL hasRapidLqmDuration;
@property (nonatomic) unsigned long long rapidLqmDuration;
@property (nonatomic) BOOL hasTdEvalDuration;
@property (nonatomic) unsigned long long tdEvalDuration;
@property (nonatomic) BOOL hasRoamWaitTime;
@property (nonatomic) unsigned long long roamWaitTime;

- (unsigned long long)hash;
- (BOOL)readFrom:(id)a0;
- (void)writeTo:(id)a0;
- (id)description;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)a0;
- (BOOL)isEqual:(id)a0;
- (void)mergeFrom:(id)a0;
- (id)copyWithZone:(struct _NSZone { } *)a0;

@end
