@class NSString;

@interface AWDWRMWiFiCallingEnd : PBCodable <NSCopying> {
    struct { unsigned char lTECTRSRP : 1; unsigned char lTERSRP : 1; unsigned char servingCellRSRP : 1; unsigned char timestamp : 1; unsigned char wiFiRSSI : 1; unsigned char wiFiSINR : 1; unsigned char bBAudioErasures : 1; unsigned char bBAudioPacketLoss : 1; unsigned char bSSLoad : 1; unsigned char beaconRate : 1; unsigned char hOBool : 1; unsigned char lTEDataLQM : 1; unsigned char lTESINR : 1; unsigned char lTETxPower : 1; unsigned char lTEVoiceLQM : 1; unsigned char latteDejitterBufferUnderflow : 1; unsigned char latteErasures : 1; unsigned char latteNominalJitterBufferSize : 1; unsigned char latteRTPPacketLoss : 1; unsigned char servingCellRAT : 1; unsigned char servingCellSINR : 1; unsigned char sessionId : 1; unsigned char signalBar : 1; unsigned char wiFiRxRetry : 1; unsigned char wiFiTxPER : 1; unsigned char aTMRegistrationState : 1; unsigned char captiveNetwork : 1; unsigned char hOCapability : 1; unsigned char iPSecTunnelStatus : 1; unsigned char iWLANStatus : 1; unsigned char lTEQoSAvailable : 1; unsigned char wOWEnabled : 1; unsigned char wiFiBSSIDChange : 1; unsigned char wiFiPreferred : 1; } _has;
}

@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) unsigned long long timestamp;
@property (nonatomic) BOOL hasWiFiRSSI;
@property (nonatomic) long long wiFiRSSI;
@property (nonatomic) BOOL hasWiFiTxPER;
@property (nonatomic) unsigned int wiFiTxPER;
@property (nonatomic) BOOL hasWiFiSINR;
@property (nonatomic) long long wiFiSINR;
@property (nonatomic) BOOL hasWiFiBSSIDChange;
@property (nonatomic) BOOL wiFiBSSIDChange;
@property (nonatomic) BOOL hasBeaconRate;
@property (nonatomic) unsigned int beaconRate;
@property (nonatomic) BOOL hasCaptiveNetwork;
@property (nonatomic) BOOL captiveNetwork;
@property (nonatomic) BOOL hasWOWEnabled;
@property (nonatomic) BOOL wOWEnabled;
@property (nonatomic) BOOL hasWiFiRxRetry;
@property (nonatomic) unsigned int wiFiRxRetry;
@property (nonatomic) BOOL hasLTEDataLQM;
@property (nonatomic) int lTEDataLQM;
@property (nonatomic) BOOL hasLTETxPower;
@property (nonatomic) unsigned int lTETxPower;
@property (nonatomic) BOOL hasLTEQoSAvailable;
@property (nonatomic) BOOL lTEQoSAvailable;
@property (nonatomic) BOOL hasBSSLoad;
@property (nonatomic) unsigned int bSSLoad;
@property (nonatomic) BOOL hasLTEVoiceLQM;
@property (nonatomic) int lTEVoiceLQM;
@property (nonatomic) BOOL hasLTESINR;
@property (nonatomic) int lTESINR;
@property (nonatomic) BOOL hasLTERSRP;
@property (nonatomic) long long lTERSRP;
@property (nonatomic) BOOL hasLTECTRSRP;
@property (nonatomic) long long lTECTRSRP;
@property (nonatomic) BOOL hasSignalBar;
@property (nonatomic) unsigned int signalBar;
@property (nonatomic) BOOL hasLatteNominalJitterBufferSize;
@property (nonatomic) unsigned int latteNominalJitterBufferSize;
@property (nonatomic) BOOL hasLatteDejitterBufferUnderflow;
@property (nonatomic) unsigned int latteDejitterBufferUnderflow;
@property (nonatomic) BOOL hasLatteRTPPacketLoss;
@property (nonatomic) unsigned int latteRTPPacketLoss;
@property (nonatomic) BOOL hasLatteErasures;
@property (nonatomic) unsigned int latteErasures;
@property (nonatomic) BOOL hasHOCapability;
@property (nonatomic) BOOL hOCapability;
@property (nonatomic) BOOL hasHOBool;
@property (nonatomic) unsigned int hOBool;
@property (readonly, nonatomic) BOOL hasWRMRecommendedRAT;
@property (retain, nonatomic) NSString *wRMRecommendedRAT;
@property (nonatomic) BOOL hasIWLANStatus;
@property (nonatomic) BOOL iWLANStatus;
@property (readonly, nonatomic) BOOL hasCallId;
@property (retain, nonatomic) NSString *callId;
@property (nonatomic) BOOL hasSessionId;
@property (nonatomic) unsigned int sessionId;
@property (nonatomic) BOOL hasIPSecTunnelStatus;
@property (nonatomic) BOOL iPSecTunnelStatus;
@property (readonly, nonatomic) BOOL hasCallEndReason;
@property (retain, nonatomic) NSString *callEndReason;
@property (nonatomic) BOOL hasATMRegistrationState;
@property (nonatomic) BOOL aTMRegistrationState;
@property (nonatomic) BOOL hasBBAudioPacketLoss;
@property (nonatomic) unsigned int bBAudioPacketLoss;
@property (nonatomic) BOOL hasBBAudioErasures;
@property (nonatomic) unsigned int bBAudioErasures;
@property (nonatomic) BOOL hasWiFiPreferred;
@property (nonatomic) BOOL wiFiPreferred;
@property (nonatomic) BOOL hasServingCellRAT;
@property (nonatomic) unsigned int servingCellRAT;
@property (nonatomic) BOOL hasServingCellSINR;
@property (nonatomic) int servingCellSINR;
@property (nonatomic) BOOL hasServingCellRSRP;
@property (nonatomic) long long servingCellRSRP;

- (unsigned long long)hash;
- (void)dealloc;
- (BOOL)readFrom:(id)a0;
- (void)writeTo:(id)a0;
- (id)description;
- (id)dictionaryRepresentation;
- (void)copyTo:(id)a0;
- (BOOL)isEqual:(id)a0;
- (void)mergeFrom:(id)a0;
- (id)copyWithZone:(struct _NSZone { } *)a0;

@end
