@class NSMutableDictionary, CLLocation, RTLocationStore, RTInvocationDispatcher, RTDefaultsManager, CLLocationManager, RTPlatform, RTTimerManager, NSMutableArray, CLLocationManagerRoutine, RTPowerAssertion, NSString, RTTimer, RTAuthorizationManager;

@interface RTLocationManager : RTService <CLLocationManagerDelegate, RTPurgable, RTStoreManager>

@property (retain, nonatomic) NSMutableArray *currentLocationHandlers;
@property (nonatomic) BOOL leechingLocations;
@property (nonatomic) BOOL monitoringLocations;
@property (retain, nonatomic) RTTimer *stopUpdatingLocationTimer;
@property (retain, nonatomic) RTPowerAssertion *powerAssertion;
@property (retain, nonatomic) RTInvocationDispatcher *dispatcher;
@property (nonatomic) BOOL updating;
@property (retain, nonatomic) CLLocationManager *locationManager;
@property (retain, nonatomic) CLLocationManagerRoutine *locationManagerRoutine;
@property (nonatomic) BOOL enabled;
@property (nonatomic) BOOL supported;
@property (nonatomic) BOOL locationStoreAvailable;
@property (nonatomic) BOOL persistingLocations;
@property (retain, nonatomic) CLLocation *lastLocation;
@property (retain, nonatomic) RTAuthorizationManager *authorizationManager;
@property (retain, nonatomic) RTLocationStore *locationStore;
@property (retain, nonatomic) RTPlatform *platform;
@property (retain, nonatomic) RTDefaultsManager *defaultsManager;
@property (retain, nonatomic) RTTimerManager *timerManager;
@property (retain, nonatomic) NSMutableDictionary *regionEventHandlerDictionary;
@property (retain, nonatomic) RTInvocationDispatcher *regionEventDispatcher;
@property (readonly) unsigned long long hash;
@property (readonly) Class superclass;
@property (readonly, copy) NSString *description;
@property (readonly, copy) NSString *debugDescription;

+ (id)stringForRegionCallbackType:(long long)a0;
+ (id)errorDuplicateClientIdentifier:(id)a0;
+ (BOOL)supportsNotificationName:(id)a0;
+ (id)errorUnregisteredClientIdentifier:(id)a0;
+ (id)regionIdentifierDelimiterString;
+ (id)errorUsedDelimiter;
+ (BOOL)isValidIdentifier:(id)a0;
+ (id)regionWithModifiedIdentifier:(id)a0 forRegion:(id)a1;
+ (id)vendedClasses;
+ (id)clientRegionForRegion:(id)a0 clientIdentifierPrefix:(id)a1;

- (void)_shutdown;
- (void)performPurgeOfType:(long long)a0 referenceDate:(id)a1 completion:(id /* block */)a2;
- (void)fetchEnumerableObjectsWithOptions:(id)a0 offset:(unsigned long long)a1 handler:(id /* block */)a2;
- (void)locationManager:(id)a0 didStartMonitoringForRegion:(id)a1;
- (void)unregisterForRegionEventsWithClientIdentifier:(id)a0 handler:(id /* block */)a1;
- (void)locationManager:(id)a0 didExitRegion:(id)a1;
- (void)locationManager:(id)a0 didDetermineState:(long long)a1 forRegion:(id)a2;
- (void)locationManager:(id)a0 monitoringDidFailForRegion:(id)a1 withError:(id)a2;
- (void)_setup;
- (void)registerForRegionEventsWithClientIdentifier:(id)a0 handler:(id /* block */)a1;
- (void)onAuthorizationNotification:(id)a0;
- (void)stopUpdatingLocation;
- (void)shouldLeechLocations;
- (void)fetchStoredLocationsWithOptions:(id)a0 handler:(id /* block */)a1;
- (void)startUpdatingLocation;
- (id)init;
- (void)locationManager:(id)a0 didUpdateLocations:(id)a1;
- (void)shouldPersistLocations;
- (void).cxx_destruct;
- (void)injectLocations:(id)a0 handler:(id /* block */)a1;
- (void)_storeLocations:(id)a0 handler:(id /* block */)a1;
- (void)_unregisterNotifications;
- (void)_fetchStoredLocationsWithOptions:(id)a0 handler:(id /* block */)a1;
- (void)fetchCachedLocationWithHandler:(id /* block */)a0;
- (void)fetchCurrentLocationWithHandler:(id /* block */)a0;
- (void)internalAddObserver:(id)a0 name:(id)a1;
- (void)fetchStoredLocationsCountFromDate:(id)a0 toDate:(id)a1 uncertainty:(double)a2 limit:(unsigned long long)a3 handler:(id /* block */)a4;
- (void)_fetchStoredLocationsCountFromDate:(id)a0 toDate:(id)a1 uncertainty:(double)a2 limit:(unsigned long long)a3 handler:(id /* block */)a4;
- (id)initWithAuthorizationManager:(id)a0 defaultsManager:(id)a1 locationStore:(id)a2 platform:(id)a3 routineLocationManager:(id)a4 timerManager:(id)a5;
- (void)performCallbackForRegion:(id)a0 regionEvent:(long long)a1 callbackError:(id)a2 handler:(id /* block */)a3;
- (void)submitHarvestSample:(id)a0 handler:(id /* block */)a1;
- (id)_fullIdentifierForClientIdentifier:(id)a0 regionIdentifier:(id)a1 error:(id *)a2;
- (void)onStopUpdatingLocationTimerExpiry;
- (void)fetchStoredLocationsWithContext:(id)a0 handler:(id /* block */)a1;
- (BOOL)stopMonitoringAllRegionsForClientIdentifier:(id)a0 error:(id *)a1;
- (id)_prefixForClientIdentifier:(id)a0 error:(id *)a1;
- (BOOL)_isClientIdentifierAvailable:(id)a0;
- (void)_registerForRegionEventsWithClientIdentifier:(id)a0 handler:(id /* block */)a1;
- (void)internalRemoveObserver:(id)a0 name:(id)a1;
- (BOOL)startMonitoringForRegion:(id)a0 clientIdentifier:(id)a1 error:(id *)a2;
- (void)locationManager:(id)a0 didEnterRegion:(id)a1;
- (void)_unregisterForRegionEventsWithClientIdentifier:(id)a0 handler:(id /* block */)a1;
- (id)_clientIdentifierForRegion:(id)a0;
- (BOOL)_performCallbackForClientRegion:(id)a0 clientIdentifier:(id)a1 regionEvent:(long long)a2 callbackError:(id)a3 handler:(id /* block */)a4;
- (void)onLocationStoreNotification:(id)a0;
- (BOOL)_performCallbackForRegion:(id)a0 regionEvent:(long long)a1 callbackError:(id)a2 handler:(id /* block */)a3;
- (void)_fetchStoredLocationsWithContext:(id)a0 handler:(id /* block */)a1;
- (void)_registerNotifications;
- (void)onUserSessionChangeNotification:(id)a0;
- (void)shouldMonitorLocations;
- (BOOL)_stopMonitoringAllRegionsForClientIdentifier:(id)a0 error:(id *)a1;
- (void)_createLocationManager;
- (void)_removeLocationsPredating:(id)a0 handler:(id /* block */)a1;
- (BOOL)stopMonitoringForRegion:(id)a0 clientIdentifier:(id)a1 error:(id *)a2;
- (id)_regionForClientRegion:(id)a0 clientIdentifier:(id)a1 error:(id *)a2;
- (void)locationManager:(id)a0 didChangeAuthorizationStatus:(int)a1;

@end
