@interface AWDNFCGeneralStatistic : PBCodable <NSCopying> {
    struct { unsigned char startTimestamp : 1; unsigned char timestamp : 1; unsigned char seCounterMeasureLevel : 1; unsigned char totalAPNReceived : 1; unsigned char totalAccessTransaction : 1; unsigned char totalAuthECommerce : 1; unsigned char totalBurnoutTimerCounter : 1; unsigned char totalCEEnable : 1; unsigned char totalCEEnabledWithMissingTransactionEndEvent : 1; unsigned char totalCEEnabledWithNoFieldDetected : 1; unsigned char totalCardProvisioned : 1; unsigned char totalDynamicPackages : 1; unsigned char totalDynamicRFParametersUpdate : 1; unsigned char totalExpressFelicaTransaction : 1; unsigned char totalFailureWithMissingTransactionEndEvent : 1; unsigned char totalFailureWithTransactionEndEventErrors : 1; unsigned char totalFelicaEMoneyTransaction : 1; unsigned char totalFelicaTransitTransaction : 1; unsigned char totalGenericAExpressTransaction : 1; unsigned char totalLPEMCounter : 1; unsigned char totalPTDatabaseCorruption : 1; unsigned char totalPTKeyDeletionFailed : 1; unsigned char totalPTKeys : 1; unsigned char totalPeerPaymentRequest : 1; unsigned char totalPeerPaymentRequestFailure : 1; unsigned char totalPlasticCardModeEnable : 1; unsigned char totalRestrictModeEntered : 1; unsigned char totalSuccessfulCardIngestion : 1; unsigned char totalSuccessfulCardIngestionWithSessionToken : 1; unsigned char totalSuccessfulVAS : 1; unsigned char totalTransactionEndEvent : 1; unsigned char totalTransientDeactiveTimeout : 1; unsigned char totalVASActivation : 1; unsigned char totalVASSignup : 1; unsigned char totalVASTransactionException : 1; unsigned char hasAccessExpressTransactionEnable : 1; unsigned char hasAttackLogs : 1; unsigned char hasFelicaExpressTransactionEnable : 1; unsigned char hasGenericAExpressEnable : 1; } _has;
}

@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) unsigned long long timestamp;
@property (nonatomic) BOOL hasStartTimestamp;
@property (nonatomic) unsigned long long startTimestamp;
@property (nonatomic) BOOL hasTotalCEEnable;
@property (nonatomic) unsigned int totalCEEnable;
@property (nonatomic) BOOL hasTotalCardProvisioned;
@property (nonatomic) unsigned int totalCardProvisioned;
@property (nonatomic) BOOL hasTotalTransientDeactiveTimeout;
@property (nonatomic) unsigned int totalTransientDeactiveTimeout;
@property (nonatomic) BOOL hasTotalAPNReceived;
@property (nonatomic) unsigned int totalAPNReceived;
@property (nonatomic) BOOL hasTotalRestrictModeEntered;
@property (nonatomic) unsigned int totalRestrictModeEntered;
@property (nonatomic) BOOL hasTotalTransactionEndEvent;
@property (nonatomic) unsigned int totalTransactionEndEvent;
@property (nonatomic) BOOL hasTotalFailureWithTransactionEndEventErrors;
@property (nonatomic) unsigned int totalFailureWithTransactionEndEventErrors;
@property (nonatomic) BOOL hasTotalFailureWithMissingTransactionEndEvent;
@property (nonatomic) unsigned int totalFailureWithMissingTransactionEndEvent;
@property (nonatomic) BOOL hasTotalAuthECommerce;
@property (nonatomic) unsigned int totalAuthECommerce;
@property (nonatomic) BOOL hasTotalVASActivation;
@property (nonatomic) unsigned int totalVASActivation;
@property (nonatomic) BOOL hasTotalSuccessfulVAS;
@property (nonatomic) unsigned int totalSuccessfulVAS;
@property (nonatomic) BOOL hasTotalVASSignup;
@property (nonatomic) unsigned int totalVASSignup;
@property (nonatomic) BOOL hasTotalVASTransactionException;
@property (nonatomic) unsigned int totalVASTransactionException;
@property (nonatomic) BOOL hasTotalExpressFelicaTransaction;
@property (nonatomic) unsigned int totalExpressFelicaTransaction;
@property (nonatomic) BOOL hasTotalFelicaEMoneyTransaction;
@property (nonatomic) unsigned int totalFelicaEMoneyTransaction;
@property (nonatomic) BOOL hasTotalFelicaTransitTransaction;
@property (nonatomic) unsigned int totalFelicaTransitTransaction;
@property (nonatomic) BOOL hasHasFelicaExpressTransactionEnable;
@property (nonatomic) BOOL hasFelicaExpressTransactionEnable;
@property (nonatomic) BOOL hasTotalSuccessfulCardIngestion;
@property (nonatomic) unsigned int totalSuccessfulCardIngestion;
@property (nonatomic) BOOL hasTotalSuccessfulCardIngestionWithSessionToken;
@property (nonatomic) unsigned int totalSuccessfulCardIngestionWithSessionToken;
@property (nonatomic) BOOL hasTotalPlasticCardModeEnable;
@property (nonatomic) unsigned int totalPlasticCardModeEnable;
@property (nonatomic) BOOL hasTotalAccessTransaction;
@property (nonatomic) unsigned int totalAccessTransaction;
@property (nonatomic) BOOL hasHasAccessExpressTransactionEnable;
@property (nonatomic) BOOL hasAccessExpressTransactionEnable;
@property (nonatomic) BOOL hasHasAttackLogs;
@property (nonatomic) BOOL hasAttackLogs;
@property (nonatomic) BOOL hasTotalDynamicPackages;
@property (nonatomic) unsigned int totalDynamicPackages;
@property (nonatomic) BOOL hasTotalPeerPaymentRequest;
@property (nonatomic) unsigned int totalPeerPaymentRequest;
@property (nonatomic) BOOL hasTotalPeerPaymentRequestFailure;
@property (nonatomic) unsigned int totalPeerPaymentRequestFailure;
@property (nonatomic) BOOL hasHasGenericAExpressEnable;
@property (nonatomic) BOOL hasGenericAExpressEnable;
@property (nonatomic) BOOL hasTotalGenericAExpressTransaction;
@property (nonatomic) unsigned int totalGenericAExpressTransaction;
@property (nonatomic) BOOL hasTotalDynamicRFParametersUpdate;
@property (nonatomic) unsigned int totalDynamicRFParametersUpdate;
@property (nonatomic) BOOL hasTotalCEEnabledWithNoFieldDetected;
@property (nonatomic) unsigned int totalCEEnabledWithNoFieldDetected;
@property (nonatomic) BOOL hasTotalCEEnabledWithMissingTransactionEndEvent;
@property (nonatomic) unsigned int totalCEEnabledWithMissingTransactionEndEvent;
@property (nonatomic) BOOL hasTotalPTKeys;
@property (nonatomic) unsigned int totalPTKeys;
@property (nonatomic) BOOL hasTotalPTDatabaseCorruption;
@property (nonatomic) unsigned int totalPTDatabaseCorruption;
@property (nonatomic) BOOL hasTotalPTKeyDeletionFailed;
@property (nonatomic) unsigned int totalPTKeyDeletionFailed;
@property (nonatomic) BOOL hasTotalLPEMCounter;
@property (nonatomic) unsigned int totalLPEMCounter;
@property (nonatomic) BOOL hasSeCounterMeasureLevel;
@property (nonatomic) unsigned int seCounterMeasureLevel;
@property (nonatomic) BOOL hasTotalBurnoutTimerCounter;
@property (nonatomic) unsigned int totalBurnoutTimerCounter;

- (id)copyWithZone:(struct _NSZone { } *)a0;
- (void)mergeFrom:(id)a0;
- (BOOL)readFrom:(id)a0;
- (unsigned long long)hash;
- (void)writeTo:(id)a0;
- (id)description;
- (void)copyTo:(id)a0;
- (BOOL)isEqual:(id)a0;
- (id)dictionaryRepresentation;

@end
