@interface AWDBiometricKitAttentionCheck : PBCodable <NSCopying> {
    struct { unsigned char overallTime : 1; unsigned char timestamp : 1; unsigned char ambientLux : 1; unsigned char camRectH : 1; unsigned char camRectW : 1; unsigned char camRectX : 1; unsigned char camRectY : 1; unsigned char cameraErr : 1; unsigned char deviceOrientation : 1; unsigned char faceDetectFrameCount : 1; unsigned char faceDetectFrameDenseCount : 1; unsigned char faceDetectFrameFloodCount : 1; unsigned char faceDetectFrameSparseCount : 1; unsigned char faceDetectResult : 1; unsigned char faceDistance : 1; unsigned char faceOrientation : 1; unsigned char facePitch : 1; unsigned char faceRoll : 1; unsigned char faceYaw : 1; unsigned char ppmAllocatedBudget : 1; unsigned char ppmRequestedBudget : 1; unsigned char sensorTemperature : 1; unsigned char attentionDetectFailed : 1; unsigned char engagementInfoFeedbackCameraObstructed : 1; unsigned char engagementInfoFeedbackFaceOccluded : 1; unsigned char engagementInfoFeedbackFaceTooClose : 1; unsigned char engagementInfoFeedbackFaceTooFar : 1; unsigned char engagementInfoFeedbackNoAttention : 1; unsigned char engagementInfoFeedbackNoFaceDetected : 1; unsigned char engagementInfoFeedbackNoseAndMouthOccluded : 1; unsigned char engagementInfoFeedbackPartialOutOfFOV : 1; unsigned char engagementInfoFeedbackPoseMarginal : 1; unsigned char engagementInfoFeedbackPoseOutOfRange : 1; unsigned char faceDetectFailed : 1; unsigned char hasOcclusion : 1; } _has;
}

@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) unsigned long long timestamp;
@property (nonatomic) BOOL hasOverallTime;
@property (nonatomic) unsigned long long overallTime;
@property (nonatomic) BOOL hasFaceDetectResult;
@property (nonatomic) unsigned int faceDetectResult;
@property (nonatomic) BOOL hasFaceDetectFrameCount;
@property (nonatomic) unsigned int faceDetectFrameCount;
@property (nonatomic) BOOL hasFaceDetectFrameFloodCount;
@property (nonatomic) unsigned int faceDetectFrameFloodCount;
@property (nonatomic) BOOL hasFaceDetectFrameSparseCount;
@property (nonatomic) unsigned int faceDetectFrameSparseCount;
@property (nonatomic) BOOL hasFaceDetectFrameDenseCount;
@property (nonatomic) unsigned int faceDetectFrameDenseCount;
@property (nonatomic) BOOL hasAmbientLux;
@property (nonatomic) int ambientLux;
@property (nonatomic) BOOL hasCameraErr;
@property (nonatomic) int cameraErr;
@property (nonatomic) BOOL hasSensorTemperature;
@property (nonatomic) int sensorTemperature;
@property (nonatomic) BOOL hasFaceDistance;
@property (nonatomic) unsigned int faceDistance;
@property (nonatomic) BOOL hasHasOcclusion;
@property (nonatomic) BOOL hasOcclusion;
@property (nonatomic) BOOL hasCamRectX;
@property (nonatomic) unsigned int camRectX;
@property (nonatomic) BOOL hasCamRectY;
@property (nonatomic) unsigned int camRectY;
@property (nonatomic) BOOL hasCamRectW;
@property (nonatomic) unsigned int camRectW;
@property (nonatomic) BOOL hasCamRectH;
@property (nonatomic) unsigned int camRectH;
@property (nonatomic) BOOL hasPpmRequestedBudget;
@property (nonatomic) unsigned int ppmRequestedBudget;
@property (nonatomic) BOOL hasPpmAllocatedBudget;
@property (nonatomic) unsigned int ppmAllocatedBudget;
@property (nonatomic) BOOL hasFaceDetectFailed;
@property (nonatomic) BOOL faceDetectFailed;
@property (nonatomic) BOOL hasAttentionDetectFailed;
@property (nonatomic) BOOL attentionDetectFailed;
@property (nonatomic) BOOL hasDeviceOrientation;
@property (nonatomic) unsigned int deviceOrientation;
@property (nonatomic) BOOL hasEngagementInfoFeedbackNoFaceDetected;
@property (nonatomic) BOOL engagementInfoFeedbackNoFaceDetected;
@property (nonatomic) BOOL hasEngagementInfoFeedbackFaceTooClose;
@property (nonatomic) BOOL engagementInfoFeedbackFaceTooClose;
@property (nonatomic) BOOL hasEngagementInfoFeedbackFaceTooFar;
@property (nonatomic) BOOL engagementInfoFeedbackFaceTooFar;
@property (nonatomic) BOOL hasEngagementInfoFeedbackPoseOutOfRange;
@property (nonatomic) BOOL engagementInfoFeedbackPoseOutOfRange;
@property (nonatomic) BOOL hasEngagementInfoFeedbackNoAttention;
@property (nonatomic) BOOL engagementInfoFeedbackNoAttention;
@property (nonatomic) BOOL hasEngagementInfoFeedbackFaceOccluded;
@property (nonatomic) BOOL engagementInfoFeedbackFaceOccluded;
@property (nonatomic) BOOL hasEngagementInfoFeedbackCameraObstructed;
@property (nonatomic) BOOL engagementInfoFeedbackCameraObstructed;
@property (nonatomic) BOOL hasEngagementInfoFeedbackPartialOutOfFOV;
@property (nonatomic) BOOL engagementInfoFeedbackPartialOutOfFOV;
@property (nonatomic) BOOL hasEngagementInfoFeedbackPoseMarginal;
@property (nonatomic) BOOL engagementInfoFeedbackPoseMarginal;
@property (nonatomic) BOOL hasFaceOrientation;
@property (nonatomic) unsigned int faceOrientation;
@property (nonatomic) BOOL hasFacePitch;
@property (nonatomic) int facePitch;
@property (nonatomic) BOOL hasFaceYaw;
@property (nonatomic) int faceYaw;
@property (nonatomic) BOOL hasFaceRoll;
@property (nonatomic) int faceRoll;
@property (nonatomic) BOOL hasEngagementInfoFeedbackNoseAndMouthOccluded;
@property (nonatomic) BOOL engagementInfoFeedbackNoseAndMouthOccluded;

- (BOOL)readFrom:(id)a0;
- (id)description;
- (void)mergeFrom:(id)a0;
- (BOOL)isEqual:(id)a0;
- (void)writeTo:(id)a0;
- (id)copyWithZone:(struct _NSZone { } *)a0;
- (void)copyTo:(id)a0;
- (unsigned long long)hash;
- (id)dictionaryRepresentation;

@end
