@interface AWDNWAPIUsage : PBCodable <NSCopying> {
    struct { unsigned char ifFltrAttach : 1; unsigned char ifFltrAttachOs : 1; unsigned char ifnetAlloc : 1; unsigned char ifnetAllocOs : 1; unsigned char ipFltrAdd : 1; unsigned char ipFltrAddOs : 1; unsigned char nexusFlowInet6Datagram : 1; unsigned char nexusFlowInet6Stream : 1; unsigned char nexusFlowInetDatagram : 1; unsigned char nexusFlowInetStream : 1; unsigned char pfAddrule : 1; unsigned char pfAddruleOs : 1; unsigned char sockAlloc : 1; unsigned char sockAllocKernel : 1; unsigned char sockAllocKernelOs : 1; unsigned char sockDomainInet : 1; unsigned char sockDomainInet6 : 1; unsigned char sockDomainKey : 1; unsigned char sockDomainLocal : 1; unsigned char sockDomainMultipath : 1; unsigned char sockDomainNdrv : 1; unsigned char sockDomainOther : 1; unsigned char sockDomainRoute : 1; unsigned char sockDomainSystem : 1; unsigned char sockFltrRegister : 1; unsigned char sockFltrRegisterOs : 1; unsigned char sockInetMcastJoin : 1; unsigned char sockInetMcastJoinOs : 1; unsigned char sockNecpClientuuidCount : 1; unsigned char sockNetInet6Dgram : 1; unsigned char sockNetInet6DgramConnected : 1; unsigned char sockNetInet6DgramDns : 1; unsigned char sockNetInet6DgramNoData : 1; unsigned char sockNetInet6Stream : 1; unsigned char sockNetInetDgram : 1; unsigned char sockNetInetDgramConnected : 1; unsigned char sockNetInetDgramDns : 1; unsigned char sockNetInetDgramNoData : 1; unsigned char sockNetInetStream : 1; unsigned char timeSinceLastReport : 1; unsigned char timestamp : 1; unsigned char vmnetStart : 1; unsigned char ifNetagentEnabled : 1; } _has;
}

@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) unsigned long long timestamp;
@property (nonatomic) BOOL hasIfFltrAttach;
@property (nonatomic) long long ifFltrAttach;
@property (nonatomic) BOOL hasIfFltrAttachOs;
@property (nonatomic) long long ifFltrAttachOs;
@property (nonatomic) BOOL hasIpFltrAdd;
@property (nonatomic) long long ipFltrAdd;
@property (nonatomic) BOOL hasIpFltrAddOs;
@property (nonatomic) long long ipFltrAddOs;
@property (nonatomic) BOOL hasSockFltrRegister;
@property (nonatomic) long long sockFltrRegister;
@property (nonatomic) BOOL hasSockFltrRegisterOs;
@property (nonatomic) long long sockFltrRegisterOs;
@property (nonatomic) BOOL hasSockAlloc;
@property (nonatomic) long long sockAlloc;
@property (nonatomic) BOOL hasSockAllocKernel;
@property (nonatomic) long long sockAllocKernel;
@property (nonatomic) BOOL hasSockAllocKernelOs;
@property (nonatomic) long long sockAllocKernelOs;
@property (nonatomic) BOOL hasSockNecpClientuuidCount;
@property (nonatomic) long long sockNecpClientuuidCount;
@property (nonatomic) BOOL hasSockDomainLocal;
@property (nonatomic) long long sockDomainLocal;
@property (nonatomic) BOOL hasSockDomainRoute;
@property (nonatomic) long long sockDomainRoute;
@property (nonatomic) BOOL hasSockDomainInet;
@property (nonatomic) long long sockDomainInet;
@property (nonatomic) BOOL hasSockDomainInet6;
@property (nonatomic) long long sockDomainInet6;
@property (nonatomic) BOOL hasSockDomainSystem;
@property (nonatomic) long long sockDomainSystem;
@property (nonatomic) BOOL hasSockDomainMultipath;
@property (nonatomic) long long sockDomainMultipath;
@property (nonatomic) BOOL hasSockDomainKey;
@property (nonatomic) long long sockDomainKey;
@property (nonatomic) BOOL hasSockDomainNdrv;
@property (nonatomic) long long sockDomainNdrv;
@property (nonatomic) BOOL hasSockDomainOther;
@property (nonatomic) long long sockDomainOther;
@property (nonatomic) BOOL hasSockNetInetStream;
@property (nonatomic) long long sockNetInetStream;
@property (nonatomic) BOOL hasSockNetInetDgram;
@property (nonatomic) long long sockNetInetDgram;
@property (nonatomic) BOOL hasSockNetInetDgramConnected;
@property (nonatomic) long long sockNetInetDgramConnected;
@property (nonatomic) BOOL hasSockNetInetDgramDns;
@property (nonatomic) long long sockNetInetDgramDns;
@property (nonatomic) BOOL hasSockNetInetDgramNoData;
@property (nonatomic) long long sockNetInetDgramNoData;
@property (nonatomic) BOOL hasSockNetInet6Stream;
@property (nonatomic) long long sockNetInet6Stream;
@property (nonatomic) BOOL hasSockNetInet6Dgram;
@property (nonatomic) long long sockNetInet6Dgram;
@property (nonatomic) BOOL hasSockNetInet6DgramConnected;
@property (nonatomic) long long sockNetInet6DgramConnected;
@property (nonatomic) BOOL hasSockNetInet6DgramDns;
@property (nonatomic) long long sockNetInet6DgramDns;
@property (nonatomic) BOOL hasSockNetInet6DgramNoData;
@property (nonatomic) long long sockNetInet6DgramNoData;
@property (nonatomic) BOOL hasSockInetMcastJoin;
@property (nonatomic) long long sockInetMcastJoin;
@property (nonatomic) BOOL hasSockInetMcastJoinOs;
@property (nonatomic) long long sockInetMcastJoinOs;
@property (nonatomic) BOOL hasNexusFlowInetStream;
@property (nonatomic) long long nexusFlowInetStream;
@property (nonatomic) BOOL hasNexusFlowInetDatagram;
@property (nonatomic) long long nexusFlowInetDatagram;
@property (nonatomic) BOOL hasNexusFlowInet6Stream;
@property (nonatomic) long long nexusFlowInet6Stream;
@property (nonatomic) BOOL hasNexusFlowInet6Datagram;
@property (nonatomic) long long nexusFlowInet6Datagram;
@property (nonatomic) BOOL hasIfnetAlloc;
@property (nonatomic) long long ifnetAlloc;
@property (nonatomic) BOOL hasIfnetAllocOs;
@property (nonatomic) long long ifnetAllocOs;
@property (nonatomic) BOOL hasPfAddrule;
@property (nonatomic) long long pfAddrule;
@property (nonatomic) BOOL hasPfAddruleOs;
@property (nonatomic) long long pfAddruleOs;
@property (nonatomic) BOOL hasVmnetStart;
@property (nonatomic) long long vmnetStart;
@property (nonatomic) BOOL hasIfNetagentEnabled;
@property (nonatomic) BOOL ifNetagentEnabled;
@property (nonatomic) BOOL hasTimeSinceLastReport;
@property (nonatomic) unsigned long long timeSinceLastReport;

- (BOOL)readFrom:(id)a0;
- (id)description;
- (void)mergeFrom:(id)a0;
- (BOOL)isEqual:(id)a0;
- (void)writeTo:(id)a0;
- (id)copyWithZone:(struct _NSZone { } *)a0;
- (void)copyTo:(id)a0;
- (unsigned long long)hash;
- (id)dictionaryRepresentation;

@end
