@interface AWDWiFiCLTMSliceSpecific : PBCodable <NSCopying> {
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _batteryVoltageBucketeds;
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _cltmIndexBucketeds;
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _numActiveChainsBucketeds;
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _ppmBucketeds;
    struct { int *list; unsigned long long count; unsigned long long size; } _temperatureBucketeds;
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _txDutyCycleBucketeds;
    struct { int *list; unsigned long long count; unsigned long long size; } _txPowerBackoffBucketeds;
    struct { unsigned char timestamp : 1; unsigned char updateCount : 1; unsigned char batteryVoltage : 1; unsigned char cltmIndex : 1; unsigned char numActiveChains : 1; unsigned char ppm : 1; unsigned char temperature : 1; unsigned char txDutyCycle : 1; unsigned char txPowerBackoff : 1; } _has;
}

@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) unsigned long long timestamp;
@property (nonatomic) BOOL hasTxDutyCycle;
@property (nonatomic) unsigned int txDutyCycle;
@property (nonatomic) BOOL hasTxPowerBackoff;
@property (nonatomic) int txPowerBackoff;
@property (nonatomic) BOOL hasNumActiveChains;
@property (nonatomic) unsigned int numActiveChains;
@property (nonatomic) BOOL hasTemperature;
@property (nonatomic) int temperature;
@property (nonatomic) BOOL hasBatteryVoltage;
@property (nonatomic) unsigned int batteryVoltage;
@property (readonly, nonatomic) unsigned long long txDutyCycleBucketedsCount;
@property (readonly, nonatomic) unsigned int *txDutyCycleBucketeds;
@property (readonly, nonatomic) unsigned long long txPowerBackoffBucketedsCount;
@property (readonly, nonatomic) int *txPowerBackoffBucketeds;
@property (readonly, nonatomic) unsigned long long numActiveChainsBucketedsCount;
@property (readonly, nonatomic) unsigned int *numActiveChainsBucketeds;
@property (readonly, nonatomic) unsigned long long temperatureBucketedsCount;
@property (readonly, nonatomic) int *temperatureBucketeds;
@property (readonly, nonatomic) unsigned long long batteryVoltageBucketedsCount;
@property (readonly, nonatomic) unsigned int *batteryVoltageBucketeds;
@property (nonatomic) BOOL hasCltmIndex;
@property (nonatomic) unsigned int cltmIndex;
@property (nonatomic) BOOL hasPpm;
@property (nonatomic) unsigned int ppm;
@property (nonatomic) BOOL hasUpdateCount;
@property (nonatomic) unsigned long long updateCount;
@property (readonly, nonatomic) unsigned long long cltmIndexBucketedsCount;
@property (readonly, nonatomic) unsigned int *cltmIndexBucketeds;
@property (readonly, nonatomic) unsigned long long ppmBucketedsCount;
@property (readonly, nonatomic) unsigned int *ppmBucketeds;

- (BOOL)readFrom:(id)a0;
- (id)description;
- (void)mergeFrom:(id)a0;
- (BOOL)isEqual:(id)a0;
- (void)writeTo:(id)a0;
- (id)copyWithZone:(struct _NSZone { } *)a0;
- (void)copyTo:(id)a0;
- (unsigned long long)hash;
- (void)dealloc;
- (id)dictionaryRepresentation;
- (void)clearTxDutyCycleBucketeds;
- (unsigned int)txDutyCycleBucketedAtIndex:(unsigned long long)a0;
- (void)addTxDutyCycleBucketed:(unsigned int)a0;
- (void)clearTxPowerBackoffBucketeds;
- (int)txPowerBackoffBucketedAtIndex:(unsigned long long)a0;
- (void)addTxPowerBackoffBucketed:(int)a0;
- (void)clearNumActiveChainsBucketeds;
- (unsigned int)numActiveChainsBucketedAtIndex:(unsigned long long)a0;
- (void)addNumActiveChainsBucketed:(unsigned int)a0;
- (void)clearTemperatureBucketeds;
- (int)temperatureBucketedAtIndex:(unsigned long long)a0;
- (void)addTemperatureBucketed:(int)a0;
- (void)clearBatteryVoltageBucketeds;
- (unsigned int)batteryVoltageBucketedAtIndex:(unsigned long long)a0;
- (void)addBatteryVoltageBucketed:(unsigned int)a0;
- (void)clearCltmIndexBucketeds;
- (unsigned int)cltmIndexBucketedAtIndex:(unsigned long long)a0;
- (void)addCltmIndexBucketed:(unsigned int)a0;
- (void)clearPpmBucketeds;
- (unsigned int)ppmBucketedAtIndex:(unsigned long long)a0;
- (void)addPpmBucketed:(unsigned int)a0;
- (void)setTxDutyCycleBucketeds:(unsigned int *)a0 count:(unsigned long long)a1;
- (void)setTxPowerBackoffBucketeds:(int *)a0 count:(unsigned long long)a1;
- (void)setNumActiveChainsBucketeds:(unsigned int *)a0 count:(unsigned long long)a1;
- (void)setTemperatureBucketeds:(int *)a0 count:(unsigned long long)a1;
- (void)setBatteryVoltageBucketeds:(unsigned int *)a0 count:(unsigned long long)a1;
- (void)setCltmIndexBucketeds:(unsigned int *)a0 count:(unsigned long long)a1;
- (void)setPpmBucketeds:(unsigned int *)a0 count:(unsigned long long)a1;

@end
