@class NSString;

@interface AWDWRMLinkPrefChangeEvent : PBCodable <NSCopying> {
    struct { unsigned int *list; unsigned long long count; unsigned long long size; } _changeReasons;
    struct { unsigned char ccStatusUpdateDelay : 1; unsigned char timestamp : 1; unsigned char wifiRssi : 1; unsigned char wifiSNR : 1; unsigned char bcnPer : 1; unsigned char bssLoad : 1; unsigned char callStatus : 1; unsigned char ccStatusUpdate : 1; unsigned char cca : 1; unsigned char cellRSRP : 1; unsigned char cellSINR : 1; unsigned char changeDirection : 1; unsigned char dataAppStatus : 1; unsigned char dataLQM : 1; unsigned char dataLinkPref : 1; unsigned char decisionVIBE : 1; unsigned char decisionVO : 1; unsigned char expectedThroughputVIBE : 1; unsigned char expectedThroughputVO : 1; unsigned char lqmScoreWifi : 1; unsigned char motionState : 1; unsigned char packetLifetimeVIBE : 1; unsigned char pkgLifeTimeVO : 1; unsigned char pktLossRateVO : 1; unsigned char qbssLoad : 1; unsigned char serviceType : 1; unsigned char serviceTypeOfLastGrant : 1; unsigned char signalBar : 1; unsigned char stationCount : 1; unsigned char timeToLastDecision : 1; unsigned char timeToLastReverseDecision : 1; unsigned char timeToLastReverseGrant : 1; unsigned char voiceLQM : 1; unsigned char voiceLinkPref : 1; unsigned char wifiEstimatedBandwitdh : 1; unsigned char wifiRxPhyRate : 1; unsigned char wifiRxRetry : 1; unsigned char wifiTxPER : 1; unsigned char wifiTxPhyRate : 1; unsigned char captiveNetworks : 1; } _has;
}

@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) unsigned long long timestamp;
@property (nonatomic) BOOL hasChangeDirection;
@property (nonatomic) unsigned int changeDirection;
@property (nonatomic) BOOL hasServiceType;
@property (nonatomic) unsigned int serviceType;
@property (nonatomic) BOOL hasVoiceLinkPref;
@property (nonatomic) unsigned int voiceLinkPref;
@property (nonatomic) BOOL hasDataLinkPref;
@property (nonatomic) unsigned int dataLinkPref;
@property (nonatomic) BOOL hasCallStatus;
@property (nonatomic) unsigned int callStatus;
@property (nonatomic) BOOL hasDataAppStatus;
@property (nonatomic) unsigned int dataAppStatus;
@property (readonly, nonatomic) BOOL hasAppType;
@property (retain, nonatomic) NSString *appType;
@property (nonatomic) BOOL hasMotionState;
@property (nonatomic) int motionState;
@property (readonly, nonatomic) unsigned long long changeReasonsCount;
@property (readonly, nonatomic) unsigned int *changeReasons;
@property (nonatomic) BOOL hasWifiRssi;
@property (nonatomic) long long wifiRssi;
@property (nonatomic) BOOL hasWifiTxPER;
@property (nonatomic) unsigned int wifiTxPER;
@property (nonatomic) BOOL hasWifiSNR;
@property (nonatomic) long long wifiSNR;
@property (nonatomic) BOOL hasCaptiveNetworks;
@property (nonatomic) BOOL captiveNetworks;
@property (nonatomic) BOOL hasWifiRxRetry;
@property (nonatomic) unsigned int wifiRxRetry;
@property (nonatomic) BOOL hasWifiEstimatedBandwitdh;
@property (nonatomic) unsigned int wifiEstimatedBandwitdh;
@property (nonatomic) BOOL hasWifiTxPhyRate;
@property (nonatomic) unsigned int wifiTxPhyRate;
@property (nonatomic) BOOL hasWifiRxPhyRate;
@property (nonatomic) unsigned int wifiRxPhyRate;
@property (nonatomic) BOOL hasQbssLoad;
@property (nonatomic) unsigned int qbssLoad;
@property (nonatomic) BOOL hasCca;
@property (nonatomic) unsigned int cca;
@property (nonatomic) BOOL hasStationCount;
@property (nonatomic) unsigned int stationCount;
@property (nonatomic) BOOL hasBcnPer;
@property (nonatomic) unsigned int bcnPer;
@property (nonatomic) BOOL hasLqmScoreWifi;
@property (nonatomic) int lqmScoreWifi;
@property (nonatomic) BOOL hasExpectedThroughputVO;
@property (nonatomic) unsigned int expectedThroughputVO;
@property (nonatomic) BOOL hasPkgLifeTimeVO;
@property (nonatomic) unsigned int pkgLifeTimeVO;
@property (nonatomic) BOOL hasPktLossRateVO;
@property (nonatomic) unsigned int pktLossRateVO;
@property (nonatomic) BOOL hasDecisionVO;
@property (nonatomic) unsigned int decisionVO;
@property (nonatomic) BOOL hasExpectedThroughputVIBE;
@property (nonatomic) unsigned int expectedThroughputVIBE;
@property (nonatomic) BOOL hasPacketLifetimeVIBE;
@property (nonatomic) unsigned int packetLifetimeVIBE;
@property (nonatomic) BOOL hasDecisionVIBE;
@property (nonatomic) unsigned int decisionVIBE;
@property (nonatomic) BOOL hasDataLQM;
@property (nonatomic) int dataLQM;
@property (nonatomic) BOOL hasBssLoad;
@property (nonatomic) unsigned int bssLoad;
@property (nonatomic) BOOL hasVoiceLQM;
@property (nonatomic) unsigned int voiceLQM;
@property (nonatomic) BOOL hasSignalBar;
@property (nonatomic) unsigned int signalBar;
@property (readonly, nonatomic) BOOL hasRatType;
@property (retain, nonatomic) NSString *ratType;
@property (nonatomic) BOOL hasCellRSRP;
@property (nonatomic) int cellRSRP;
@property (nonatomic) BOOL hasCellSINR;
@property (nonatomic) int cellSINR;
@property (nonatomic) BOOL hasCcStatusUpdate;
@property (nonatomic) int ccStatusUpdate;
@property (nonatomic) BOOL hasCcStatusUpdateDelay;
@property (nonatomic) unsigned long long ccStatusUpdateDelay;
@property (nonatomic) BOOL hasTimeToLastDecision;
@property (nonatomic) unsigned int timeToLastDecision;
@property (nonatomic) BOOL hasTimeToLastReverseDecision;
@property (nonatomic) unsigned int timeToLastReverseDecision;
@property (nonatomic) BOOL hasTimeToLastReverseGrant;
@property (nonatomic) unsigned int timeToLastReverseGrant;
@property (nonatomic) BOOL hasServiceTypeOfLastGrant;
@property (nonatomic) unsigned int serviceTypeOfLastGrant;

- (BOOL)readFrom:(id)a0;
- (id)description;
- (void)mergeFrom:(id)a0;
- (BOOL)isEqual:(id)a0;
- (void)writeTo:(id)a0;
- (id)copyWithZone:(struct _NSZone { } *)a0;
- (void)copyTo:(id)a0;
- (unsigned long long)hash;
- (void)dealloc;
- (id)dictionaryRepresentation;
- (id)motionStateAsString:(int)a0;
- (int)StringAsMotionState:(id)a0;
- (void)clearChangeReasons;
- (unsigned int)changeReasonAtIndex:(unsigned long long)a0;
- (void)addChangeReason:(unsigned int)a0;
- (void)setChangeReasons:(unsigned int *)a0 count:(unsigned long long)a1;
- (id)ccStatusUpdateAsString:(int)a0;
- (int)StringAsCcStatusUpdate:(id)a0;

@end
