@class NSString, NSMutableArray, AWDWiFiNWActivityTxCompletions;

@interface AWDWiFiNWActivityPeerStats : PBCodable <NSCopying> {
    struct { unsigned char ccaValue : 1; unsigned char ibssCCA : 1; unsigned char interferenceCCA : 1; unsigned char nfValue : 1; unsigned char obssCCA : 1; unsigned char ofdmDesense : 1; unsigned char qbssCCA : 1; unsigned char qbssSTACount : 1; unsigned char role : 1; unsigned char rssiValue : 1; unsigned char snrValue : 1; } _has;
}

@property (nonatomic) BOOL hasRole;
@property (nonatomic) int role;
@property (readonly, nonatomic) BOOL hasHashID;
@property (retain, nonatomic) NSString *hashID;
@property (retain, nonatomic) NSMutableArray *rssis;
@property (retain, nonatomic) NSMutableArray *ccas;
@property (retain, nonatomic) NSMutableArray *snrs;
@property (retain, nonatomic) NSMutableArray *packets;
@property (retain, nonatomic) NSMutableArray *bytes;
@property (retain, nonatomic) NSMutableArray *txLatencyBKs;
@property (retain, nonatomic) NSMutableArray *txLatencyBEs;
@property (retain, nonatomic) NSMutableArray *txLatencyVOs;
@property (retain, nonatomic) NSMutableArray *txLatencyVIs;
@property (readonly, nonatomic) BOOL hasCompletions;
@property (retain, nonatomic) AWDWiFiNWActivityTxCompletions *completions;
@property (retain, nonatomic) NSMutableArray *acCompletions;
@property (nonatomic) BOOL hasRssiValue;
@property (nonatomic) int rssiValue;
@property (nonatomic) BOOL hasSnrValue;
@property (nonatomic) int snrValue;
@property (nonatomic) BOOL hasCcaValue;
@property (nonatomic) unsigned int ccaValue;
@property (nonatomic) BOOL hasNfValue;
@property (nonatomic) int nfValue;
@property (nonatomic) BOOL hasOfdmDesense;
@property (nonatomic) unsigned int ofdmDesense;
@property (nonatomic) BOOL hasIbssCCA;
@property (nonatomic) unsigned int ibssCCA;
@property (nonatomic) BOOL hasObssCCA;
@property (nonatomic) unsigned int obssCCA;
@property (nonatomic) BOOL hasInterferenceCCA;
@property (nonatomic) unsigned int interferenceCCA;
@property (nonatomic) BOOL hasQbssCCA;
@property (nonatomic) unsigned int qbssCCA;
@property (nonatomic) BOOL hasQbssSTACount;
@property (nonatomic) unsigned int qbssSTACount;
@property (retain, nonatomic) NSMutableArray *rxLatencyTID0s;
@property (retain, nonatomic) NSMutableArray *rxLatencyTID1s;
@property (retain, nonatomic) NSMutableArray *rxLatencyTID2s;
@property (retain, nonatomic) NSMutableArray *rxLatencyTID3s;
@property (retain, nonatomic) NSMutableArray *rxLatencyTID4s;
@property (retain, nonatomic) NSMutableArray *rxLatencyTID5s;
@property (retain, nonatomic) NSMutableArray *rxLatencyTID6s;
@property (retain, nonatomic) NSMutableArray *rxLatencyTID7s;

+ (Class)snrType;
+ (Class)ccaType;
+ (Class)packetsType;
+ (Class)bytesType;
+ (Class)rssiType;
+ (Class)txLatencyBKType;
+ (Class)txLatencyBEType;
+ (Class)txLatencyVOType;
+ (Class)txLatencyVIType;
+ (Class)acCompletionsType;
+ (Class)rxLatencyTID0Type;
+ (Class)rxLatencyTID1Type;
+ (Class)rxLatencyTID2Type;
+ (Class)rxLatencyTID3Type;
+ (Class)rxLatencyTID4Type;
+ (Class)rxLatencyTID5Type;
+ (Class)rxLatencyTID6Type;
+ (Class)rxLatencyTID7Type;

- (BOOL)readFrom:(id)a0;
- (id)description;
- (id)roleAsString:(int)a0;
- (int)StringAsRole:(id)a0;
- (void)mergeFrom:(id)a0;
- (BOOL)isEqual:(id)a0;
- (void)writeTo:(id)a0;
- (id)copyWithZone:(struct _NSZone { } *)a0;
- (void)copyTo:(id)a0;
- (void)addCca:(id)a0;
- (void)addSnr:(id)a0;
- (unsigned long long)hash;
- (void)dealloc;
- (id)dictionaryRepresentation;
- (void)addPackets:(id)a0;
- (void)addBytes:(id)a0;
- (unsigned long long)packetsCount;
- (void)clearPackets;
- (id)packetsAtIndex:(unsigned long long)a0;
- (unsigned long long)bytesCount;
- (void)clearBytes;
- (id)bytesAtIndex:(unsigned long long)a0;
- (void)addRssi:(id)a0;
- (void)addTxLatencyBK:(id)a0;
- (void)addTxLatencyBE:(id)a0;
- (void)addTxLatencyVO:(id)a0;
- (void)addTxLatencyVI:(id)a0;
- (void)addAcCompletions:(id)a0;
- (void)addRxLatencyTID0:(id)a0;
- (void)addRxLatencyTID1:(id)a0;
- (void)addRxLatencyTID2:(id)a0;
- (void)addRxLatencyTID3:(id)a0;
- (void)addRxLatencyTID4:(id)a0;
- (void)addRxLatencyTID5:(id)a0;
- (void)addRxLatencyTID6:(id)a0;
- (void)addRxLatencyTID7:(id)a0;
- (unsigned long long)rssisCount;
- (void)clearRssis;
- (id)rssiAtIndex:(unsigned long long)a0;
- (unsigned long long)ccasCount;
- (void)clearCcas;
- (id)ccaAtIndex:(unsigned long long)a0;
- (unsigned long long)snrsCount;
- (void)clearSnrs;
- (id)snrAtIndex:(unsigned long long)a0;
- (unsigned long long)txLatencyBKsCount;
- (void)clearTxLatencyBKs;
- (id)txLatencyBKAtIndex:(unsigned long long)a0;
- (unsigned long long)txLatencyBEsCount;
- (void)clearTxLatencyBEs;
- (id)txLatencyBEAtIndex:(unsigned long long)a0;
- (unsigned long long)txLatencyVOsCount;
- (void)clearTxLatencyVOs;
- (id)txLatencyVOAtIndex:(unsigned long long)a0;
- (unsigned long long)txLatencyVIsCount;
- (void)clearTxLatencyVIs;
- (id)txLatencyVIAtIndex:(unsigned long long)a0;
- (unsigned long long)acCompletionsCount;
- (void)clearAcCompletions;
- (id)acCompletionsAtIndex:(unsigned long long)a0;
- (unsigned long long)rxLatencyTID0sCount;
- (void)clearRxLatencyTID0s;
- (id)rxLatencyTID0AtIndex:(unsigned long long)a0;
- (unsigned long long)rxLatencyTID1sCount;
- (void)clearRxLatencyTID1s;
- (id)rxLatencyTID1AtIndex:(unsigned long long)a0;
- (unsigned long long)rxLatencyTID2sCount;
- (void)clearRxLatencyTID2s;
- (id)rxLatencyTID2AtIndex:(unsigned long long)a0;
- (unsigned long long)rxLatencyTID3sCount;
- (void)clearRxLatencyTID3s;
- (id)rxLatencyTID3AtIndex:(unsigned long long)a0;
- (unsigned long long)rxLatencyTID4sCount;
- (void)clearRxLatencyTID4s;
- (id)rxLatencyTID4AtIndex:(unsigned long long)a0;
- (unsigned long long)rxLatencyTID5sCount;
- (void)clearRxLatencyTID5s;
- (id)rxLatencyTID5AtIndex:(unsigned long long)a0;
- (unsigned long long)rxLatencyTID6sCount;
- (void)clearRxLatencyTID6s;
- (id)rxLatencyTID6AtIndex:(unsigned long long)a0;
- (unsigned long long)rxLatencyTID7sCount;
- (void)clearRxLatencyTID7s;
- (id)rxLatencyTID7AtIndex:(unsigned long long)a0;

@end
