@class AWDWiFiTDM, NSMutableArray;

@interface AWDWiFiNWActivityImpedingFunctions : PBCodable <NSCopying> {
    struct { unsigned char activechains0 : 1; unsigned char activechains1 : 1; unsigned char ctlmid0 : 1; unsigned char ctlmid1 : 1; unsigned char ppm0 : 1; unsigned char ppm1 : 1; unsigned char rc1Duration : 1; unsigned char rc1Request : 1; unsigned char rc1wlanCrit : 1; unsigned char rc1wlanCritDuration : 1; unsigned char rc2Duration : 1; unsigned char rc2Grant : 1; unsigned char rc2LongGrant : 1; unsigned char rc2Request : 1; unsigned char rc2cts2a : 1; unsigned char temp0 : 1; unsigned char temp1 : 1; unsigned char tvpmindex0 : 1; unsigned char tvpmindex1 : 1; unsigned char txduty0 : 1; unsigned char txduty1 : 1; unsigned char txpowerbackoff0 : 1; unsigned char txpowerbackoff1 : 1; unsigned char voltage0 : 1; unsigned char voltage1 : 1; } _has;
}

@property (retain, nonatomic) NSMutableArray *cTLMIndexs;
@property (retain, nonatomic) NSMutableArray *txPowerBackoffDBs;
@property (retain, nonatomic) NSMutableArray *txDutyCyclePcts;
@property (retain, nonatomic) NSMutableArray *cTLMIndex1s;
@property (retain, nonatomic) NSMutableArray *txPowerBackoffDB1s;
@property (retain, nonatomic) NSMutableArray *txDutyCyclePct1s;
@property (nonatomic) BOOL hasTxduty0;
@property (nonatomic) unsigned int txduty0;
@property (nonatomic) BOOL hasTxduty1;
@property (nonatomic) unsigned int txduty1;
@property (nonatomic) BOOL hasTxpowerbackoff0;
@property (nonatomic) unsigned int txpowerbackoff0;
@property (nonatomic) BOOL hasTxpowerbackoff1;
@property (nonatomic) unsigned int txpowerbackoff1;
@property (nonatomic) BOOL hasActivechains0;
@property (nonatomic) unsigned int activechains0;
@property (nonatomic) BOOL hasActivechains1;
@property (nonatomic) unsigned int activechains1;
@property (nonatomic) BOOL hasTemp0;
@property (nonatomic) unsigned int temp0;
@property (nonatomic) BOOL hasTemp1;
@property (nonatomic) unsigned int temp1;
@property (nonatomic) BOOL hasVoltage0;
@property (nonatomic) unsigned int voltage0;
@property (nonatomic) BOOL hasVoltage1;
@property (nonatomic) unsigned int voltage1;
@property (nonatomic) BOOL hasPpm0;
@property (nonatomic) unsigned int ppm0;
@property (nonatomic) BOOL hasPpm1;
@property (nonatomic) unsigned int ppm1;
@property (nonatomic) BOOL hasCtlmid0;
@property (nonatomic) unsigned int ctlmid0;
@property (nonatomic) BOOL hasCtlmid1;
@property (nonatomic) unsigned int ctlmid1;
@property (nonatomic) BOOL hasTvpmindex0;
@property (nonatomic) unsigned int tvpmindex0;
@property (nonatomic) BOOL hasTvpmindex1;
@property (nonatomic) unsigned int tvpmindex1;
@property (nonatomic) BOOL hasRc1Request;
@property (nonatomic) unsigned int rc1Request;
@property (nonatomic) BOOL hasRc1Duration;
@property (nonatomic) unsigned int rc1Duration;
@property (nonatomic) BOOL hasRc1wlanCrit;
@property (nonatomic) unsigned int rc1wlanCrit;
@property (nonatomic) BOOL hasRc1wlanCritDuration;
@property (nonatomic) unsigned int rc1wlanCritDuration;
@property (nonatomic) BOOL hasRc2Request;
@property (nonatomic) unsigned int rc2Request;
@property (nonatomic) BOOL hasRc2Duration;
@property (nonatomic) unsigned int rc2Duration;
@property (nonatomic) BOOL hasRc2Grant;
@property (nonatomic) unsigned int rc2Grant;
@property (nonatomic) BOOL hasRc2LongGrant;
@property (nonatomic) unsigned int rc2LongGrant;
@property (nonatomic) BOOL hasRc2cts2a;
@property (nonatomic) unsigned int rc2cts2a;
@property (readonly, nonatomic) BOOL hasSdbtdm;
@property (retain, nonatomic) AWDWiFiTDM *sdbtdm;

+ (Class)cTLMIndexType;
+ (Class)txPowerBackoffDBType;
+ (Class)txDutyCyclePctType;
+ (Class)cTLMIndex1Type;
+ (Class)txPowerBackoffDB1Type;
+ (Class)txDutyCyclePct1Type;

- (BOOL)readFrom:(id)a0;
- (id)description;
- (void)mergeFrom:(id)a0;
- (BOOL)isEqual:(id)a0;
- (void)writeTo:(id)a0;
- (id)copyWithZone:(struct _NSZone { } *)a0;
- (void)copyTo:(id)a0;
- (unsigned long long)hash;
- (void)dealloc;
- (id)dictionaryRepresentation;
- (void)addCTLMIndex:(id)a0;
- (void)addTxPowerBackoffDB:(id)a0;
- (void)addTxDutyCyclePct:(id)a0;
- (void)addCTLMIndex1:(id)a0;
- (void)addTxPowerBackoffDB1:(id)a0;
- (void)addTxDutyCyclePct1:(id)a0;
- (unsigned long long)cTLMIndexsCount;
- (void)clearCTLMIndexs;
- (id)cTLMIndexAtIndex:(unsigned long long)a0;
- (unsigned long long)txPowerBackoffDBsCount;
- (void)clearTxPowerBackoffDBs;
- (id)txPowerBackoffDBAtIndex:(unsigned long long)a0;
- (unsigned long long)txDutyCyclePctsCount;
- (void)clearTxDutyCyclePcts;
- (id)txDutyCyclePctAtIndex:(unsigned long long)a0;
- (unsigned long long)cTLMIndex1sCount;
- (void)clearCTLMIndex1s;
- (id)cTLMIndex1AtIndex:(unsigned long long)a0;
- (unsigned long long)txPowerBackoffDB1sCount;
- (void)clearTxPowerBackoffDB1s;
- (id)txPowerBackoffDB1AtIndex:(unsigned long long)a0;
- (unsigned long long)txDutyCyclePct1sCount;
- (void)clearTxDutyCyclePct1s;
- (id)txDutyCyclePct1AtIndex:(unsigned long long)a0;

@end
