@class NSString;

@interface AWDWRMWiFiCell5GData : PBCodable <NSCopying> {
    struct { unsigned char timestamp : 1; unsigned char applicationCategory : 1; unsigned char cellDataLQM : 1; unsigned char cellDlBw : 1; unsigned char cellEstimatedBw : 1; unsigned char cellEstimatedLoad : 1; unsigned char cellLteEstimatedThroughput : 1; unsigned char cellLteRSRP : 1; unsigned char cellLteRSRQ : 1; unsigned char cellLteSNR : 1; unsigned char cellMaxDlCaNumConfigured : 1; unsigned char cellMaxUlCaNumConfigured : 1; unsigned char cellNrEstimatedThroughput : 1; unsigned char cellNrFR2active : 1; unsigned char cellNrRSRP : 1; unsigned char cellNrRSRQ : 1; unsigned char cellNrSNR : 1; unsigned char cellNsaEnabled : 1; unsigned char cellRrcState : 1; unsigned char cellTotalMimoLayers : 1; unsigned char cellUlBw : 1; unsigned char cellularRecommendationConfidence : 1; unsigned char cellularRecommendationScore : 1; unsigned char locationDBFR1Count : 1; unsigned char locationDBFR2Count : 1; unsigned char radioCoverage : 1; unsigned char radioFrequency : 1; unsigned char recommendedlink : 1; unsigned char totalNrBandwidth : 1; unsigned char triggerReason : 1; unsigned char wRMRecommendationReason : 1; unsigned char wiFiPredictedThroughput : 1; unsigned char wiFiThroughput : 1; unsigned char wifPoi : 1; unsigned char wifiCca : 1; unsigned char wifiEstThoughtput : 1; unsigned char wifiQbssLoad : 1; unsigned char wifiRecommendationConfidence : 1; unsigned char wifiRecommendationScore : 1; unsigned char wifiRssi : 1; unsigned char wifiRxRetry : 1; unsigned char wifiSnr : 1; unsigned char wifiStationCount : 1; unsigned char wifiTxPER : 1; unsigned char wifiWghtAVGRXPHYRATE : 1; unsigned char wifiWghtAVGSNR : 1; unsigned char wifiWghtAVGTXPHYRATE : 1; unsigned char wifiWgtAVGRSSI : 1; unsigned char wifiWifiEstThoughtputConfidence : 1; unsigned char fr2DBRecommendation : 1; unsigned char highThermalTemperatureNotification : 1; } _has;
}

@property (nonatomic) BOOL hasTimestamp;
@property (nonatomic) unsigned long long timestamp;
@property (nonatomic) BOOL hasWifiRssi;
@property (nonatomic) int wifiRssi;
@property (nonatomic) BOOL hasWifiSnr;
@property (nonatomic) unsigned int wifiSnr;
@property (nonatomic) BOOL hasWifiTxPER;
@property (nonatomic) unsigned int wifiTxPER;
@property (nonatomic) BOOL hasWifiRxRetry;
@property (nonatomic) unsigned int wifiRxRetry;
@property (nonatomic) BOOL hasWifiCca;
@property (nonatomic) unsigned int wifiCca;
@property (nonatomic) BOOL hasWifiQbssLoad;
@property (nonatomic) unsigned int wifiQbssLoad;
@property (nonatomic) BOOL hasWifiStationCount;
@property (nonatomic) unsigned int wifiStationCount;
@property (nonatomic) BOOL hasWifPoi;
@property (nonatomic) unsigned int wifPoi;
@property (nonatomic) BOOL hasWifiWgtAVGRSSI;
@property (nonatomic) int wifiWgtAVGRSSI;
@property (nonatomic) BOOL hasWifiWghtAVGSNR;
@property (nonatomic) unsigned int wifiWghtAVGSNR;
@property (nonatomic) BOOL hasWifiWghtAVGTXPHYRATE;
@property (nonatomic) unsigned int wifiWghtAVGTXPHYRATE;
@property (nonatomic) BOOL hasWifiWghtAVGRXPHYRATE;
@property (nonatomic) unsigned int wifiWghtAVGRXPHYRATE;
@property (nonatomic) BOOL hasWifiEstThoughtput;
@property (nonatomic) unsigned int wifiEstThoughtput;
@property (nonatomic) BOOL hasWifiWifiEstThoughtputConfidence;
@property (nonatomic) unsigned int wifiWifiEstThoughtputConfidence;
@property (readonly, nonatomic) BOOL hasCellRatType;
@property (retain, nonatomic) NSString *cellRatType;
@property (nonatomic) BOOL hasCellLteRSRP;
@property (nonatomic) int cellLteRSRP;
@property (nonatomic) BOOL hasCellLteSNR;
@property (nonatomic) int cellLteSNR;
@property (nonatomic) BOOL hasCellLteRSRQ;
@property (nonatomic) int cellLteRSRQ;
@property (nonatomic) BOOL hasCellNrRSRP;
@property (nonatomic) int cellNrRSRP;
@property (nonatomic) BOOL hasCellNrRSRQ;
@property (nonatomic) int cellNrRSRQ;
@property (nonatomic) BOOL hasCellNrSNR;
@property (nonatomic) int cellNrSNR;
@property (nonatomic) BOOL hasCellDataLQM;
@property (nonatomic) unsigned int cellDataLQM;
@property (nonatomic) BOOL hasCellRrcState;
@property (nonatomic) unsigned int cellRrcState;
@property (nonatomic) BOOL hasCellNrFR2active;
@property (nonatomic) unsigned int cellNrFR2active;
@property (nonatomic) BOOL hasCellLteEstimatedThroughput;
@property (nonatomic) unsigned int cellLteEstimatedThroughput;
@property (nonatomic) BOOL hasCellNrEstimatedThroughput;
@property (nonatomic) unsigned int cellNrEstimatedThroughput;
@property (nonatomic) BOOL hasCellNsaEnabled;
@property (nonatomic) unsigned int cellNsaEnabled;
@property (nonatomic) BOOL hasCellDlBw;
@property (nonatomic) unsigned int cellDlBw;
@property (nonatomic) BOOL hasCellUlBw;
@property (nonatomic) unsigned int cellUlBw;
@property (nonatomic) BOOL hasCellMaxDlCaNumConfigured;
@property (nonatomic) unsigned int cellMaxDlCaNumConfigured;
@property (nonatomic) BOOL hasCellMaxUlCaNumConfigured;
@property (nonatomic) unsigned int cellMaxUlCaNumConfigured;
@property (nonatomic) BOOL hasCellEstimatedLoad;
@property (nonatomic) unsigned int cellEstimatedLoad;
@property (nonatomic) BOOL hasCellEstimatedBw;
@property (nonatomic) unsigned int cellEstimatedBw;
@property (nonatomic) BOOL hasRecommendedlink;
@property (nonatomic) unsigned int recommendedlink;
@property (nonatomic) BOOL hasFr2DBRecommendation;
@property (nonatomic) BOOL fr2DBRecommendation;
@property (nonatomic) BOOL hasLocationDBFR1Count;
@property (nonatomic) unsigned int locationDBFR1Count;
@property (nonatomic) BOOL hasLocationDBFR2Count;
@property (nonatomic) unsigned int locationDBFR2Count;
@property (nonatomic) BOOL hasHighThermalTemperatureNotification;
@property (nonatomic) BOOL highThermalTemperatureNotification;
@property (nonatomic) BOOL hasWiFiThroughput;
@property (nonatomic) unsigned int wiFiThroughput;
@property (nonatomic) BOOL hasWiFiPredictedThroughput;
@property (nonatomic) unsigned int wiFiPredictedThroughput;
@property (nonatomic) BOOL hasWRMRecommendationReason;
@property (nonatomic) unsigned int wRMRecommendationReason;
@property (nonatomic) BOOL hasWifiRecommendationScore;
@property (nonatomic) unsigned int wifiRecommendationScore;
@property (nonatomic) BOOL hasWifiRecommendationConfidence;
@property (nonatomic) unsigned int wifiRecommendationConfidence;
@property (nonatomic) BOOL hasCellularRecommendationScore;
@property (nonatomic) unsigned int cellularRecommendationScore;
@property (nonatomic) BOOL hasCellularRecommendationConfidence;
@property (nonatomic) unsigned int cellularRecommendationConfidence;
@property (nonatomic) BOOL hasRadioCoverage;
@property (nonatomic) unsigned int radioCoverage;
@property (nonatomic) BOOL hasRadioFrequency;
@property (nonatomic) unsigned int radioFrequency;
@property (nonatomic) BOOL hasTriggerReason;
@property (nonatomic) unsigned int triggerReason;
@property (nonatomic) BOOL hasApplicationCategory;
@property (nonatomic) unsigned int applicationCategory;
@property (nonatomic) BOOL hasCellTotalMimoLayers;
@property (nonatomic) unsigned int cellTotalMimoLayers;
@property (nonatomic) BOOL hasTotalNrBandwidth;
@property (nonatomic) unsigned int totalNrBandwidth;

- (BOOL)readFrom:(id)a0;
- (id)description;
- (void)mergeFrom:(id)a0;
- (BOOL)isEqual:(id)a0;
- (void)writeTo:(id)a0;
- (id)copyWithZone:(struct _NSZone { } *)a0;
- (void)copyTo:(id)a0;
- (unsigned long long)hash;
- (void)dealloc;
- (id)dictionaryRepresentation;

@end
