@class NSString, NSURL, NSError, NSObject, NSMutableArray;
@protocol OS_dispatch_queue, OS_os_transaction, OS_dispatch_source;

@interface PQLConnection : NSObject {
    unsigned long long _currentStmtStart;
    NSObject<OS_os_transaction> *_batchStarted;
    int _suspendCaching;
    int _savePointLevel;
    int _skipBatchStop;
    int _vacuumTracker;
    NSMutableArray *_flushNotifications;
    id /* block */ _batchingPolicyHandler;
    NSObject<OS_dispatch_source> *_batchingTimer;
    double _batchingPeriod;
    int _batchingChangesLimit;
    int _batchingChangesCount;
    int _cacheSize;
    BOOL _useBatching;
    BOOL _useQueue;
    BOOL _needsFullSync;
    BOOL _needsBarrierFSync;
    struct cache_s { } *_preparedStatements;
    NSObject<OS_dispatch_source> *_stmtCacheSource;
    NSMutableArray *_stmtCacheCleanupQueue;
    long long _changesOverride;
    NSObject<OS_dispatch_queue> *_targetQueue;
}

@property (copy, nonatomic) NSString *label;
@property (nonatomic, getter=isTraced) BOOL traced;
@property (nonatomic) BOOL crashIfUsedAfterClose;
@property (readonly, copy, nonatomic) NSURL *url;
@property (readonly, nonatomic) struct sqlite3 { } *dbHandle;
@property (readonly, nonatomic) BOOL isInBatch;
@property (readonly, nonatomic) BOOL isInTransaction;
@property (retain, nonatomic) NSError *lastError;
@property (readonly, nonatomic) long long lastInsertedRowID;
@property (readonly, nonatomic) long long changes;
@property (nonatomic) unsigned long long statementCacheMaxCount;
@property (readonly, nonatomic) NSObject<OS_dispatch_queue> *serialQueue;
@property (readonly, nonatomic) double currentOperationDuration;
@property (readonly, copy) NSString *debugDescription;
@property (nonatomic) unsigned long long synchronousMode;
@property (nonatomic) int batchTransactionType;
@property (nonatomic) BOOL shouldUseWALJournalMode;
@property (copy, nonatomic) id /* block */ lockedHandler;
@property (copy, nonatomic) id /* block */ busyHandler;
@property (copy, nonatomic) id /* block */ autoRollbackHandler;
@property (copy, nonatomic) id /* block */ sqliteErrorHandler;
@property (copy, nonatomic) id /* block */ preFlushHook;
@property (copy, nonatomic) id /* block */ postFlushHook;
@property (copy, nonatomic) id /* block */ profilingHook;
@property (copy, nonatomic) id /* block */ willBeginBatchingHook;
@property (copy, nonatomic) id /* block */ didFinishBatchingHook;
@property (readonly, nonatomic) BOOL isBatchSuspended;

+ (void)initialize;

- (BOOL)close:(id *)a0;
- (id)init;
- (id)fetch:(id)a0;
- (void)dealloc;
- (void)flush;
- (id)userVersion;
- (BOOL)execute:(id)a0;
- (void)_resetState;
- (id)description;
- (void).cxx_destruct;
- (BOOL)setUserVersion:(long long)a0;
- (void)assertOnQueue;
- (id)fetchObjectOfClass:(Class)a0 sql:(id)a1;
- (BOOL)openAtURL:(id)a0 sharedCache:(BOOL)a1 error:(id *)a2;
- (BOOL)performWithFlags:(unsigned int)a0 action:(id /* block */)a1;
- (BOOL)setupPragmas;
- (void)useSerialQueue;
- (id)_description:(BOOL)a0;
- (void)forceBatchStart;
- (BOOL)registerFunction:(id)a0 nArgs:(int)a1 handler:(id /* block */)a2;
- (long long)autovacuumableSpaceInBytes;
- (BOOL)backupToURL:(id)a0 progress:(id /* block */)a1;
- (BOOL)execute:(id)a0 args:(char *)a1;
- (BOOL)executeRaw:(id)a0;
- (id)fetch:(id)a0 args:(char *)a1;
- (id)fetchObject:(id /* block */)a0 sql:(id)a1;
- (id)fetchObject:(id /* block */)a0 sql:(id)a1 args:(char *)a2;
- (id)fetchObjectOfClass:(Class)a0 initializer:(SEL)a1 sql:(id)a2;
- (id)fetchObjectOfClass:(Class)a0 initializer:(SEL)a1 sql:(id)a2 args:(char *)a3;
- (id)fetchObjectOfClass:(Class)a0 sql:(id)a1 args:(char *)a2;
- (void)groupInBatch:(id /* block */)a0;
- (BOOL)groupInTransaction:(id /* block */)a0;
- (BOOL)incrementalVacuum:(long long)a0;
- (void)makeNextFlushBarrierFSync;
- (void)makeNextFlushFullSync;
- (BOOL)openAtURL:(id)a0 withFlags:(int)a1 error:(id *)a2;
- (BOOL)performWithFlags:(unsigned int)a0 action:(id /* block */)a1 whenFlushed:(id /* block */)a2;
- (void)useBatchingOnTargetQueue:(id)a0 withPolicyHandler:(id /* block */)a1;
- (void)useBatchingWithDelay:(double)a0 changeCount:(int)a1;
- (void)useSerialQueueWithTarget:(id)a0;
- (BOOL)destroyDatabaseWithError:(id *)a0;
- (void)_clearCleanupCacheQueueIfNeeded;
- (void)_vacuumIfNeeded;
- (void)_batchStartIfNeeded:(int)a0;
- (void)_batchStopIfNeeded;
- (void)_clearStatementCache;
- (void)_createCacheIfNeeded;
- (BOOL)_execute:(id)a0 mustSucceed:(BOOL)a1 bindings:(char *)a2;
- (BOOL)_executeStmt:(id)a0 mustSucceed:(BOOL)a1;
- (void)_fireFlushNotifications;
- (BOOL)_fullSync;
- (BOOL)_incrementalVacuum:(unsigned long long)a0;
- (id)_newStatementForBuilder:(id /* block */)a0;
- (id)_newStatementForFormat:(id)a0 arguments:(char *)a1;
- (BOOL)_performWithFlags:(unsigned int)a0 action:(id /* block */)a1 whenFlushed:(id /* block */)a2;
- (int)_vacuumMode;
- (BOOL)executeSwift:(id /* block */)a0 error:(id *)a1;
- (id)fetchObjectOfClassSwift:(Class)a0 query:(id /* block */)a1 error:(id *)a2;
- (id)fetchObjectSwift:(id /* block */)a0 query:(id /* block */)a1 error:(id *)a2;
- (id)fetchSwift:(id /* block */)a0 error:(id *)a1;
- (void)useBatchingOnTargetQueue:(id)a0 delay:(double)a1 changeCount:(int)a2;
- (void)useBatchingWithPolicyHandler:(id /* block */)a0;

@end
